ENV_SUPATH from login.defs not used when connecting to root user
gravitational/teleport pull request #1004
Opened 2017-05-19 03:12 UTC by aashley

When connecting to a root user on Ubuntu (or any OS using login.defs) the ENV_SUPATH is used to set the default PATH variable value instead of ENV_PATH. Typically ENV_SUPATH has the sbin directories ENV_SUPATH does not.

This patch adds a username variable to the call of getDefaultEnvPath() and if it is root will load the ENV_SUPATH instead of ENV_PATH. This allows granting access to the root user directly while still providing the expected default PATH values.

2017-05-19 03:14 UTC, aashley commented
forgot to commit a line, patch should actually do what it says on the box now

2017-05-30 05:51 UTC, kontsevoy requested changes

2017-05-30 05:51 UTC, kontsevoy commented on lib/srv/exec.go
> +	if osUser == "root" {
if `root` logs in without `ENV_SUPATH` defined, it won't pick up any path at all. instead, it should fall back to `ENV_PATH` in such case.

another question I have: is comparing username to `root` enough if a user is superuser? IMO a better test would be to check UID for 0.

2017-06-03 01:03 UTC, kontsevoy commented
@aashley created an issue #1046 scheduled for the next release.

2017-06-03 01:03 UTC, closed without merging