Update profile on OIDC/SAML login
gravitational/teleport pull request #1025
Opened 2017-05-29 21:21 UTC by russjones

**Purpose**

When logging in using OIDC or SAML save your profile upon successful login.

**Implementation**

* Upon successful login, call `tc.SaveProfile`.

**Related Issue**

Fixes https://github.com/gravitational/teleport/issues/1013

2017-05-29 21:36 UTC, russjones commented
@gravitational-jenkins test this please

2017-05-29 21:49 UTC, russjones commented
@gravitational-jenkins test this please

2017-05-29 21:55 UTC, russjones commented
@gravitational-jenkins test this please

2017-05-30 04:43 UTC, kontsevoy requested changes
Adding `SaveProfile()` inside of `ConnectToProxy()` creates the unexpected side effect. These are two completely different concerns: connecting to a proxy and creating user profiles. 

`ConnectToProxy()` can be called in all kinds of contexts, it's a relatively low level API function. For example, the web UI (!) also calls ConenctToProxy() on the server side. I suspect the side effect in this case would be the creation of `/root/.tsh` directory _on the server_ (!) where the proxy is running.

the only safe place to call `SaveProfile()` is inside of `tsh`, not inside of `lib/client...`

2017-06-02 18:49 UTC, closed without merging