Updated comment
gravitational/teleport pull request #10414
Opened 2022-02-16 20:15 UTC by Erick-Reyes

Update clarifying comment for database section.

2022-02-16 23:06 UTC, zmb3 approved these changes
Approved, but consider a more descriptive commit message so that it's easier to tell what this change is.

2022-02-17 01:30 UTC, russjones approved these changes

2022-02-17 18:31 UTC, webvictim requested changes
Please see comment inline, I think we should keep maps consistent as we don't use this format anywhere else in the file or our docs.

2022-03-17 02:41 UTC, webvictim approved these changes

2022-03-17 02:41 UTC, webvictim commented
/gcbrun

2022-03-17 03:04 UTC, merged