Add support for externally created service account
gravitational/teleport pull request #10515
Opened 2022-02-22 18:10 UTC by stephenwolfe1

This PR add support to disable the serviceAccount creation to allow a serviceAccount to be created outside the helm chart. This is useful for custom cloud integrations like AWS fine grained IAM and managing the serviceAccount separately.

Brings these charts in line with your newer charts as well as standard `helm create my-chart` format.

2022-03-01 21:57 UTC, zmb3 approved these changes

2022-03-10 23:28 UTC, webvictim requested changes
@stephenwolfe1 Thanks for the PR. Couple of changes required and then we can get this merged/backported.

2022-03-28 18:20 UTC, webvictim commented
We have some contribution guidelines for Helm PRs here now: https://github.com/gravitational/teleport/blob/master/examples/chart/CONTRIBUTING.md

2022-04-25 21:01 UTC, webvictim commented
Closing in favour of https://github.com/gravitational/teleport/pull/11895 which implements the same thing and is being actively worked on.

2022-04-25 21:01 UTC, closed without merging