Change get resources api response
gravitational/teleport pull request #10598
Opened 2022-02-24 21:26 UTC by kimlisa

part of [RFD 55](https://github.com/gravitational/teleport/blob/master/rfd/0055-webui-ss-paginate-filter.md#phases-of-work)

#### Description
Wrapped JSON response in an object for resources that were not wrapped to accommodate future changes. Some resources like get database, desktops, and kubes JSON response returned as a list which requires change in the frontend.

2022-02-25 14:38 UTC, rosstimothy approved these changes

2022-02-25 14:54 UTC, espadolini requested changes
`e` was mistakenly changed to an earlier commit, it should be left alone

2022-02-25 16:44 UTC, espadolini approved these changes
Adding fields to our responses to the web UI won't break things, right?

2022-02-25 20:54 UTC, kimlisa commented
> Adding fields to our responses to the web UI won't break things, right?

@espadolini handling backwards compatibility for webassets has been very fuzzy to me. Backwards compat becomes a problem where there are mixed proxy versions: one older version can serve the old webassets, and an api call can go to a newer proxy returning a new response (and vice versa). I'm not sure how realistic it is for proxy versions to be mixed for long though

2022-02-28 22:11 UTC, zmb3 approved these changes

2022-02-28 22:23 UTC, merged