Add in version string definition for role in Terraform reference
gravitational/teleport pull request #10609
Opened 2022-02-25 04:26 UTC by stevenGravy

version was not specified

2022-02-25 15:16 UTC, zmb3 requested changes

2022-02-25 15:16 UTC, zmb3 commented on docs/pages/setup/reference/terraform-provider.mdx
> +`version` is a not required `string` that specifies the role version (default `v3`).
```suggestion
`version` is an optional string that specifies the role version (default `v3`). 
```

2022-02-25 23:59 UTC, stevenGravy commented
@zmb3 changes accepted

2022-02-28 22:01 UTC, ptgott approved these changes

2022-03-23 20:32 UTC, zmb3 approved these changes

2022-03-24 01:48 UTC, merged