Fix certificate extension not being included in `tctl auth sign`
gravitational/teleport pull request #10949
Opened 2022-03-08 12:19 UTC by lxea

This meant that certificates exported with `tctl auth sign` were not including the ssh key extensions.

2022-03-08 14:35 UTC, probakowski approved these changes
LGTM 👍  would be good to add test to make sure it really works

2022-03-08 15:45 UTC, gabrielcorado approved these changes

2022-03-09 13:29 UTC, probakowski requested changes
Thanks for adding test, I think last check can be simplified

2022-03-09 13:29 UTC, probakowski commented on lib/auth/auth_test.go
> +	require.True(t, keyExtensionFound, "Key extension must be found")
```suggestion
	val, ok := key.Extensions[extension.Name]
	require.True(t, ok)
	require.Equal(t, extension.Value, val)
```

2022-03-09 15:39 UTC, probakowski approved these changes
LGTM, thanks @lxea !

2022-03-15 04:35 UTC, r0mant approved these changes
@lxea Let's get this in and backport to v9 also (if the cert. extensions are present in v9).

2022-03-15 14:10 UTC, merged