Allow MFA devices with `/` in names to be deleted
gravitational/teleport pull request #11011
Opened 2022-03-09 21:42 UTC by probakowski

Currently MFA devices with `/` in names can't be removed from UI because `httprouter` can't match correct route as it sees additional path segments despite `:devicename` being correctly escaped (go doesn't treat encoded reserved characters as different from unescaped, deviating from RFC).
This change fixes that by using catch-all route instead, which captures all characters past `/device`.

2022-03-10 10:13 UTC, Tener requested changes
This change fixes the problem with `/webapi/mfa/token/:token/devices/:devicename` endpoint, but does not address other endpoints with exact same problem e.g. `/webapi/sites/:site/desktops/:desktopName`. 

I believe the proper fix should be done at the library level, e.g. by forking `httprouter` and applying https://github.com/julienschmidt/httprouter/pull/209 which was raised to address this exact issue, or in any other way which ensures syntax `:param` works with encoded parameter values.

2022-03-10 16:45 UTC, nklaassen reviewed
Generally agreed with @Tener that we should try to fix this by properly handling escaped characters

2022-03-10 16:45 UTC, nklaassen commented on lib/web/mfa.go
> +		DeviceName: p.ByName("devicename")[1:],
what does this change do?

2022-03-10 16:45 UTC, nklaassen commented on lib/web/apiserver_test.go
> +			require.NoError(t, err)
While we're here testing this, any cases where there should be an error? Can you try to delete a device that doesn't exist, or you don't have permissions for?

2022-03-11 16:19 UTC, Tener commented
I went ahead and tested (https://github.com/gravitational/teleport/pull/11068) that the comprehensive fix appears to be to:
- use patched version of `httprouter`
- enable `.UseRawPath` option added by the patched version.

What do you think?

To be clear, I think we want to reference our own fork of `httprouter` instead of a third-party one, but for POC I think this is good enough.

2022-03-23 20:35 UTC, r0mant commented
@probakowski @Tener Hey guys, if we're going in a different direction like @Tener mentioned, should this one be closed?

2022-03-24 07:25 UTC, Tener commented
> @probakowski @Tener Hey guys, if we're going in a different direction like @Tener mentioned, should this one be closed?

Yeah, I think this makes sense. The tests are definitely useful to show the issue is fixed though.

2022-03-24 08:19 UTC, probakowski commented
Yes, that makes sense, I'll close this one

2022-03-24 08:19 UTC, closed without merging