Allow for probe timeouts to be configurable
gravitational/teleport pull request #11176
Opened 2022-03-16 14:40 UTC by hmadison

When setting up a new Teleport enterprise cluster on GCP,
I noticed that I needed to set the probe timeouts to get the
cluster to be helthy. This seems to be a known issue (https://github.com/kubernetes/kubernetes/issues/89898).

As a "stopgap", I've updated the helm chart to allow for end users
to be able to configure these timeouts.

Closes #11109

2022-03-16 15:30 UTC, codingllama reviewed
Thanks for the contribution, @hmadison!

2022-03-16 15:30 UTC, codingllama commented on examples/chart/teleport-cluster/values.yaml
> +probeTimeout: 1
Suggestion: mention time unit, bump defaults a bit.

```suggestion
probeTimeoutSeconds: 5
```

2022-03-16 15:32 UTC, codingllama commented
@zmb3 and @r0mant, should we look for parity in other charts after this one lands? Seems like a sensible setting to have.

2022-03-16 15:50 UTC, zmb3 commented
> @zmb3 and @r0mant, should we look for parity in other charts after this one lands? Seems like a sensible setting to have.

Seems reasonable to me. @webvictim - thoughts?

2022-03-16 16:22 UTC, webvictim requested changes
Agree with @codingllama's comment regarding making the value a little easier to understand by using a unit in the name.

@hmadison There's also a few other things we'll need before we can approve/merge/backport (sorry, haven't got around to writing the contribution guidelines yet - they're in the works):

1) Please add `probeTimeoutSeconds` at the appropriate location in the `teleport-cluster` chart reference: https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx

2) Please add `probeTimeoutSeconds` to https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.schema.json

3) Please add an example which sets `probeTimeoutSeconds` so it can be validated by the linter - see other examples in https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster/.lint

Thank you!

2022-03-16 19:44 UTC, hmadison commented
@webvictim / @codingllama I've made the requested changes.

2022-03-16 20:06 UTC, codingllama approved these changes
LGTM. Thanks again for contributing!

2022-03-17 02:52 UTC, webvictim approved these changes
LGTM - thanks!

2022-03-17 02:52 UTC, webvictim commented on docs/pages/kubernetes-access/helm/reference.mdx
> +| `integer` | `1` | ✅  |
Teeny tiny space nit

```suggestion
| `integer` | `1` | ✅ |
```

2022-03-17 02:52 UTC, webvictim commented
/gcbrun

2022-03-17 21:52 UTC, russjones approved these changes

2022-03-17 23:48 UTC, webvictim commented
/gcbrun

2022-03-23 20:09 UTC, webvictim commented
@hmadison For ease, I've opened my own PR (#11396) which implements this feature for both Helm charts, adds unit tests and rebases against the new reference updates we've done. I'll push this through and get it backported to `branch/v9` so it comes out in the next Helm chart release.

Thanks for your contribution!

2022-03-23 20:09 UTC, closed without merging