Role Rules
gravitational/teleport pull request #1209
Opened 2017-08-18 19:08 UTC by russjones

**Purpose**

In https://github.com/gravitational/teleport/issues/1200, we describe a list of rules users can operate on and the list of allowable verbs. In this PR we implement those rules and verbs.

**Implementation**

* All old resources were made into rules. `RW` was converted to `connect, list, create, read, readsecrets, update, delete` while `RO` was converted to `list, read`.
* `lib/auth/auth_with_roles.go` was updated to support the new verbs.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1200

2017-08-18 19:17 UTC, klizhentas commented on lib/services/resource.go
> +	// VerbConnect is used to allow you to connect to a remote item.
let's use term `object` instead of item

2017-08-18 19:19 UTC, klizhentas commented on lib/services/role.go
> +func applyImplicitRules(rules map[string][]string) {
applyImplicitRules will add the rules to the database what we agreed to avoid. We agreed to add a role with implicit rules to the role set.

2017-08-18 19:19 UTC, klizhentas requested changes
see my comment about `applyImplicitRules`

2017-08-18 19:27 UTC, kontsevoy requested changes

2017-08-18 19:27 UTC, kontsevoy commented on lib/services/role.go
> +		rules[resource] = verbs
I see a bug here. Write-only resource will get converted to a read-only rule.

2017-08-19 00:39 UTC, russjones commented
@gravitational-jenkins test this please

2017-08-19 00:46 UTC, kontsevoy commented on lib/services/role.go
> +		} else { // write-only
again, "write" access becomes default behavior. what if there's a record with an empty string? it won't contain "write". I would make this explicit: grant RO() only if containsWrite.

2017-08-19 01:20 UTC, russjones commented
@gravitational-jenkins test this please

2017-08-19 01:42 UTC, klizhentas approved these changes

2017-08-21 17:57 UTC, russjones commented
@gravitational-jenkins test this please

2017-08-21 18:01 UTC, russjones commented
@gravitational-jenkins test this please

2017-08-21 18:09 UTC, merged