Session access controls.
gravitational/teleport pull request #1224
Opened 2017-08-25 20:19 UTC by russjones

**Purpose**

As covered in, https://github.com/gravitational/teleport/issues/1223, this PR addresses two issues. The first is the rule names that gate access to various resources. The second is getting a client to a remote auth server with the logged in users role.

**Implementation**

For the first issue, the following three rules gate access to sessions.

* services.KindSSHSession this controls active sessions. This should be hidden from user roles because this is only used by proxies and nodes.
* services.KindSession this controls recorded sessions. This should be exposed to users and used to gate access to endpoints from the audit log where we fetch session playback related events.
* services.KindEvent which is used to access the full audit log and emit events to the audit log.

In addition a new endpoint `/events/sesssion` and function `SearchSessionEvents` has been created that can only return events related to session start and end which is used to reconstruct the list of completed sessions.

For the second issue, the `Dial` function for a `reversetunnel.RemoteSite` has been updated to accept a special string `@remote-auth-server` which returns a TCP connection to the remote auth server. We then build the `authMethods` for the logged in user and establish a SSH connection and from there an client to the auth server. This way we get a client with the users role instead of the role of the proxy.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1223

2017-08-25 20:48 UTC, russjones commented
@gravitational-jenkins test this please

2017-08-25 20:59 UTC, klizhentas commented on lib/auth/apiserver.go
> +	srv.GET("/:version/events/session", srv.withAuth(srv.searchSessionEvents)) // return session related events
comment is redundant

2017-08-25 21:00 UTC, klizhentas commented on lib/auth/clt.go
> +// SearchSessionEvents returns session relayed events to find completed sessions.
session-related

2017-08-25 21:01 UTC, klizhentas commented on lib/events/api.go
>  	SearchEvents(fromUTC, toUTC time.Time, query string) ([]EventFields, error)
why not simply extend query to add query type for session type events instead of adding extra method?

2017-08-25 21:02 UTC, klizhentas commented on lib/reversetunnel/agent.go
> +	log.Infof("got out of band request %v", servers)
`Debugf`

2017-08-25 21:02 UTC, klizhentas commented on lib/reversetunnel/agent.go
>  		log.Error(trace.DebugReport(err))
this is not an error, connection could fail for various reasons

2017-08-25 21:03 UTC, klizhentas commented on lib/reversetunnel/agent.go
> +	var connected bool
connected flag seems redundant, because `conn != nil` should do the same

2017-08-25 21:04 UTC, klizhentas commented on lib/web/apiserver.go
> +// clientWithUserRole will return an auth.ClientI with the role of the user at
this should be a method of ctx

2017-08-25 21:04 UTC, klizhentas commented on lib/web/apiserver.go
> +func remoteClient(ctx *SessionContext, site reversetunnel.RemoteSite) (auth.ClientI, error) {
same here

2017-08-25 21:05 UTC, klizhentas commented on lib/web/apiserver.go
> +func clientWithUserRole(ctx *SessionContext, site reversetunnel.RemoteSite) (auth.ClientI, error) {
clientWithUserRole -> ctx.GetUserClient()

2017-08-25 21:06 UTC, klizhentas commented on lib/web/apiserver.go
> +	clt, err := auth.NewClient("http://stub:0", sshDialer)
you will be creating clients on every request. This client should be associated with active user session and should be deleted when the session closes. Extend the logic of the `SessionContext` to support additional use case.

2017-08-25 21:07 UTC, klizhentas commented on lib/web/apiserver.go
> +			return nil, trace.Wrap(err)
connection above should be closed if you failed to get agent here, otherwise it will be orphaned resource.

2017-08-25 21:07 UTC, klizhentas commented on lib/web/apiserver.go
> +			return nil, trace.Wrap(err)
same here

2017-08-25 21:07 UTC, klizhentas commented on lib/web/apiserver.go
> +			return nil, trace.Wrap(err)
same here

2017-08-25 21:08 UTC, klizhentas requested changes
There are several issues to be fixed with this PR especially around resource handling.

2017-08-26 00:17 UTC, klizhentas commented on lib/web/sessions.go
> +	remoteClt, ok := c.remoteClt[site.GetName()]
this could be accessed concurrently, because the session can be used in multiple requests at the same time.

2017-08-26 00:17 UTC, klizhentas commented on lib/web/sessions.go
> +	remoteClt, ok := c.remoteClt[site.GetName()]
you should protect the access to the client with read write mutex, I suggest to use separate small function with defer for that.

2017-08-26 00:17 UTC, klizhentas commented on lib/web/sessions.go
> +		c.remoteClt[site.GetName()] = rClt
same here.

2017-08-26 00:18 UTC, klizhentas commented on lib/web/sessions.go
> +		c.remoteClt[site.GetName()] = rClt
I think you should call `AddCloser` here to close client if it supports closing

2017-08-26 00:19 UTC, klizhentas commented on lib/web/sessions.go
> +	return clt, nil
probably clt does not support closing directly, but underlying netConn does, so you can return it here with clt explicitly and call AddCloser to close the connection when session ends

2017-08-26 00:19 UTC, klizhentas commented on lib/web/sessions.go
> +		err := remoteClt.Close()
ah, it does, actually, but does it close underlying netConn?

2017-08-26 00:54 UTC, klizhentas approved these changes

2017-08-26 01:04 UTC, merged