Add brief Q&A about how to setup recovery codes
gravitational/teleport pull request #12492
Opened 2022-05-06 18:16 UTC by ulysseskan

Useful for existing customers who were never prompted to setup recovery codes in earlier releases.

2022-05-06 19:31 UTC, zmb3 commented on docs/pages/cloud/faq.mdx
> +## How do I setup recovery codes for my admin account so I don't lose access?
```suggestion
## How do I set up recovery codes for my admin account so I don't lose access?
```

`setup` is a noun

2022-05-06 19:32 UTC, zmb3 requested changes
See comment

2022-05-07 00:26 UTC, zmb3 approved these changes

2022-05-09 20:33 UTC, ptgott approved these changes

2022-06-10 22:51 UTC, merged