Add labels to output of 'tsh kube ls'
gravitational/teleport pull request #12753
Opened 2022-05-18 22:16 UTC by capnspacehook

Example output:

```
Kube Cluster Name Labels             Selected 
----------------- ------------------ --------
cluster1          foo=bar,cmd=result *
```

Fixes #11203.

2022-05-19 15:26 UTC, ibeckermayer requested changes

2022-05-19 15:26 UTC, ibeckermayer commented on lib/kube/utils/utils.go
> +	for n := range uniqueClusters {
nit: `n` could be more descriptive `cluster`

2022-05-19 15:26 UTC, ibeckermayer commented on lib/kube/utils/utils.go
> +func extractAndSortKubeClusterNames(kss []types.Server) []string {
Can't we make this call `extractAndSortKubeClusters` and then just add the names to a list? That way we don't need to maintain effectively the same logic in two places.

2022-05-19 15:26 UTC, ibeckermayer commented on lib/kube/utils/utils.go
> +	kubeClusters := make([]*types.KubernetesCluster, 0, len(uniqueClusters))
```suggestion
	kubeClusters := make([]*types.KubernetesCluster, len(uniqueClusters))
```

2022-05-21 16:44 UTC, ibeckermayer commented on lib/kube/utils/utils.go
> +	kubeClusters := make([]*types.KubernetesCluster, 0, len(uniqueClusters))
Yeah you're right, ignore me

2022-05-24 15:00 UTC, ibeckermayer approved these changes

2022-05-24 18:37 UTC, r0mant commented
@timothyb89 Can you please review this?

2022-05-31 18:41 UTC, r0mant approved these changes

2022-05-31 19:11 UTC, timothyb89 approved these changes

2022-06-01 17:52 UTC, merged