Re-add `kinds` config field to tbot with a deprecation warning
gravitational/teleport pull request #12933
Opened 2022-05-25 23:55 UTC by timothyb89

This re-adds the `kinds` config field with a deprecation warning. We removed the field in #11596 but due to strict YAML parsing this causes existing otherwise compatible configs to error out.

We should instead remove the field after a sane migration period in v11 or so.

2022-05-26 07:50 UTC, strideynet approved these changes

2022-05-26 11:34 UTC, LKozlowski approved these changes

2022-05-26 14:07 UTC, zmb3 commented on tool/tbot/config/config_destination.go
> +	// removed in a future release in v11 or later.
+1

2022-05-26 14:07 UTC, zmb3 requested changes

2022-05-26 14:07 UTC, zmb3 commented on tool/tbot/config/config_destination.go
> +			"safely be removed the configuration file.")
```suggestion
			"safely be removed from the configuration file.")
```

2022-05-26 15:01 UTC, timothyb89 commented on tool/tbot/config/config_destination.go
> +			"safely be removed the configuration file.")
🤦

2022-05-26 15:05 UTC, timothyb89 commented on tool/tbot/config/config_destination.go
> +	// removed in a future release in v11 or later.
Done!

2022-05-27 19:34 UTC, zmb3 approved these changes

2022-05-27 21:26 UTC, merged