Remove deprecated trusted cluster http endpoints.
gravitational/teleport pull request #12968
Opened 2022-05-27 01:31 UTC by Joerger

Follow up to https://github.com/gravitational/teleport/pull/6103

2022-05-27 03:56 UTC, zmb3 approved these changes

2022-05-27 15:42 UTC, jakule requested changes
Those endpoints are still being used by our tests and maybe somewhere in our application code. Look on the tests run failures.

2022-05-31 17:38 UTC, Joerger commented
> Those endpoints are still being used by our tests and maybe somewhere in our application code. Look on the tests run failures.

"/:version/trustedclusters/validate" is still in use and I had accidentally removed it. Thanks for pointing that out, I've added it back. The other four endpoints are safe to remove.

2022-06-01 15:38 UTC, jakule approved these changes

2022-06-02 00:30 UTC, merged