Refactored Trusted Cluster state change.
gravitational/teleport pull request #1313
Opened 2017-09-13 22:10 UTC by russjones

**Purpose**

Simplify the Trusted Cluster state change code to be easier to reason about.

**Implementation**

* Explicit state machine.
* We now return an error when trying to delete a Trusted Cluster that does not exist.

**Related Issues**

n/a

2017-09-13 22:12 UTC, russjones commented
@gravitational-jenkins retest this please

2017-09-13 22:27 UTC, kontsevoy approved these changes
Looks good, but I would return an error saying that updating existing trusted clusters is not supported (unless they are changing the enabled/disabled flag). And maybe the error message should say if they want to change other fields, they have to re-create the TC

2017-09-13 22:31 UTC, kontsevoy requested changes
also noticed that the code could have been a lot more concise in those helper methods.

2017-09-13 22:31 UTC, kontsevoy commented on lib/auth/trustedcluster.go
> +	err := a.UpsertReverseTunnel(reverseTunnel)
this entire block can be replaced with:
```
return trace.Wrap(a.UpsertReverseTunnel(reverseTunnel))
```

2017-09-13 22:31 UTC, kontsevoy commented on lib/auth/trustedcluster.go
> +	err = a.DeactivateCertAuthority(services.CertAuthID{Type: services.HostCA, DomainName: t.GetName()})
this entire block can be replaced with:

```
return trace.Wrap(a.DeactivateCertAuthority(services.CertAuthID{Type: services.HostCA, DomainName: t.GetName()}))
```

2017-09-13 22:31 UTC, kontsevoy commented on lib/auth/trustedcluster.go
> +	err = a.ActivateCertAuthority(services.CertAuthID{Type: services.HostCA, DomainName: t.GetName()})
same as below

2017-09-14 01:14 UTC, kontsevoy approved these changes

2017-09-14 02:41 UTC, klizhentas reviewed
a couple of nitpicks, but otherwise looks good.

2017-09-14 02:41 UTC, klizhentas commented on lib/auth/trustedcluster.go
> +func canChangeState(ec services.TrustedCluster, nc services.TrustedCluster) error {
I would make this a method of Trusted cluster, `TrustedCluster.CanChangeStateTo(other) -> error`

2017-09-14 02:41 UTC, klizhentas commented on lib/auth/trustedcluster.go
> +	switch {
switch looks really nice

2017-09-14 18:03 UTC, russjones commented
@gravitational-jenkins retest this please

2017-09-14 18:05 UTC, klizhentas approved these changes

2017-09-14 18:21 UTC, merged