[v9] `tsh` list resources accross proxies and clusters (#12934)
gravitational/teleport pull request #13313
Opened 2022-06-08 19:46 UTC by atburke

Backport of #12934.

2022-06-08 20:06 UTC, r0mant approved these changes

2022-06-08 23:35 UTC, timothyb89 approved these changes

2022-06-09 00:45 UTC, jakule requested changes
I think this PR needs to wait for https://github.com/gravitational/teleport/pull/13321 as currently master doesn't work.

2022-06-16 18:26 UTC, jakule approved these changes

2022-06-16 19:09 UTC, merged