[v8] Access request compatibility for servers without v2 api
gravitational/teleport pull request #13427
Opened 2022-06-13 18:13 UTC by xacrimon

Backport #13373 to branch/v8

2022-06-13 18:15 UTC, r0mant approved these changes

2022-06-13 20:09 UTC, codingllama approved these changes

2022-06-13 22:41 UTC, zmb3 approved these changes

2022-06-14 03:15 UTC, zmb3 requested changes
Removing approval until we verify the fix.

2022-06-14 03:16 UTC, r0mant requested changes
This fix doesn't appear to work, same error from CI when publishing teleport-plugins as before:

```
Original Error: *trace.NotImplementedError unknown method GetAccessRequestsV2 for service proto.AuthService
Stack Trace:
	/go/pkg/mod/github.com/gravitational/teleport/api@v0.0.0-20220613212417-f490ba2be6ed/client/client.go:765 github.com/gravitational/teleport/api/client.(*Client).GetAccessRequests
	/workspace/access/jira/app.go:319 github.com/gravitational/teleport-plugins/access/jira.(*App).onJiraWebhook
	/workspace/access/jira/webhook_server.go:123 github.com/gravitational/teleport-plugins/access/jira.(*WebhookServer).processWebhook
	/go/pkg/mod/github.com/rw-access/httprouter@v1.3.1-0.20210321233808-98e93175c124/router.go:474 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/usr/local/go/src/net/http/server.go:2879 net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:1930 net/http.(*conn).serve
	/usr/local/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: unknown method GetAccessRequestsV2 for service proto.AuthService
```

2022-06-14 14:25 UTC, codingllama commented on api/client/client_test.go
> +		require.NoError(t, m.grpc.Serve(l))
```suggestion
		assert.NoError(t, m.grpc.Serve(l))
```

Avoid "t.Fatal"-ing in goroutines.

2022-06-14 14:25 UTC, codingllama commented on api/client/client_test.go
> +func TestAccessRequestDowngrade(t *testing.T) {
Nice, can we forward-port this test?

2022-06-14 14:37 UTC, codingllama commented on api/client/client_test.go
> +func TestAccessRequestDowngrade(t *testing.T) {
Nevermind, already done.

2022-06-14 15:01 UTC, codingllama approved these changes

2022-06-14 22:15 UTC, zmb3 approved these changes

2022-06-15 07:03 UTC, marcoandredinis approved these changes

2022-06-15 07:17 UTC, xacrimon commented
fyi @r0mant you'll need to approve this in order to merge

2022-06-15 15:41 UTC, r0mant approved these changes

2022-06-16 10:47 UTC, merged