fix ec2 join check
gravitational/teleport pull request #13706
Opened 2022-06-21 20:53 UTC by fspmarshall

Fixes https://github.com/gravitational/teleport/issues/13677

2022-06-21 21:19 UTC, nklaassen requested changes

2022-06-21 21:19 UTC, nklaassen commented on lib/auth/join_ec2.go
> +		instanceExists = true
```suggestion
		instanceExists = false
```

2022-06-21 21:22 UTC, fspmarshall commented on lib/auth/join_ec2.go
> +		instanceExists = true
lmao, one sec.

2022-06-21 21:25 UTC, nklaassen approved these changes

2022-06-22 13:22 UTC, zmb3 commented
Can we add test coverage to prevent future regressions?

2022-06-23 05:56 UTC, fspmarshall commented
@zmb3 Catching this kind of regression requires proper integration testing.  We have integration tests that would have caught this, but it seems they aren't run because they rely on the real EC2 api.

2022-06-23 18:49 UTC, nklaassen commented
> Catching this kind of regression requires proper integration testing. We have integration tests that would have caught this, but it seems they aren't run because they rely on the real EC2 api.

fwiw that test still passes and nothing seems broken, I only found this because I noticed the logs

2022-06-27 21:33 UTC, rosstimothy approved these changes

2022-06-28 22:14 UTC, fspmarshall commented
> fwiw that test still passes and nothing seems broken, I only found this because I noticed the logs

@nklaassen ah, didn't realize that.  Looks like test was able to pass if the ssh service successfully heartbeats, even if the node couldn't finish all startup steps. Updated the existing integration test to now require that the node actually emits `TeleportReady` and confirmed that it fails without the fix in this PR.  This will ensure that going forward, test doesn't pass unless all required certs are successfully acquired.

2022-06-28 22:50 UTC, zmb3 commented on integration/ec2_test.go
> +		t.Fatal("timeout waiting for node readyness")
```suggestion
		t.Fatal("timeout waiting for node readiness")
```

2022-06-29 01:05 UTC, merged