[v9] Refine the organization of /docs/getting-started
gravitational/teleport pull request #13746
Opened 2022-06-22 16:17 UTC by ptgott

Backports #12923

Fixes #12921

This removes the DigitalOcean link on the /docs/getting-started page
and moves the DigitalOcean guide into /docs/setup/deployments, which is
a more appropriate home. Now, the "Deploy to production" section of
/docs/getting-started only includes links to the Getting Started
guide for the Open Source, Cloud, and Enterprise editions, making it
clearer to users that there are three editions and that we have separate
content for each one.

This also changes the href of the Teleport Cloud link on the Getting
Started page to /cloud/getting-started/?scope=cloud to be
consistent with the other links, which direct users to guides.

2022-06-24 22:47 UTC, zmb3 approved these changes

2022-07-05 20:10 UTC, klizhentas requested changes

2022-07-05 20:10 UTC, klizhentas commented on docs/config.json
> +              "hideInScopes": ["enterprise", "cloud"]
remove hide in scopes

2022-07-07 20:56 UTC, ptgott commented
@klizhentas After rebasing, the change no longer includes `hideInScopes`.

2022-07-11 19:33 UTC, stevenGravy approved these changes

2022-07-15 18:49 UTC, ptgott commented
@klizhentas Just following up to see if my most recent commit to this PR makes the changes you requested. Thanks!

2022-07-22 19:01 UTC, ptgott commented
@klizhentas I am following up on this PR. Thanks!

2022-07-29 20:39 UTC, klizhentas approved these changes

2022-08-02 20:28 UTC, merged