[v9] Correctly handle Firestore pagination with DocumentID cursors
gravitational/teleport pull request #13757
Opened 2022-06-22 18:08 UTC by xacrimon

Backport #13017 to branch/v9

2022-06-22 18:18 UTC, strideynet approved these changes

2022-06-22 19:02 UTC, Joerger approved these changes

2022-08-29 18:19 UTC, r0mant requested changes
@xacrimon We know that upgrading crypto/ssh (which we've done in v10+) breaks old SSH clients that do not support the new signature algorithms. Can we find a way to fix this Firestore issue without bumping crypto/ssh in v9 branch?

2022-09-07 15:45 UTC, xacrimon commented
@r0mant I've reverted the package update changes as they weren't actually needed for the bug fix to work.

2022-09-07 15:52 UTC, somethingnew2-0 approved these changes

2022-09-14 16:58 UTC, somethingnew2-0 commented
We’re currently on the v9 release for our deployment of Teleport in GCP with the Firestore backend. Can this be merged and released?

2022-09-16 17:58 UTC, r0mant approved these changes

2022-09-16 18:21 UTC, merged