[v9] Move Auth/Proxy-only Kubernetes guides
gravitational/teleport pull request #13778
Opened 2022-06-22 22:29 UTC by ptgott

Backports #13068

See #12654

The Kubernetes Access section includes guides for using the Kubernetes
Service as well as guides for running the Auth and Proxy Service on
Kubernetes. This is misleading, since (a) you can run the Auth/Proxy
on Kubernetes without using Kubernetes Access and (b) you can use
Kubernetes Access without running the Auth/Proxy on Kubernetes.

This change focuses on the pages in:

/docs/pages/kubernetes-access/getting-started/

- Move docs/pages/kubernetes-access/getting-started guides that don't
  relate to Kubernetes Access out of this section, and change the
  docs/pages/kubernetes-access/getting-started.mdx page to point to
  the current "Agent" guide.

- Edit the "docs/pages/getting-started.mdx" menu page to accommodate the
  Kubernetes guides. Previously, this page included separate links for
  each edition's getting started guide. To add the Kubernetes Cluster
  guide, I organized the links in the "Deploy to production" section into
  a TabItem for each Teleport edition. There are separate links to the
  Kubernetes Cluster guide, one for OSS users and one for Enterprise
  users. These links also take users to the appropriate scope.

2022-06-24 22:41 UTC, zmb3 approved these changes

2022-07-05 20:08 UTC, klizhentas requested changes

2022-07-05 20:08 UTC, klizhentas commented on docs/config.json
> +              "hideInScopes": "cloud"
@ptgott please remove `hideInScopes`

2022-07-07 21:09 UTC, ptgott commented
@klizhentas after rebasing, the changes no longer include `hideInScopes`.

2022-07-11 19:34 UTC, stevenGravy approved these changes

2022-07-15 18:50 UTC, ptgott commented
@klizhentas Just following up to see if the changes you requested have now been made

2022-07-22 19:10 UTC, ptgott commented
@klizhentas Just following on this one since you requested changes. Thanks!

2022-07-29 20:40 UTC, klizhentas approved these changes

2022-07-29 21:12 UTC, merged