[v9] Move Helm deployment guides
gravitational/teleport pull request #13803
Opened 2022-06-23 15:39 UTC by ptgott

Backports #13105

See #12654

The Kubernetes Access section includes guides for using the Kubernetes
Service as well as guides for running the Auth and Proxy Service on
Kubernetes. This is misleading, since (a) you can run the Auth/Proxy
on Kubernetes without using Kubernetes Access and (b) you can use
Kubernetes Access without running the Auth/Proxy on Kubernetes.

This change focuses on our Helm deployment guides. These guides
are not related to the Kubernetes Service, but rather to deploying
the Auth Service and Proxy Service on Kubernetes. I've suggested
moving these guides to a /setup/helm-deployments section for visibility.

2022-06-24 22:39 UTC, zmb3 approved these changes

2022-07-05 20:10 UTC, klizhentas requested changes

2022-07-05 20:10 UTC, klizhentas commented on docs/config.json
> +          "hideInScopes": "cloud",
Please remove `hideInScopes`

2022-07-06 20:48 UTC, ptgott commented
@klizhentas I've removed the `hideInScopes` fields from `config.json`.

2022-07-15 18:50 UTC, ptgott commented
@klizhentas Just following up to see if the changes you requested have now been made

2022-07-22 19:18 UTC, ptgott commented
@klizhentas Just following up on this since you requested changes. Thanks!

2022-07-29 20:39 UTC, klizhentas approved these changes

2022-08-04 22:10 UTC, merged