tctl: Clarify message if tctl is called before teleport is ever run
gravitational/teleport pull request #13975
Opened 2022-06-29 15:04 UTC by EdwardDowling

2022-06-29 17:14 UTC, r0mant requested changes

2022-06-30 23:59 UTC, r0mant approved these changes

2022-06-30 23:59 UTC, r0mant commented on lib/utils/utils.go
> +		return "", trace.Wrap(trace.ConvertSystemError(err), "unable to find host_uuid file: teleport start must be called first")
Yep, looks alright now.

2022-07-01 16:02 UTC, atburke approved these changes

2022-07-04 09:39 UTC, merged