Optimize tsh db ls performance
gravitational/teleport pull request #14092
Opened 2022-07-05 02:01 UTC by greedy52

2022-07-05 10:22 UTC, smallinsky commented on tool/tsh/db.go
> +				errors.Add(trace.Wrap(err))
I think that we can improve readability by using one of the  main GO principle: 
> Do not communicate by sharing memory; instead, share memory by communicating

What would you say about just inlining struct definition for result types like: 
```go
type databaseResult struct {
  databases []types.Database
  err error
}

type rolesResult struct {
  databases []types.Database
  err error
}
... 
if err != nil {
    dbResultC <- databaseResult{err: trace.Wrap(err))
    return
}
dbResultC <- databaseResult{databases: clusterDatabases)

``` 

and then using chan for communication:
```go

dbResults := <- databasesC
rolesResults  := <- rolesC

if err := trace.NewAgg(dbResult.err, rolesResults.err); err != nil {
   return err
}
```

2022-07-06 07:52 UTC, smallinsky reviewed
I wonder if we can cover this flow somehow in the tsh test. 
For example, we can use our own dialer  with custom timeout and inject this in tsh test to simulate low latency between the tsh client and teleport proxy.

2022-07-06 09:28 UTC, espadolini reviewed
Have we considered the idea of having the allowed database users retrieved and returned as part of `ListDatabases` instead, to avoid the extra roundtrips to also fetch the rolesets?

sidenote: we don't seem to care about showing the list of database users when we're outputting databases in json format, perhaps we could skip the extra fetches in that case?

2022-07-06 09:28 UTC, espadolini commented on tool/tsh/db.go
> +						dbListings.Add(databaseListing{
This has far too much synchronization - we can just give each goroutine a slice of `databaseListing` to fill, can't we? Locking a rwlock (or even a mutex) on every swap in a sort would be quite slow.

2022-07-06 09:28 UTC, espadolini commented on tool/tsh/db.go
> +			go func() {
This is mostly a duplicate of the `onListDatabases` code in a loop anyway, just with all clusters in each profile rather than just the active one.

2022-07-06 11:12 UTC, espadolini commented
additional question: do we absolutely need all the changes to parallelize `ListDatabases` and `ConnectToProxy/FetchAllClusterRoles` instead of opening one less `ProxyClient` and using the same one for databases *and* roles?

2022-07-06 12:40 UTC, espadolini reviewed
Additional point raised by @rosstimothy: we should be careful about parallelizing connections - a profile with a lot of leaf clusters will cause a massive amount of outbound connections when doing `listDatabasesAllClusters` in a cluster with a lot of leaves.

2022-07-07 05:03 UTC, greedy52 commented on lib/services/role.go
> +		return NewRoleSet(roles...), nil
The current implementation calls `FetchRoles` which also does `NewRoleSet`.

2022-07-07 05:04 UTC, greedy52 commented on tool/tsh/db.go
> +			go func() {
It was a prototype just trying to see how fast it can get. I end up reverted `go func()` here and used an `errgroup.Go` per profile.

2022-07-07 10:37 UTC, smallinsky reviewed
Nice,  I have left one comment but aport from that the fix looks good for me.

2022-07-07 12:04 UTC, espadolini requested changes

2022-07-07 15:51 UTC, greedy52 commented on tool/tsh/db.go
> +	group.SetLimit(runtime.NumCPU())
Fixed to `4` with a comment.

2022-07-07 15:52 UTC, espadolini approved these changes

2022-07-07 15:52 UTC, greedy52 commented on tool/tsh/db.go
>  	sort.Sort(dbListings)
yes, you are right. context is cancelled by `group.Wait` but it's possible the list is still being updated.

2022-07-07 15:55 UTC, greedy52 commented on tool/tsh/db.go
> +			proxy, err := tc.ConnectToProxy(cf.Context)
updated to reuse the `proxy` for this part too. We may want to investigate later how to reuse proxy client inside `client.TeleportClient`.

2022-07-07 16:15 UTC, rosstimothy approved these changes
Looks good to me. We probably want to consider adding some tracing bits to the new stuff added here. It might also be worthwhile to capture traces before and after this change. That would really show the performance gains and also help identify any areas that could still be improved upon.

2022-07-08 08:48 UTC, smallinsky approved these changes

2022-07-09 20:22 UTC, merged