Sasha/dynamo
gravitational/teleport pull request #1448
Opened 2017-11-10 20:33 UTC by klizhentas

Update DynamoDB backend

* Add support for TTL
* Add support for Batch reads
* Update default values
* Use batch reads to retrieve nodes

2017-11-11 01:10 UTC, russjones requested changes
Code looks good, documentation needs to be added for the Terraform modules.

2017-11-11 01:10 UTC, russjones commented on lib/services/local/presence.go
> +	// fast getter of the items extension
What about something like `getter is used to make batch requests to the backend.`

2017-11-13 18:04 UTC, klizhentas commented on lib/backend/dynamo/dynamodbbk.go
> +		return err
no wrap here intentionally to preserve original error

2017-11-13 18:04 UTC, klizhentas commented on lib/backend/dynamo/dynamodbbk.go
> +		return err
same here

2017-11-13 19:17 UTC, russjones approved these changes

2017-11-13 19:46 UTC, merged