[v10] Docs update version 10.0.1
gravitational/teleport pull request #14524
Opened 2022-07-15 17:27 UTC by stevenGravy

Update docs OSS, ent to 10.0.1

2022-07-15 17:32 UTC, ptgott approved these changes

2022-07-15 18:59 UTC, r0mant requested changes
Looks good but let's not merge this yet as there's some issue with plugins 10.0.1 publishing. If we merge this, all plugins links will be broken.

Requesting changes so we don't merge this accidentally.

2022-07-18 13:55 UTC, zmb3 approved these changes

2022-07-18 21:12 UTC, stevenGravy commented
@r0mant ok to go now?

2022-07-19 21:44 UTC, r0mant approved these changes

2022-07-19 22:41 UTC, merged