[v10] Shutdown TCP socket on Go-side close
gravitational/teleport pull request #14996
Opened 2022-07-28 14:37 UTC by xacrimon

Backport #14703 to branch/v10

2022-07-28 17:41 UTC, ibeckermayer approved these changes

2022-07-29 22:09 UTC, zmb3 requested changes
Requesting changes as I don't think this fixes the issue.

2022-08-08 18:49 UTC, xacrimon commented
@zmb3 I've cherry-picked over the other PR to this one too, could you re-review?

2022-08-08 18:52 UTC, zmb3 approved these changes

2022-08-08 20:52 UTC, merged