[v9] Add custom unmarshal for second_type factor (#10203)
gravitational/teleport pull request #15202
Opened 2022-08-04 11:56 UTC by tobiaszheller

Backport #15197 to branch/v9

2022-08-04 12:18 UTC, strideynet approved these changes

2022-08-04 12:18 UTC, strideynet requested changes
It looks like this backport has broken due to an import.

2022-08-04 12:43 UTC, strideynet approved these changes

2022-08-08 13:31 UTC, tigrato approved these changes

2022-08-08 13:32 UTC, rosstimothy approved these changes

2022-08-09 08:36 UTC, merged