Fix mux detect HTTP protocol
gravitational/teleport pull request #15300
Opened 2022-08-08 11:20 UTC by smallinsky

## What 
After introducing https://github.com/gravitational/teleport/pull/12426 mux tries recognise connection protocol based on 8 bytes peek. This logic was ganged and the peek length was extended from 3 to 8 bytes. 

In case of detecting http protocol  the length of `methods` elements is always less than 8 bytes thus the order HasPrefix call should be changed from `if bytes.HasPrefix(verb, in)` to `bytes.HasPrefix(in, verb)`

2022-08-08 13:10 UTC, greedy52 approved these changes

2022-08-08 14:34 UTC, zmb3 approved these changes

2022-11-03 14:55 UTC, zmb3 requested changes

2022-11-03 14:55 UTC, zmb3 commented on lib/multiplexer/multiplexer_test.go
> +				require.NoError(t, err)
You can't call `require.NoError` in a goroutine like this.

2023-04-07 15:39 UTC, zmb3 commented
@smallinsky do we still want this change?

2023-04-12 07:00 UTC, smallinsky commented
@zmb3  
No, I think that this is not longer needed so I'm closing it for now. Thanks

2023-04-12 07:00 UTC, closed without merging