Kubernetes IO via Websockets
gravitational/teleport pull request #15475
Opened 2022-08-12 14:03 UTC by tigrato

TODO:

- Extend support for  `port-forward`
- Extend support for  `attach`
- Extend support for  `cp`
- Check how to test this
- Fix errors triggered in the server 
```

E0812 14:58:52.931107   28994 conn.go:254] Error on socket receive: read tcp 192.168.1.236:3027->192.168.1.236:58501: use of closed network connection
E0812 14:58:53.312284   28994 v2.go:151] use of closed network connection
```
Fixes #15463

2022-08-12 15:56 UTC, alex-astronomer commented
Let me know if there's anything I can help with to move this forward.  Facing the same issue as #15484 #15474 #15463

2022-09-01 01:52 UTC, r0mant approved these changes

2022-09-01 18:02 UTC, codingllama reviewed
Comments so far, I'm still to take a closer look at kube_mock.go.

2022-09-01 18:03 UTC, codingllama requested changes
(Marking as request changes for now.)

2022-09-01 18:31 UTC, tigrato commented on lib/kube/proxy/remotecommand_websocket.go
> +Copyright 2016 The Kubernetes Authors.
I followed the same criteria used by Sasha with K8S files eg. `lib/kube/proxy/remotecommand.go`

2022-09-01 19:06 UTC, tigrato commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +		// TODO: I don't belong here, I should be abstracted from this class
this is original comment from vendor file

2022-09-01 19:06 UTC, tigrato commented on lib/kube/proxy/testing/kube_server/kube_mock.go
> +		log:    *log.NewEntry(log.New()),
It was a mistake followed by an LSP autocomplete

2022-09-01 19:11 UTC, codingllama commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +		// TODO: I don't belong here, I should be abstracted from this class
If we don't know that it means then let's take it out, otherwise it's just noise.

2022-09-01 19:25 UTC, tigrato commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +		if err != gwebsocket.ErrBadHandshake {
this code is vendored

2022-09-01 19:26 UTC, tigrato commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +	req, err := http.NewRequest(method, u.String(), nil)
Vendor code and it's only used in tests. Is it worth a change?

2022-09-01 19:26 UTC, tigrato commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +		return nil, fmt.Errorf("error sending request: %v", err)
Vendor code and it's only used in tests. Is it worth a change?

2022-09-01 19:27 UTC, tigrato commented on lib/kube/proxy/testing/websocket/dummy_client.go
> +		return nil, fmt.Errorf("error closing response body: %v", err)
same as before

2022-09-01 19:34 UTC, codingllama commented
@tigrato, could you elaborate more about the changes in the PR description as well?

2022-09-09 15:52 UTC, codingllama approved these changes

2022-09-09 16:55 UTC, merged