Logout from everywhere
gravitational/teleport pull request #1591
Opened 2018-01-15 07:16 UTC by dhilipkumars

Are you looking for something like this?

The user is 
``
echo $USER
d
``
Login
```
$./build/tsh login --proxy=localhost --insecure --user=d@example.com
WARNING: You are using insecure connection to SSH proxy https://localhost:3080
Enter password for Teleport user d@example.com:
Enter your OTP token:
*******
WARNING: You are using insecure connection to SSH proxy https://localhost:3080

You are now logged in
```
and when you logout
```
./build/tsh logout
d is not logged in, but logging out of everywhere
```

and the keydir is 
```
ls -lrt ~/.tsh/
total 0
```

#1541

2018-01-15 17:42 UTC, klizhentas commented
ok to test

2018-01-15 17:42 UTC, klizhentas commented
looks good to me, @kontsevoy wyt?

2018-01-15 17:43 UTC, klizhentas commented
also, can you use `rebase` for simple commits like this, I'm trying to reduce the amount of merge commits in master

2018-01-15 18:07 UTC, klizhentas commented on lib/client/profile.go
> +		fmt.Printf("%s is not logged in, but logging out of everywhere\n", username)
remove but

2018-01-15 18:08 UTC, klizhentas commented on lib/client/keystore.go
> +	//Now recreate initalize it
this comment is redundant, simply repeats what next line does

2018-01-15 18:08 UTC, klizhentas commented on lib/client/keystore.go
> +	//Empty the content of keyDir and recreate it
same here

2018-01-15 18:08 UTC, klizhentas commented on lib/client/keystore.go
> +// CleanupAll
comment does not match the function name

`Cleanup cleans up local key store of keys`

2018-01-15 18:28 UTC, dhilipkumars commented
@klizhentas PTAL now.

2018-01-16 17:50 UTC, klizhentas commented
@dhilipkumars last rebase and I will merge, I promise :)

2018-01-16 18:10 UTC, dhilipkumars commented
@klizhentas Done, No problem. :-)

2018-01-16 19:34 UTC, russjones approved these changes

2018-01-16 21:48 UTC, russjones requested changes
@dhilipkumars, during testing I actually found a problem (if you log in with multiple identities, `tsh logout` will not log you out of all of them) that needs to be resolved before we can merge this PR.

Before we get into the fix for that, it's probably helpful to cover the expected behavior of `tsh logout`.

1. If no username is specified, `tsh logout` should remove all keys for all users under `~/.tsh`.
1. If a username is specified, `tsh logout --username` should only remove keys for the specified user.

The problem is the following block in `LogoutFromEverywhere`: [profile.go#L128-L135](https://github.com/gravitational/teleport/blob/2590e716c336c8434cde8339d532e82650bc5f5f/lib/client/profile.go#L128-L135). This is a legacy from when Teleport only supported local accounts and didn't support external identity providers which allowed `tsh logout` to derive the Teleport username from the Linux user.

To fix this, let's not try and derive the username. Instead of no username is passed in, it implies that all users should be logged out. If a username is provided, then get keys for that user and log them out.

@klizhentas @kontsevoy What do you think?

2018-01-17 10:58 UTC, dhilipkumars commented
@russjones without a username is there a way to create ?

```
agent, err := NewLocalAgent("", username)
	if err != nil {
		return trace.Wrap(err)
	}
```
Or should we simpy send in? a special user to be used under these circumstances? 
```
agent, err := NewLocalAgent("", "nobody or AllUsers")
```

2018-01-17 12:04 UTC, dhilipkumars commented
>  during testing I actually found a problem (if you log in with multiple identities, tsh logout will not log you out of all of them) that needs to be resolved before we can merge this PR.

Also apart from clearing `~/.tsh` directory is there anything else to be performed for external identity providers?

2018-01-17 19:46 UTC, kontsevoy commented
will take a look later today

2018-01-20 02:20 UTC, russjones commented
@dhilipkumars I was working on a related issue https://github.com/gravitational/teleport/issues/1611, which caused me to re-factor `LocalKeyAgent` and remove `GetKeys` completely. Once `GetKeys` was gone I had to fix logout as well because it relied on `GetKeys` existing: https://github.com/gravitational/teleport/pull/1618.

I'm going to close this PR because this issue has been resolved. We appreciate the help in narrowing down and resolving this issue!

2018-01-20 02:20 UTC, closed without merging