[v10] bump go mod go1.18
gravitational/teleport pull request #16088
Opened 2022-09-02 09:57 UTC by lxea

Closes #13958

2022-09-02 10:03 UTC, reedloden approved these changes

2022-09-02 10:06 UTC, marcoandredinis commented on go.mod
> -	github.com/gravitational/license v0.0.0-20210218173955-6d8fb49b117a
Those should not be removed
It usually happens when you don't have the `e` submodule

2022-09-02 10:14 UTC, reedloden requested changes

2022-09-02 10:14 UTC, reedloden commented on go.mod
> -	github.com/gravitational/reporting v0.0.0-20210923183620-237377721140
Same here as above

2022-09-02 10:14 UTC, reedloden commented on go.sum
> -github.com/gravitational/license v0.0.0-20210218173955-6d8fb49b117a h1:PN5vAN1ZA0zqdpM6wNdx6+bkdlQ5fImd75oaIHSbOhY=
Same as above

2022-09-02 10:14 UTC, reedloden commented on go.sum
> -github.com/gravitational/reporting v0.0.0-20210923183620-237377721140 h1:UACNXsuOXxe2dpjn3SA2g4YUgOoZTxQ6yf+QYAYcQMc=
Same as above

2022-09-02 10:19 UTC, reedloden approved these changes

2022-09-02 10:24 UTC, marcoandredinis approved these changes

2022-09-05 09:28 UTC, espadolini commented on go.mod
> +	golang.org/x/exp v0.0.0-20220613132600-b0d781184e0d
Missing a `go mod tidy` here; if it doesn't change anything, put all the required imports in the same group and run it again.

2022-09-05 10:55 UTC, espadolini approved these changes

2022-09-05 11:42 UTC, tcsc approved these changes

2022-09-08 14:18 UTC, r0mant approved these changes

2022-09-08 14:54 UTC, merged