Adds event-handler systemd example
gravitational/teleport pull request #16460
Opened 2022-09-16 02:07 UTC by stevenGravy

2022-09-21 14:19 UTC, alexfornuto requested changes
Thanks for the updates! I've made some suggestions, and posed a question or two.

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/deploy-a-cluster/helm-deployments/aws.mdx
> +  ```yaml
Adds a space between copy and code fence.
```suggestion
  to the values file in the next step.
  
  ```yaml
```

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/deploy-a-cluster/helm-deployments/aws.mdx
> +  separateMongoListener: true
Should we include the parent key above these two, so folks know where to insert these keys into the values file?

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +update the `teleport-event-handler.toml` file to use fully qualified paths and copy into `/etc/`.
```suggestion
The above steps are an example Fluentd configuration. In production, we 
recommend starting the Teleport plugin daemon via an init system like
 systemd.
 
First, copy `teleport-event-handler` to `/usr/local/bin`. Then update the
`teleport-event-handler.toml` file to use fully qualified paths, and move
it into `/etc/`.
```

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +## Setup with systemd
This this section be numbered, and the sections above have their `/6` updated?

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +for systemd:
Hadn't hit 80 chars:

```suggestion
Here's the recommended Teleport plugin service unit file for systemd:
```

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +(!examples/systemd/plugins/teleport-event-handler.service!)
I assume this is an include because we have or expect to have other pieces of content where this example can be reused?

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +supported by systemd.
```suggestion
Save this as `teleport-event-handler.service` in either `/usr/lib/systemd/system/`
or another [unit file load path](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path)
supported by systemd.
```

2022-09-21 14:19 UTC, alexfornuto commented on docs/pages/management/guides/fluentd.mdx
> +$ sudo systemctl start teleport-event-handler
```suggestion
$ sudo systemctl enable --now teleport-event-handler
```

2022-10-14 19:23 UTC, zmb3 commented
@stevenGravy are you still looking to merge this or should I close it out?

2022-10-15 20:20 UTC, closed without merging