[Docs] correct disable_create_host_user reference
gravitational/teleport pull request #16798
Opened 2022-09-28 17:07 UTC by alexfornuto

The existing reference had an extraneous `s`.

2022-09-28 17:16 UTC, r0mant approved these changes

2022-09-28 17:40 UTC, zmb3 requested changes
Also needs to be fixed in `host-user-creation.mdx`.

2022-10-04 20:42 UTC, ptgott approved these changes

2022-10-05 05:06 UTC, zmb3 approved these changes

2022-10-17 13:19 UTC, merged