Key Generation Fixes
gravitational/teleport pull request #1686
Opened 2018-02-15 00:39 UTC by russjones

**Purpose**

This PR resolves several issues. The fix for https://github.com/gravitational/teleport/issues/1640 is uninteresting and https://github.com/gravitational/teleport/issues/1638 no longer exists due to refactoring in https://github.com/gravitational/teleport/pull/1679.

https://github.com/gravitational/teleport/issues/1639 is the core of this PR. The native key generator has been updated to no longer be a singleton, the key pool size has increased, and the pool is used in the recording proxy (which leads to better performance when connecting to a proxy).

**Implementation**

* Removed the singleton implementation of the native key generator. Instead a single key generator is created per Teleport process that is shared across the service.
* The precomputed keys are now used in the recording proxy, this should decrease time to connect to a node when using the recording proxy.
* Due to the above, the size of the precomputed keys has increased from 10 to 25.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1640
Fixes https://github.com/gravitational/teleport/issues/1639
Fixes https://github.com/gravitational/teleport/issues/1638

2018-02-15 00:50 UTC, russjones commented
@gravitational-jenkins retest this please

2018-02-15 06:02 UTC, klizhentas requested changes
I think keygen service should be called on service shutdown in lib/service/service.go then

2018-02-15 21:36 UTC, russjones commented
@gravitational-jenkins retest this please

2018-02-16 01:01 UTC, klizhentas approved these changes

2018-02-16 01:25 UTC, merged