Add option to disable the `ServiceAccount` creation for `teleport-kube-agent chart`
gravitational/teleport pull request #16876
Opened 2022-09-30 09:45 UTC by tigrato

When assigning AWS IAM permissions to Teleport, `eksctl create iamserviceaccount` command manages the ServiceAccount lifecycle. 

This PR allows any user to configure a Kubernetes ServiceAccount used by the agent.

2022-09-30 15:55 UTC, hugoShaka commented
Hey, I'm sorry: I forgot to update the `teleport-kube-agent` chart when merging https://github.com/gravitational/teleport/pull/16337

Could you use the same value names than the `teleport-cluster` chart so both charts are aligned?

After checking quickly what the Helm community is doing it seems most modern charts converged to the signature

```
serviceAccount:
  create: true
  name: ""
  # ...
```

2022-09-30 15:56 UTC, hugoShaka requested changes
Hey, I'm sorry: I forgot to update the `teleport-kube-agent` chart when merging https://github.com/gravitational/teleport/pull/16337

Could you use the same value names than the `teleport-cluster` chart so both charts are aligned?

After checking quickly what the Helm community is doing it seems most modern charts converged to the signature

```
serviceAccount:
  create: true
  name: ""
  # ...
```

2022-09-30 15:59 UTC, hugoShaka commented on examples/chart/teleport-kube-agent/tests/serviceaccount_test.yaml
> +  - it: sets ServiceAccount labels when specified
Copy-paste error

2022-09-30 16:43 UTC, hugoShaka approved these changes

2022-09-30 21:10 UTC, probakowski approved these changes

2022-10-03 15:11 UTC, alexfornuto approved these changes

2022-10-03 15:25 UTC, merged

2022-10-31 15:24 UTC, alexfornuto commented
@tigrato the backporting for the PR is failing the [linter](https://console.cloud.google.com/cloud-build/builds;region=us-west1/e25bb59e-3bef-48b5-888f-7de068d02721?project=ci-account) checks.