[v10] Add option for `tsh` to load all CAs (#15178)
gravitational/teleport pull request #17398
Opened 2022-10-13 17:55 UTC by atburke

Backport #15178 to branch/v10

2022-10-13 18:55 UTC, zmb3 requested changes
Requesting changes until flaky test is fixed.

2022-10-13 18:55 UTC, zmb3 commented on lib/client/keyagent_test.go
> +	rootCASigner, rootTrustedCerts := generateCA("example.com")
This code is flaky. I fixed it in master - please cherry-pick the fix into this PR as well.

2022-10-13 21:20 UTC, ptgott approved these changes
Approving from the docs side

2022-10-14 02:56 UTC, zmb3 approved these changes

2022-10-20 18:21 UTC, merged