Backport [v9] Added file copying role option and node config option
gravitational/teleport pull request #17796
Opened 2022-10-25 16:19 UTC by capnspacehook

Backport of #15144

2022-10-25 20:52 UTC, ptgott approved these changes

2022-10-27 18:37 UTC, jakule requested changes
Let's hold on with merging it for now.

2022-11-17 21:31 UTC, ptgott commented
@capnspacehook @jakule Following up on this one. Should we fix the conflicts while we hold off on merging?

2022-11-17 22:12 UTC, jakule commented
@ptgott I'm closing this PR. We wanted to port this change to v9 as a part of the security fix but then decided to port just the security fix without the code in this PR.

2022-11-17 22:12 UTC, closed without merging