Updated error logging.
gravitational/teleport pull request #1806
Opened 2018-03-22 18:10 UTC by russjones

**Purpose**

Cleanup error logging.

**Implementation**

When `utils.FatalError` is called, check if a user message has been embedded in the error. If it has the user message prefixes the wrapped error. If not, it prefixes a generic user message: "A fatal error occurred".

Here are a few examples of what these errors will look like:

```
$ teleport start
Initialization failed: mkdir /var/lib/teleport: permission denied
```
```
$ teleport start
A fatal error occurred: mkdir /var/lib/teleport: permission denied
```
```
$ teleport start -d

ERROR REPORT:
Original Error: *os.PathError mkdir /var/lib/teleport: permission denied
Stack Trace:
	/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/service/service.go:335 github.com/gravitational/teleport/lib/service.NewTeleport
	/home/rjones/Development/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:168 github.com/gravitational/teleport/tool/teleport/common.OnStart
	/home/rjones/Development/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:148 github.com/gravitational/teleport/tool/teleport/common.Run
	/home/rjones/Development/go/src/github.com/gravitational/teleport/tool/teleport/main.go:29 main.main
	/usr/local/go/src/runtime/proc.go:204 runtime.main
	/usr/local/go/src/runtime/asm_amd64.s:2338 runtime.goexit
User Message: Initialization failed
```

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1798

2018-03-22 18:11 UTC, klizhentas approved these changes

2018-03-26 23:11 UTC, kontsevoy requested changes
I couldn't test this because it does not build. I am getting this error:

```
luna ~/go/src/github.com/gravitational/teleport: make full
VERSION=2.6.0-alpha.0 make -f version.mk setver
make[1]: Entering directory '/home/ekontsevoy/go/src/github.com/gravitational/teleport'
make[1]: Leaving directory '/home/ekontsevoy/go/src/github.com/gravitational/teleport'
Building Teleport with PAM support.
make -s -j 3 build/teleport build/tctl build/tsh
# github.com/gravitational/teleport/vendor/github.com/coreos/etcd/client
vendor/github.com/coreos/etcd/client/keys.go:30:2: can't find import: "github.com/gravitational/teleport/vendor/github.com/ugorji/go/codec"
Makefile:61: recipe for target 'build/teleport' failed
make[1]: *** [build/teleport] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:54: recipe for target 'all' failed
make: *** [all] Error 2
```

Also this looks too complex. If printing a _correct_ error message requires type assertions it means we're returning broken errors. How come we don't do this in other places and it works?

2018-03-26 23:20 UTC, kontsevoy approved these changes

2018-03-26 23:21 UTC, kontsevoy commented
[udpate] rjones and I have resolved issues on my machine in-person.

2018-03-27 01:00 UTC, merged