Added logging for audit stream creation.
gravitational/teleport pull request #18591
Opened 2022-11-18 00:43 UTC by russjones

Added logging for stream creation errors. This will surface AWS/GCP/MinIO credentials/configuration issues and log them.

2022-11-18 23:16 UTC, zmb3 requested changes

2022-11-18 23:16 UTC, zmb3 commented on lib/auth/grpcserver.go
> +				log.Errorf("Failed to create audit stream: %q.", err)
`GRPCServer` embeds a log entry.
```suggestion
				g.Errorf("Failed to create audit stream: %q.", err)
```

2022-11-19 01:27 UTC, russjones commented on lib/auth/grpcserver.go
> +				log.Errorf("Failed to create audit stream: %q.", err)
Fixed.

2022-11-19 02:57 UTC, zmb3 approved these changes

2022-11-23 22:39 UTC, r0mant approved these changes

2022-11-24 00:15 UTC, merged