Disable FuzzMongoRead test due to instability
gravitational/teleport pull request #19418
Opened 2022-12-15 23:23 UTC by jentfoo

Disabling this test due to flakiness when fuzzing.  I have filed this internal issue to track fixing the root causes of instability for us to be able to re-enable fuzzing here: https://github.com/gravitational/security-findings/issues/21

2022-12-15 23:31 UTC, zmb3 approved these changes

2022-12-16 16:00 UTC, r0mant approved these changes

2022-12-16 16:12 UTC, jakule requested changes
I think we should disable this test in the Open Fuzz instead of here. This test still runs as a part of our UT suite now.

It should be disabled here:
https://github.com/gravitational/teleport/blob/129ae1d05828df097ecc62a04ce90dff5efaef78/fuzz/oss-fuzz-build.sh#L80-L81

2022-12-16 16:13 UTC, jakule approved these changes

2022-12-16 16:34 UTC, merged