Switch golang.org/x/crypto to gravitational fork
gravitational/teleport pull request #19579
Opened 2022-12-21 17:46 UTC by jakule

2022-12-28 19:21 UTC, hatched approved these changes

2022-12-28 19:21 UTC, hatched commented on go.mod
> +	// Use our internal crypto fork, to work around the issue with OpenSSH <= 7.6 mentioned here: https://github.com/golang/go/issues/53391
Do we have an issue somewhere to track reverting this change once this issue has been resolved upstream?

2023-01-03 15:59 UTC, jakule commented
@fspmarshall Friendly ping.

2023-01-03 17:08 UTC, zmb3 approved these changes

2023-01-03 17:10 UTC, zmb3 commented
cc @rosstimothy for awareness - we'll have to keep our fork up to date as upstream changes

2023-01-03 17:42 UTC, codingllama requested changes
Could you update the following files as well?

* api/go.mod -> needs the same replace as base go.mod, and it has the same "do not update" warning (https://github.com/gravitational/teleport/blob/master/api/go.mod#L32-L36).

* .github/dependabot.yml -> please move crypto to the forked/replaced section (https://github.com/gravitational/teleport/blob/master/.github/dependabot.yml#L19), for both go.mod and api/go.mod entries.

2023-01-03 17:42 UTC, codingllama commented on go.mod
> +	golang.org/x/crypto v0.2.0
```suggestion
	golang.org/x/crypto v0.2.0 // replaced
```

so it's easier to spot when we do dependency updates. Same for api.

2023-01-03 18:57 UTC, jakule commented
> Does this change allow us to update dependencies which in turn depend on > `x/crypto v0.2.0`?

@rosstimothy Yes, with this change, we can use `x/crypto` HEAD.

2023-01-03 20:28 UTC, codingllama commented
> Could you update the following files as well?
> 
> * api/go.mod -> needs the same replace as base go.mod, and it has the same "do not update" warning (https://github.com/gravitational/teleport/blob/master/api/go.mod#L32-L36).
> * .github/dependabot.yml -> please move crypto to the forked/replaced section (https://github.com/gravitational/teleport/blob/master/.github/dependabot.yml#L19), for both go.mod and api/go.mod entries.

Missing dependabot.yml?

2023-01-03 21:51 UTC, jakule commented
@codingllama Sorry, I missed that. Fixed https://github.com/gravitational/teleport/pull/19579/commits/981e541dd172b497dcc483599ff53ed0afbb1f0b

2023-01-03 22:24 UTC, codingllama approved these changes

2023-01-04 19:30 UTC, merged