Add remote tsh support test plan.
gravitational/teleport pull request #20055
Opened 2023-01-10 20:12 UTC by Joerger

Test plan section for remote `tsh` support detailed in [RFD 95](https://github.com/gravitational/teleport/pull/18032)

2023-01-11 11:46 UTC, smallinsky approved these changes

2023-01-11 11:46 UTC, smallinsky commented on .github/ISSUE_TEMPLATE/testplan.md
> +4. In you local terminal, `tsh logout`.
```suggestion
4. In your local terminal, `tsh logout`.
```

2023-01-11 11:46 UTC, smallinsky commented on .github/ISSUE_TEMPLATE/testplan.md
> +6. In you local terminal, `tsh login` as a different user. `tsh` commands should still fail.
```suggestion
6. In your local terminal, `tsh login` as a different user. `tsh` commands should still fail.
```

2023-01-11 11:46 UTC, smallinsky commented on .github/ISSUE_TEMPLATE/testplan.md
> +    - [ ] `tsh ssh user@node` successfully connects to node with with confirmation and mfa prompts.
```suggestion
    - [ ] `tsh ssh user@node` successfully connects to node witw confirmation and MFA prompts.
```

2023-01-11 11:46 UTC, smallinsky commented on .github/ISSUE_TEMPLATE/testplan.md
> +1. [ ] `tsh login` as user with [Webauthn](https://goteleport.com/docs/access-controls/guides/webauthn/) login with per-session MFA required: `auth_service.authentication.require_session_mfa: yes` or
```suggestion
1. [ ] `tsh login` as a user with [Webauthn](https://goteleport.com/docs/access-controls/guides/webauthn/) login with per-session MFA required: `auth_service.authentication.require_session_mfa: yes` or `role.role_options.require_session_mfa: yes`.
```

2023-01-11 15:28 UTC, mdwn approved these changes

2023-01-12 04:35 UTC, jakule requested changes
Let's wait with the changes, as we will probably miss v12 test plan with these features.

2023-01-26 02:21 UTC, closed without merging