[v12] Add usage events for certificate issuance and additional session types (#20662)
gravitational/teleport pull request #21188
Opened 2023-02-02 23:03 UTC by timothyb89

Backport of #20662 for branch/v12

---

* Add usage events for certificate issuance and additional session types

This adds a new usage event for certificate issuance, emitted whenever a new user certificate is generated. These events include an anonymized username, TTL, and basic info about which requests are present on the certificate (e.g. db/app/k8s requests).

Additionally, this captures additional session event types from the audit log, including database, app, and desktop sessions, and also properly tags k8s exec sessions which were previously grouped together with SSH.

* Add `SessionStartV2` events, add `is_bot` flag to cert events

* Drop redundant `Event` prefix on `UsageCertificteIssued` event

* Rename `CertificateIssuedEvent` -> `UserCertificateIssuedEvent`

2023-02-02 23:20 UTC, michellescripts approved these changes

2023-02-03 07:47 UTC, marcoandredinis approved these changes

2023-02-03 10:08 UTC, espadolini requested changes
Blocking until we have the server side running in prod.

2023-02-03 11:03 UTC, marcoandredinis commented
> Blocking until we have the server side running in prod.

Should we block until we deploy to prod the client?
The client should be able to gracefully discard those events, right?
Also, V12 is not going to be deployed to Cloud tenants any time soon (only when we hit 12.1 if I'm not mistaken)

We are aiming to backport at least 2 PRs as soon as this one gets merged (to avoid creating a mess with merge conflits)
What do you think about unblocking this backport?

I'm ok with blocking the v11 backport until we reach production with the prehog changes

2023-02-03 12:03 UTC, espadolini commented
@logand22 are we 100% confident about getting prehog updated in prod before 12.1 is released?

2023-02-03 16:41 UTC, espadolini approved these changes

2023-02-03 18:09 UTC, merged