[v10] Bump cloud version to 11.3.3
gravitational/teleport pull request #21671
Opened 2023-02-10 21:03 UTC by jimbishopp

Teleport Cloud was upgraded to 11.3.3 on 2/9. See: https://github.com/gravitational/cloud/issues/3375

2023-02-10 21:23 UTC, alexfornuto requested changes

2023-02-10 21:23 UTC, alexfornuto commented on docs/config.json
> +      "major_version": "11",
This should still be 10 for V10, no?

2023-02-10 22:16 UTC, alexfornuto approved these changes

2023-02-11 00:09 UTC, zmb3 approved these changes

2023-02-11 00:09 UTC, merged