Rjones/trusted 3
gravitational/teleport pull request #2193
Opened 2018-08-29 17:20 UTC by russjones

**Purpose**

Fixes an issues where users can not SSO login using `tsh` on clusters that have 8 or more trusted clusters attached to it.

**Implementation**

* Upon successful login on the server, only send back the servers own host CA.
* Upon successful login on the client, connect to the Auth Server and pull down all host CAs and update known hosts file.

_Changes to proxy public address_.

If `public_addr` and `ssh_public_addr` are not set, then whatever is passed in the `--proxy` flag will be used for the HTTP and SSH endpoints of the proxy.

If only `public_addr` is set, the value for `public_addr` will be used for the HTTP proxy endpoint and whatever is passed in `--proxy` will be used for the SSH endpoint.

If only `ssh_public_addr` is set, then the value for `ssh_public_addr` will be used for the SSH proxy endpoint and whatever is passed in `--proxy` will be used for the SSH endpoint.

If both `public_addr` and `ssh_public_addr` are set, then the value for `public_addr` will be used for the HTTP proxy endpoint and the value for `ssh_public_addr` will be used for the SSH proxy endpoint. The `--proxy` endpoint will be ignored after the initial connection to the proxy.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/2192

2018-08-29 23:09 UTC, russjones commented
@gravitational-jenkins retest this please

2018-08-30 21:53 UTC, klizhentas requested changes

2018-08-30 21:53 UTC, klizhentas commented on lib/client/api.go
> +	ProxySSHHost string
I would like to move back to HostPort notation instead of Host and Port, as it's more consistent with kubernetes and is more compact.

2018-08-30 21:53 UTC, klizhentas commented on lib/client/profile.go
> +	ProxySSHPort int `yaml:"proxy_ssh_port,omitempty"`
I would like this to be consistent with `kube_proxy_addr`, so `proxy_ssh_addr` and `proxy_addr` respectively.

2018-08-31 23:15 UTC, klizhentas approved these changes

2018-08-31 23:33 UTC, merged