[v12] Fix links with long redirect chains
gravitational/teleport pull request #22503
Opened 2023-03-01 19:40 UTC by ptgott

**Note to reviewers:** This is not a backport—we'll need to forward port this to `master`

2023-03-06 15:00 UTC, alexfornuto requested changes
Because this changelog file lives above the `docs/pages` content it's never rendered on the site, only on GitHub. This change means that the links will point to these docs on GitHub instead of the docs site where they are rendered correctly.

2023-03-07 21:40 UTC, ptgott commented
@alexfornuto The Changelog page within the docs (https://raw.githubusercontent.com/gravitational/teleport/master/docs/pages/changelog.mdx) loads CHANGELOG.md as a partial, so writing the links like this ensures that, within the docs site, CHANGELOG links always refer to the currently selected version of the docs. If you use the full URLs, these links always refer to the default docs version.

I thought having links to MD files from the CHANGELOG.md was a small price to pay. What do you think?

2023-03-08 19:17 UTC, alexfornuto commented
>The Changelog page within the docs (https://raw.githubusercontent.com/gravitational/teleport/master/docs/pages/changelog.mdx) loads CHANGELOG.md as a partial, 

I did not realize that, my bad.

2023-03-08 19:17 UTC, alexfornuto approved these changes

2023-03-20 15:39 UTC, stevenGravy approved these changes

2023-03-21 21:51 UTC, merged