Add support for CA pinning when joining a cluster.
gravitational/teleport pull request #2273
Opened 2018-10-05 19:18 UTC by russjones

**Purpose**

Improve UX around validation of the Auth Server when joining a cluster.

**Implementation**

* Support an insecure method to join a cluster. This can be used with dynamic or static tokens to join a cluster without validating the identity of the Auth Server.
* Support validating the identity of the Auth Server with a CA on disk.
* Support validating the identity of the Auth Server with a CA pin.

See https://github.com/gravitational/teleport/issues/2237 for further design details.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/2237

2018-10-05 20:44 UTC, russjones commented
@gravitational-jenkins retest this please

2018-10-15 00:29 UTC, klizhentas requested changes

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/apiserver.go
> +	srv.GET("/:version/ca", srv.withAuth(srv.getLocalCA))
cacert

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/apiserver.go
> +// getLocalCA returns the CAs for the local cluster without signing keys.
getLocalCACert here and below

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/clt.go
> +	GetLocalCA() (*LocalCAResponse, error)
GetClusterCACert?

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/register.go
> +	cert, foundCA, err := readCA(params)
you dont need third bool var - just return and check for trace.NotFound

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/register.go
> +		log.Infof("Joining remote cluster %v with CA file.", cert.Subject.CommonName)
CA file is meaningless to users, trusted cluster certificate?

2018-10-15 00:29 UTC, klizhentas commented on lib/auth/register.go
> +		log.Warnf("Joining remote cluster with insecure CA configuration to Auth Server. " +
remove CA, make it clear why its insecure give instructions how to fix this

2018-10-15 21:17 UTC, klizhentas approved these changes

2018-10-15 21:17 UTC, klizhentas commented
@russjones create a separate ticket for Ev and add to the milestone please

2018-10-15 23:44 UTC, merged