Update predeploy_job.yaml
gravitational/teleport pull request #23077
Opened 2023-03-14 19:59 UTC by yjperez

Adding the ability to allow for requests and limits to be added to the predeploy_job like already done for deployments.

2023-03-14 21:28 UTC, hugoShaka requested changes
The template change looks good :)

Can you add tests covering the feature? 

You can find [test guidelines here](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/tests/README.md), and might want to copy the [main deployment resource tests](https://github.com/gravitational/teleport/blob/addb839509e13226348edecec20c5c3d592824c3/examples/chart/teleport-cluster/tests/auth_deployment_test.yaml#LL109-L127).

2023-03-15 14:43 UTC, yjperez commented
@hugoShaka I have added the tests. It was my first time building those, please let me know if I missed something.

2023-03-15 14:57 UTC, hugoShaka approved these changes
LGTM once the suggestions are addressed

2023-03-15 14:57 UTC, hugoShaka commented on examples/chart/teleport-cluster/tests/predeploy_test.yaml
> +  - it: should set resources when set in values
idem
```suggestion
  - it: should set resources on proxy redeploy job when set in values
```

2023-03-15 16:42 UTC, r0mant approved these changes
@yjperez Do you want to backport this? If so, can you add respective `backport/branch/xxx` labels to the PR.

2023-03-15 16:45 UTC, yjperez commented
@r0mant no, this is only applicable starting Teleport V12.

2023-03-15 16:47 UTC, r0mant commented
> no, this is only applicable starting Teleport V12.

@yjperez Then you need `backport/branch/v12` label?

2023-03-15 17:23 UTC, merged