Order sudoers file lines by role name
gravitational/teleport pull request #23760
Opened 2023-03-29 12:16 UTC by lxea

Fix for #23095

2023-03-30 08:30 UTC, LKozlowski approved these changes

2023-03-30 08:30 UTC, LKozlowski commented on lib/services/role.go
> +		if cmp := strings.Compare(a.GetName(), b.GetName()); cmp == 0 || cmp == 1 {
```suggestion
		if cmp := strings.Compare(a.GetName(), b.GetName()); cmp != -1 {
```

2023-03-30 16:00 UTC, r0mant reviewed
@lxea Can you include an update to the docs in this PR to add a note saying how sudoer lines will be ordered in our [Host User Creation](https://goteleport.com/docs/server-access/guides/host-user-creation/) guide?

2023-04-03 11:30 UTC, smallinsky requested changes

2023-04-03 11:30 UTC, smallinsky commented on lib/services/role.go
> +		return true
```suggestion
                return strings.Compare(a.GetName(), b.GetName()) == -1

```

2023-04-03 13:46 UTC, smallinsky requested changes

2023-04-03 13:46 UTC, smallinsky commented on lib/services/role_test.go
> +						HostSudoers: []string{"sudoers entry 4"},
Can we extend it to: 
```suggestion
						HostSudoers: []string{"sudoers entry 4", "sudoers entry 1"},
```
to test deduplications ?

2023-04-03 13:46 UTC, smallinsky commented on lib/services/role.go
> +				}
I think that sill this logic is buggy. The final result of `finalSudoers`  will contain a duplication if a sudoers entry is duplicated across different roles 

See: https://github.com/gravitational/teleport/pull/23760/files#diff-1d9446cc64e6fb429df775e3d773435dce3c1e02b49cb0a03ed43ee1d4519f9aR6095

2023-04-12 06:45 UTC, smallinsky approved these changes

2023-04-18 16:03 UTC, r0mant approved these changes

2023-04-19 09:10 UTC, merged