[v12] Distroless doc updates
gravitational/teleport pull request #24036
Opened 2023-04-04 11:52 UTC by tcsc

Documentation updates making "distroless" the default image

2023-04-04 13:46 UTC, stevenGravy requested changes
Make work with existing docker installation https://goteleport.com/docs/management/guides/docker/.  This currently fails

2023-04-04 15:23 UTC, ptgott commented
Just to double-check, does this need to be forward ported to `master` (or was there already a PR for `master`?)

2023-04-07 00:08 UTC, r0mant approved these changes
lgtm once Steven's comment about something not working is addressed.

2023-04-07 15:29 UTC, ptgott requested changes
I could have sworn I left a review of this earlier, but I'm not seeing it in the PR conversation. In any case, the Markdown tables are formatted incorrectly and do not render as tables. We should make sure this looks okay on the docs dev server before merging.

2023-04-07 15:32 UTC, ptgott commented on docs/pages/includes/docker-images-oss.mdx
> +The `*-debug` images are intended for troubleshooting deployments, and are not indended for production use.
```suggestion
The `*-debug` images are intended for troubleshooting deployments, not for production use. These include a shell and BusyBox to help you investigate issues.
```

2023-04-07 15:32 UTC, ptgott commented on docs/pages/includes/enterprise/docker-images.mdx
> +The `*-debug` images are intended for troubleshooting deployments, and are not indended for production use.
```suggestion
The `*-debug` images are intended for troubleshooting deployments, not for production use. These include a shell and BusyBox to help you investigate issues.
```

2023-04-11 06:42 UTC, tcsc commented
> I could have sworn I left a review of this earlier

The review you're thinking of was on `master`. This is a backport. Fixed in both.

2023-04-11 15:09 UTC, ptgott approved these changes

2023-04-11 15:13 UTC, stevenGravy approved these changes
lgtm

2023-04-11 22:25 UTC, merged