Fixes to metrics docs
gravitational/teleport pull request #24200
Opened 2023-04-06 14:37 UTC by pschisa

Based on my testing, setting Teleport in debug mode is not required to expose the metrics

~~~
# cat /etc/systemd/system/teleport.service
ExecStart=/usr/local/bin/teleport start  --config=/etc/teleport.yaml --diag-addr=http://172.31.36.239:3434 --pid-file=/run/teleport/teleport.pid

# cat /etc/teleport.yaml
teleport:
  log:
    severity: INFO

# curl http://172.31.36.239:3434/metrics | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP audit_failed_disk_monitoring Number of times disk monitoring failed.
# TYPE audit_failed_disk_monitoring counter
audit_failed_disk_monitoring 0
# HELP audit_failed_emit_events Number of times emitting audit event failed.
# TYPE audit_failed_emit_events counter
audit_failed_emit_events 0
# HELP audit_percentage_disk_space_used Percentage disk space used.
# TYPE audit_percentage_disk_space_used gauge
audit_percentage_disk_space_used 100
# HELP audit_server_open_files Number of open audit files
# TYPE audit_server_open_files gauge
audit_server_open_files 0
...
~~~

Also, curling the diag endpoint without the metrics part returns a 404 page not found which is a confusing way to validate it is working

~~~
# curl http://172.31.36.239:3434/
404 page not found
~~~

2023-04-06 14:45 UTC, rosstimothy requested changes
This is included in several diagnostics pages, some of which do actually require `--debug` in order to work(most notably collecting pprof profiles).

2023-04-06 14:48 UTC, zmb3 approved these changes

2023-04-06 16:23 UTC, pschisa commented
hmmm so this might not be a simple change after all.  I'll check how the doc's team wants to proceed @ptgott @alexfornuto

2023-04-06 20:09 UTC, alexfornuto commented
It looks to me like `docs/pages/management/diagnostics/profiles.mdx` is the only page that expects the `--debug` flag in this partial. I tested a solve locally where we can add the extra flag when needed using a partial variable, and if we're all happy with that I can push it to this branch.

2023-04-07 15:48 UTC, alexfornuto approved these changes

2023-04-07 17:45 UTC, pschisa commented on docs/pages/includes/diagnostics/diag-addr-prereqs-tabs.mdx
> +    $ curl http://127.0.0.1:3000/metrics
Is it better to note that the expectation is a 404 in that case?  Or is there a better endpoint to probe?  Would recommending a ps aux statement be more appropriate?

2023-04-07 18:07 UTC, pschisa commented on docs/pages/includes/diagnostics/diag-addr-prereqs-tabs.mdx
> +    $ curl http://127.0.0.1:3000/metrics
I agree that would be better, returns a nice status OK

2023-04-07 18:09 UTC, rosstimothy approved these changes
🎉

2023-04-07 18:37 UTC, merged

2023-04-07 19:22 UTC, pschisa commented
v10 and v11 did not get the debug added so not backport required