Improve performance of MFA ceremony
gravitational/teleport pull request #24250
Opened 2023-04-06 22:04 UTC by rosstimothy

To date clients attempting to access a resource first have to call `proto.AuthService/IsMFARequired` to determine if an mfa ceremony is needed for access to a resource. In an effort to reduce an extra round trip to the Auth server this can can be bundled into `proto.AuthService/GenerateUserSingleUseCerts`.

In order for RBAC to determine if mfa is required for SSH sessions the OS login of the session must be known. To accomodate this a new `SSHLogin` field was added to `proto.UserCertsRequest`.

The response to the initial request of the stream now contains a `proto.MFARequired` enum which indicates whether mfa is required, not required, or it's unknown if mfa is required. The last variant should only be returned when the `SSHLogin` field is unset in the initial request.

The `(auth.Server) isMFARequired` check was also modified for nodes to make use of `ListResources`. Instead of retrieving **all** nodes into memory and finding the matching ones, a request is made to `ListResources` with the `SearchKeywords` populated with the target from `proto.IsMFARequiredRequest_Node.Node.Node`. Care was taken to filter out any matches from labels to preserve the original matching behavior.

2023-04-12 18:11 UTC, Joerger approved these changes

2023-04-12 18:12 UTC, Joerger requested changes
Sorry, I didn't mean to approve yet ^

2023-04-12 21:21 UTC, codingllama commented on lib/auth/grpcserver_test.go
> +		require.ErrorIs(t, err, io.EOF)
```suggestion
		require.ErrorIs(t, err, io.EOF, "Want the server to close the stream when MFA is not required")
```

2023-04-12 21:21 UTC, codingllama commented on lib/auth/grpcserver_test.go
> +	if challenge.MFARequired == proto.MFARequired_MFA_REQUIRED_NO && err != nil {
I'm surprised the error happens here. Based on how I've seen other streams behave, I would expect the Send to succeed and the error to only pop up in the next Recv.

2023-04-12 21:21 UTC, codingllama commented on lib/client/api.go
> +	if mfaErr != nil && !errors.Is(mfaErr, MFARequiredUnknownErr{}) && !errors.Is(mfaErr, services.ErrSessionMFANotRequired) {
Could we get this covered by tests, somehow? Is it worth the trouble?

2023-04-12 21:21 UTC, codingllama commented on lib/client/cluster_client.go
> +			clt, err := c.tc.ConnectToCluster(ctx)
```suggestion
			clusterClient, err := c.tc.ConnectToCluster(ctx)
```

(or whatever specific this is, it it's not that)

2023-04-12 21:21 UTC, codingllama commented on lib/client/cluster_client.go
> +		if params.MFACheck != nil && !params.MFACheck.Required {
In what situation would `params.MFACheck` be non-nil here? Is it trustworthy without a previous call to `IsMFARequired`?

(I genuinely don't know, so I assume a "casual" observer wouldn't either.)

2023-04-12 21:21 UTC, codingllama commented on lib/client/cluster_client.go
> +		params.MFACheck = check
Why is it relevant to set this here? Should we be setting it in the other cases too?

Alternatively, could we deprecate/remove this field, or is that detrimental?

2023-04-12 21:21 UTC, codingllama commented on lib/client/cluster_client.go
> +	case proto.MFARequired_MFA_REQUIRED_YES:
Suggestion:

```suggestion
	case proto.MFARequired_MFA_REQUIRED_YES:
		// Proceed and prompt for MFA below.
```

2023-04-12 21:21 UTC, codingllama commented on integration/integration_test.go
> +	addr map[string]struct{}
Rename to plural and document key?

```suggestion
	addrs map[string]struct{} // key is the string representation of a net.Addr, eg: "localhost:8080"
```

(Correct it wrong, ofc.)

2023-04-12 21:21 UTC, codingllama commented on integration/integration_test.go
>  type localAddr struct {
Should we rename the type to `localAddrs`? Should we instead be using multiple `localAddr` instances, or keeping a map of them elsewhere?

The fact that it holds multiple addresses is not something I'd expect from the present type name.

```suggestion
type localAddrs struct {
```

2023-04-12 21:21 UTC, codingllama commented on integration/integration_test.go
> +				local.add(conn.LocalAddr())
I don't follow what the changes here have to do with the rest of the PR.

(It looks OK by itself, I just missing how it fits.)

2023-04-12 21:22 UTC, codingllama commented
Looks good, nice to see this one out for review.

2023-04-13 17:32 UTC, Joerger approved these changes

2023-04-14 14:51 UTC, ryanclark approved these changes

2023-04-14 15:04 UTC, codingllama approved these changes

2023-04-14 15:04 UTC, codingllama commented on tool/tsh/tsh_test.go
> +			mfaPromptCount:  0,
Suggestion:

```suggestion
```

2023-04-14 15:04 UTC, codingllama commented on lib/client/cluster_client.go
> +		if params.MFACheck != nil && !params.MFACheck.Required {
That's much clearer, thanks. I wish we had some of this background documented in the field itself.

2023-04-14 19:23 UTC, merged