Edit Homebrew installation instructions
gravitational/teleport pull request #24278
Opened 2023-04-07 16:34 UTC by ptgott

Closes #14848

- Remove the warning re: open source `tctl` from a scoped component, ensuring that users of all scopes can see the warning.

- Clean up the `Tabs` box to use a single two-dimensional `Tabs` component.

2023-04-07 16:42 UTC, zmb3 approved these changes

2023-04-07 18:03 UTC, alexfornuto requested changes

2023-04-07 18:03 UTC, alexfornuto commented on docs/pages/installation.mdx
This is rendering with both OSS and enterprise download instructions visible all the time. I'm not sure why.

![image](https://user-images.githubusercontent.com/2349184/230656009-198be947-5172-4f37-93a9-f5daabcc0ef3.png)

2023-04-18 16:46 UTC, ptgott commented on docs/pages/installation.mdx
This is the result of [this issue](https://github.com/gravitational/docs/issues/141), where if `TabItem`s have the same labels but different `options` values, these `TabItems` render at the same time for each dropdown option. I've pushed a fix!

2023-04-19 16:45 UTC, alexfornuto approved these changes

2023-04-19 17:35 UTC, merged