Restore MajorVersion template var for Installers
gravitational/teleport pull request #24388
Opened 2023-04-11 15:46 UTC by marcoandredinis

Fixes https://github.com/gravitational/teleport/issues/24378

2023-04-11 16:34 UTC, zmb3 approved these changes

2023-04-11 16:51 UTC, mdwn approved these changes

2023-04-11 17:27 UTC, r0mant requested changes

2023-04-11 17:29 UTC, r0mant requested changes

2023-04-11 17:29 UTC, r0mant commented on api/types/installers/agentless-installer.sh.tmpl
> +  fi
I don't think this change is actually needed? We only want to populate the MajorVersion template variable so users can use it in their own scripts, but we don't need to actually use it in our scripts?

2023-04-11 18:41 UTC, r0mant approved these changes
lgtm, let's just make sure it works and :shipit:

2023-04-12 10:37 UTC, lxea approved these changes

2023-04-12 11:02 UTC, merged