Shorter timeout for CreateSessionTracker
gravitational/teleport pull request #24942
Opened 2023-04-20 21:29 UTC by andreiko

This is a follow-up to https://github.com/gravitational/teleport/pull/18302
 
Additional testing showed that connecting to nodes during periods when auth service is down can hang for extra 20-40 seconds which is a bad experience.

The hanging is caused by ssh service trying to create a session tracker using Auth API. It gets better when the breaker trips and all Auth calls start failing immediately, but the delay becomes significant when the breaker starts letting requests through again.

2023-04-20 21:30 UTC, andreiko commented on lib/srv/sess.go
> +	timeoutCtx, timeoutCancel := context.WithTimeout(ctx, time.Second*5)
Couldn't find a suitable value in the `defaults` package or any configuration value accessible from here, hence the hardcoded timeout.

2023-04-20 22:36 UTC, zmb3 approved these changes

2023-04-21 20:11 UTC, rosstimothy requested changes
IIRC we agreed in the scale meeting that to fix this we should move the creation of the session tracker into a goroutine if and only if the session is not moderated instead of lowering any timeouts. @fspmarshall @espadolini is that correct?

2023-04-24 22:45 UTC, andreiko commented
Yeah, we were discussing multiple options, it's possible that I remembered wrong which one we chose.

I implemented async session tracker initialization such that, if the session is not moderated, `trackSession()` returns immediately and tracker is supposed to be accessed via `getTracker()` which blocks until initialization is complete.

This works perfectly for command execution, but interactive sessions won't start until some tracker is available. In my current version, when auth is down, it blocks [addParty() here](https://github.com/gravitational/teleport/blob/00a0f660c63675938c0f9fbf9786e2f2583db45e/lib/srv/sess.go#L1551) for 30 seconds which often leads to the "timed out waiting for continue signal" error and failure.

Maybe I'm missing something? When you suggested to create session tracker in a goroutine, did you have some different synchronization mechanism in mind?

2023-04-25 17:11 UTC, andreiko commented
> If we were to fix #17027 would that resolve the issues you are seeing when blocking in `addParty`?

Yeah, it looks like it would!

2023-04-25 18:16 UTC, andreiko commented
Closing for now.

2023-04-25 18:16 UTC, closed without merging