tctl: ensure that lock targets are valid UUIDs
gravitational/teleport pull request #24998
Opened 2023-04-21 17:56 UTC by zmb3

The help message mentioned when UUIDs were required, but nothing enforced this.

Add a custom parser that validates the provided flags are proper UUIDs.

Updates gravitational/teleport-private#556

2023-04-21 17:57 UTC, jentfoo approved these changes

2023-04-21 19:39 UTC, espadolini requested changes
It's legitimate for a Teleport node to have a host ID that's not a valid UUID, but instead matches `utils.IsEC2NodeID`, so this change would prevent adding a lock on one of those.

Have you doublechecked that we enforce that there's no way to have a non-UUID trusted device, access request or MFA device? It wouldn't be great to be prevented from locking something specifically because of this.

2023-04-21 20:26 UTC, zmb3 commented
@espadolini good catch. We could go with my original idea instead - add a `--force` flag, and require the user to specify `--force` if the node ID does not look like a UUID (showing a nice warning and erroring out if the flag is not present).

2023-09-26 19:24 UTC, zmb3 commented
Abandoning this one, though I was particularly fond of `UUIDVar`.

2023-09-26 19:24 UTC, closed without merging