Added support for directory mode to scp.
gravitational/teleport pull request #2537
Opened 2019-01-30 22:38 UTC by russjones

**Purpose**

Added support for directory mode to scp. This is to prevent a bug where the remote target file was clobbered when multiple source files were specified.

**Implementation**

* On the client side, make sure directory mode is requested when sending multiple files.
* On the server side, when in directory mode, validate that the target is a directory.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/2094

2019-01-30 22:46 UTC, russjones commented
@gravitational-jenkins retest this please

2019-02-11 03:29 UTC, klizhentas requested changes

2019-02-11 03:29 UTC, klizhentas commented on lib/sshutils/scp/scp.go
> +			return trace.BadParameter("invalid number of targets")
improve error message, what is the valid number? what targets were given, how user can fix the error

2019-02-11 03:29 UTC, klizhentas commented on lib/sshutils/scp/scp.go
> +			return trace.BadParameter("not a directory")
improve error message, what is not a directory? how client can fix the error?

2019-02-12 00:05 UTC, merged