Add Prometheus monitoring to the Audit Log.
gravitational/teleport pull request #2563
Opened 2019-02-13 23:33 UTC by russjones

**Description**

Add a Prometheus gauge which can be used to monitor how much disk space
is used and a Prometheus counter which can be used to count the number
of events that failed to emit to the Audit Log.

**Related Issues**

Fixes https://github.com/gravitational/teleport.e/issues/103

2019-02-20 01:12 UTC, russjones commented
@gravitational-jenkins retest this please

2019-02-21 20:36 UTC, klizhentas requested changes

2019-02-21 20:36 UTC, klizhentas commented on lib/service/service.go
> +		go startDiskMonitor(process)
there is no need to run this is as a `go` gourotines, as `RegisterFunc` does that for you

2019-02-27 16:54 UTC, klizhentas approved these changes

2019-03-08 19:21 UTC, merged