Moved expires to resource metadata for services.Users.
gravitational/teleport pull request #2564
Opened 2019-02-13 23:33 UTC by russjones

**Description**

Moved expiry field from spec to metadata for services.Users and updated
expiry check to prefer metadata and fallback to spec if not found. Added
test coverage.

2019-02-13 23:41 UTC, r0mant approved these changes

2019-02-13 23:41 UTC, r0mant commented on lib/services/suite/suite.go
> +var _ = fmt.Printf
Need this?

2019-02-13 23:41 UTC, r0mant commented on lib/auth/saml_test.go
> +var _ = fmt.Printf
Need this?

2019-02-14 17:11 UTC, klizhentas commented
I think this problem applies to all users, not just github ones

2019-02-14 17:11 UTC, klizhentas requested changes
Can you please check that if this problem applies to all external types

2019-02-14 18:18 UTC, russjones commented
@klizhentas It does and I fixed it for all external identity providers. I've fixed it for all and covered all with tests. That's what the bulk of the PR was.

2019-02-14 19:33 UTC, russjones commented
@gravitational-jenkins retest this please

2019-02-14 22:07 UTC, klizhentas commented
k, sorry the PR only showed me two github files, let me re-review

2019-02-18 19:28 UTC, klizhentas approved these changes

2019-02-18 19:29 UTC, klizhentas commented
retest this please

2019-02-19 02:00 UTC, klizhentas commented on lib/auth/github.go
> +// createUserParams is a set of parameters used to create a user for an\
extra `\`?

2019-02-19 02:06 UTC, klizhentas requested changes
still have a couple of comments and one actual change

2019-02-19 02:06 UTC, klizhentas commented on lib/auth/github.go
> +	var p createUserParams
why not:

```go
p := createUserParams{
     connectorName: connector.GetName(),
     username: claims.Username,
}
```

2019-02-19 02:06 UTC, klizhentas commented on lib/auth/github.go
> +	roleTTL := roles.AdjustSessionTTL(defaults.CertDuration)
should be Max duration, not default cert duration, so we can process larger than default values

2019-02-19 02:06 UTC, klizhentas commented on lib/auth/oidc.go
> +	var p createUserParams
ditto as other user

2019-02-19 02:06 UTC, klizhentas commented on lib/auth/saml.go
> +	var p createUserParams
ditto

2019-02-19 02:25 UTC, klizhentas approved these changes

2019-02-19 02:30 UTC, merged