[v12] use stable/cloud repo for cloud tenants
gravitational/teleport pull request #26845
Opened 2023-05-24 16:28 UTC by marcoandredinis

Backport of https://github.com/gravitational/teleport/pull/26656

2023-05-24 16:30 UTC, stevenGravy approved these changes

2023-05-24 16:36 UTC, r0mant reviewed
Do we want this in 12 though?

2023-05-24 16:40 UTC, marcoandredinis commented
> Do we want this in 12 though?

The apt repo shows a v12 version:
https://apt.releases.teleport.dev/ubuntu/dists/bionic/stable/cloud/binary-amd64/Packages

Using this channel ensures that manual upgrades will install newer versions (even major ones)

Should we not backport it?

2023-05-26 15:48 UTC, r0mant approved these changes

2023-05-26 15:49 UTC, r0mant requested changes
Actually, I don't think we can do it for v12. Because we already have a v13 release in that channel as well and someone might upgrade accidentally ahead of time.

2023-05-26 15:51 UTC, closed without merging