Update preference order for tunnel address.
gravitational/teleport pull request #2695
Opened 2019-05-03 00:41 UTC by russjones

**Description**

Return the tunnel address in the following preference order:

1. Reverse Tunnel Public Address.
2. SSH Proxy Public Address.
3. HTTP Proxy Public Address.
4. Tunnel Listen Address.

2019-05-03 01:05 UTC, russjones commented
@gravitational-jenkins retest this please

2019-05-03 01:09 UTC, klizhentas requested changes

2019-05-03 01:09 UTC, klizhentas commented on lib/service/connect.go
> +				return resp.Proxy.SSH.SSHPublicAddr, nil
in this case, the port should be still updated to the listen port, not the SSH port, so utils.Host(SSHPublicAddr) + ":"+utils.Port(TunnelListenAddr) or default port

2019-05-07 18:08 UTC, klizhentas approved these changes

2019-05-07 20:17 UTC, merged