[v11] use proxy port in openssh config
gravitational/teleport pull request #27547
Opened 2023-06-07 14:50 UTC by stevenGravy

Backport #27536 and #27591 to branch/v11

2023-06-07 17:07 UTC, mdwn approved these changes

2023-06-07 18:34 UTC, Joerger requested changes
This fails with the `TestWriteSSHConfig` test - not caught by CI due to https://github.com/gravitational/teleport/pull/27579

2023-06-07 18:38 UTC, Joerger approved these changes

2023-06-08 00:14 UTC, zmb3 approved these changes

2023-06-08 00:31 UTC, merged