[v12] feat: adds motd to the ui
gravitational/teleport pull request #27923
Opened 2023-06-16 03:49 UTC by sshahcodes

Backport #27813 to branch/v12

2023-06-16 11:02 UTC, ryanclark approved these changes

2023-06-16 15:53 UTC, kimlisa approved these changes

2023-06-16 16:33 UTC, zmb3 requested changes
https://github.com/gravitational/teleport/pull/27922#issuecomment-1594955385

2023-06-22 15:21 UTC, zmb3 approved these changes

2023-06-22 15:59 UTC, merged