[v13] feat: adds motd to the ui
gravitational/teleport pull request #27922
Opened 2023-06-16 03:49 UTC by sshahcodes

Backport #27813 to branch/v13

2023-06-16 11:02 UTC, ryanclark approved these changes

2023-06-16 15:53 UTC, kimlisa approved these changes

2023-06-16 16:32 UTC, zmb3 commented
Noticed one small issue. We're not properly respecting whitespace and multiline MOTD.

<img width="1610" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/4f9a742b-5587-463a-87a9-064f1e211d04">

Let's hold off on backports until we fix this.

2023-06-16 16:33 UTC, zmb3 requested changes
Let's fix multiline MOTD before merging.

2023-06-22 15:20 UTC, zmb3 approved these changes
We can release this and add multiline support in a follow up.

2023-06-22 15:41 UTC, merged