[v13] Allow setting max_session_ttl from clusterauth preferences
gravitational/teleport pull request #28130
Opened 2023-06-22 09:49 UTC by lxea

backport https://github.com/gravitational/teleport/pull/26824 and https://github.com/gravitational/teleport/pull/28138

2023-06-22 14:44 UTC, r0mant approved these changes

2023-06-22 15:05 UTC, zmb3 commented
There was a bug in the original PR, right? Should we avoid backporting this on its own and include the other fix in here too?

2023-06-23 14:43 UTC, ravicious requested changes
Preemptively blocking the merge in case https://github.com/gravitational/teleport/pull/26824#issuecomment-1604383616 turns out to be a bug.

2023-06-26 13:47 UTC, ravicious approved these changes

2023-06-26 17:32 UTC, espadolini approved these changes

2023-06-27 10:00 UTC, merged