Added 06/22 Upcoming Releases
gravitational/teleport pull request #28155
Opened 2023-06-22 16:46 UTC by russjones

2023-06-22 17:16 UTC, zmb3 approved these changes

2023-06-23 17:14 UTC, alexfornuto requested changes, later dismissed

2023-06-23 17:14 UTC, alexfornuto commented on docs/pages/upcoming-releases.mdx
> +TODO(r0mant): Fill out.
Looks like this was missed?

2023-06-23 20:24 UTC, r0mant approved these changes

2023-06-23 20:54 UTC, merged