[v12] Allow setting max_session_ttl from clusterauth preferences #28130
gravitational/teleport pull request #28185
Opened 2023-06-23 09:15 UTC by lxea

backport https://github.com/gravitational/teleport/pull/26824 and https://github.com/gravitational/teleport/pull/28138

2023-06-23 14:43 UTC, ravicious requested changes
Preemptively blocking the merge in case https://github.com/gravitational/teleport/pull/26824#issuecomment-1604383616 turns out to be a bug.

2023-06-26 13:46 UTC, ravicious approved these changes

2023-06-26 17:32 UTC, espadolini approved these changes

2023-06-27 22:15 UTC, ptgott approved these changes

2023-06-28 09:11 UTC, merged