docs: add server reference section
gravitational/teleport pull request #28655
Opened 2023-07-05 01:34 UTC by stevenGravy

- adds reference section for server including
    - cli
    - audit
    - sessions
    - config

2023-07-05 01:54 UTC, zmb3 requested changes

2023-07-05 01:54 UTC, zmb3 commented on docs/pages/includes/disable-recording-cluster.mdx
> +Session recording is enabled by default, and can be disabled in one of two ways:
This no longer reads correctly. This text is specific to desktop recordings. I would revert.

2023-07-05 15:43 UTC, zmb3 reviewed
This still feels like too big a change with overuse of includes.

I would prefer to break this up into a series of smaller less controversial changes.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/desktop-access/reference/sessions.mdx
> +recording SSH and Kubernetes sessions as well as desktop sessions.
This is awkward - we say _all types of recordings_ and then we mention 3 specifically. What about app or DB recordings?

Personally, I would have left this as-is.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/includes/disable-recording-cluster.mdx
> +Session recording is enabled by default, and can be disabled in one of two ways:
This still seems incorrect.

We say _can be disabled in one of two ways_ and then we list only one (not two) ways.

Disabling via RBAC is only supported for desktop, so I don't think we should use an include here.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/includes/reference/cli/tsh-ls.mdx
> +# grav-02   10.156.0.7:3022    os:osx
```suggestion
# Only show nodes with os label set to 'mac':
$ tsh ls os=mac

# Node Name Address            Labels
# --------- ------------------ ------
# grav-02   10.156.0.7:3022    os:mac
```

OS X is legacy terminology, let's avoid it.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/server-access/reference/audit.mdx
> +Emitted when a session is updated.
What does it mean for a session to be updated?

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/server-access/reference/cli.mdx
> +(!docs/pages/includes/reference/cli/tsh-play.mdx!)
I think we're overusing includes here. This makes it very hard to ensure that the page has a reasonable flow and transitions nicely from one section to the next.

I would use includes for smaller snippets that make sense to be reused in different places, not to write entire docs pages.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/server-access/reference/sessions.mdx
> +the session.
An audit event is emitted when a recorded session is accessed.

2023-07-05 15:43 UTC, zmb3 commented on docs/pages/server-access/reference/sessions.mdx
> +<Admonition type="tip" title="Listing recordings">
Feels odd for an admonition to be the last thing on the page.

2023-09-29 10:26 UTC, closed without merging

2023-09-29 10:26 UTC, stevenGravy commented
Closing to add with smaller changes