Update host-user-creation.mdx
gravitational/teleport pull request #29017
Opened 2023-07-12 17:57 UTC by programmerq

Added more info about what Teleport cleans up when temporary host users are supposed to be dropped.

2023-07-13 21:31 UTC, r0mant commented on docs/pages/server-access/guides/host-user-creation.mdx
> +specific pattern when it creates and deletes these sudoers entries.
Nit: The last sentence seems a bit vague and irrelevant.
```suggestion
it also removes any sudoers entries that were made for them.
```

2023-07-13 21:31 UTC, r0mant commented on docs/pages/server-access/rbac.mdx
> +    # Options specific to users create by Teleport via the create_host_user role option
`create_host_user` is obsolete. The new option is `create_host_user_mode` that supports keeping the user instead of deleting it.

2023-07-14 13:14 UTC, ptgott commented
@programmerq Are we backporting this one?

2023-07-14 13:29 UTC, programmerq commented
> @programmerq Are we backporting this one?

Backporting it would be good. Do I need to add labels to indicate that?

2023-07-14 13:56 UTC, ptgott commented
@programmerq Yep! Our CI bot creates backport branches based on the labels. I've added some—feel free to remove any that are inappropriate.

2023-07-18 22:16 UTC, zmb3 approved these changes

2023-07-25 15:31 UTC, alexfornuto commented on docs/pages/server-access/guides/host-user-creation.mdx
> +it also removes any sudoers entries that were made for them.
Suggest referencing sudoers entry removal in the preceding paragraph along with the home directory, and making this paragraph just about the delay for running processes. The idea behind this suggestion is to group like ideas with like; we talk about everything the cleanup does in one place, then talk about reasons for cleanup delay.

2023-07-25 15:31 UTC, alexfornuto commented on docs/pages/server-access/rbac.mdx
> +    # Options specific to users create by Teleport via the create_host_user_mode role option
```suggestion
    # Options specific to users created by Teleport via the create_host_user_mode role option
```

2023-07-26 23:59 UTC, r0mant approved these changes

2023-07-26 23:59 UTC, r0mant commented on docs/pages/server-access/rbac.mdx
> +    # List of sudoers entries that the created user will be added to. Only applies to create_host_user
```suggestion
    # List of sudoers entries that the created user will be added to. Only applies to create_host_user_mode
```

2023-08-30 16:27 UTC, zmb3 requested changes
@programmerq this has sat so long that I believe it's no longer accurate (we now have modes that allow you keep the user rather than deleting it).

If you still feel the changes here are worth documenting, let's make the updates and have it re-reviewed.

I'll label this as inactive and if I don't see any updates by the end of next week I'll assumed it's been abandoned and close it.

2023-09-21 17:47 UTC, zmb3 commented
Closed due to inactivity.

2023-09-21 17:47 UTC, closed without merging