Release 13.2.3
gravitational/teleport pull request #29308
Opened 2023-07-19 12:18 UTC by tcsc

Release 13.2.3

2023-07-19 12:58 UTC, hugoShaka approved these changes

2023-07-19 14:51 UTC, jakule approved these changes

2023-07-19 15:29 UTC, r0mant approved these changes

2023-07-19 15:32 UTC, r0mant requested changes

2023-07-19 15:32 UTC, r0mant commented on CHANGELOG.md
> +  * Fix proxy protocol support for Kube access flow [#29274](https://github.com/gravitational/teleport/pull/29274)
@tcsc PR titles as-is are most of the time not suitable for the changelog, and formatted all over the place. I usually try to skim through the PR description and rephrase the PR title so readers understand what is being fixed or implemented. For example, `AWS DBs Heartbeat: return IAM status (#28952)` is not a great title to get as-is.

Also things like internal product metrics are not relevant to users so I exclude things like that as well.

2023-07-20 03:11 UTC, r0mant approved these changes
@tcsc I've approved the PR so my review is not blocking you once you've fixed the changelog.

2023-07-20 04:22 UTC, merged