[v11] [Docs] Test and edit How to contribute to documentation topic
gravitational/teleport pull request #29649
Opened 2023-07-26 18:57 UTC by lsgunn-teleport

Backport https://github.com/gravitational/teleport/pull/28724 to branch/v11

2023-07-26 20:28 UTC, ptgott requested changes
There are merge conflicts in `how-to-contribute.mdx` that we'll want to fix!

2023-07-26 21:57 UTC, lsgunn-teleport commented
Oh man, I though I fixed them. Dang!

2023-07-26 22:07 UTC, ptgott approved these changes

2023-07-27 14:13 UTC, zmb3 approved these changes

2023-07-27 18:06 UTC, merged