Adds docs for keep-alive #2334
gravitational/teleport pull request #2976
Opened 2019-09-11 19:36 UTC by benarent

Adds the defaults and keep alive settings into admin-guide teleport.yaml.

2019-09-11 20:39 UTC, klizhentas requested changes

2019-09-11 20:39 UTC, klizhentas commented on docs/3.2/admin-guide.md
> +    # of messed keep-alive messages before the server tears down the connection to the
`messed` -> `missed`

2019-09-11 20:39 UTC, klizhentas commented on docs/3.2/admin-guide.md
> +    # client. The default value mirrors sshd at 3
Remove `he default value mirrors sshd at 3`

2019-09-11 20:53 UTC, webvictim commented
(same changes to both files)

2019-09-18 16:30 UTC, klizhentas commented
@benarent ping

2019-09-18 16:46 UTC, benarent commented
Thanks for the ping @klizhentas PTAL

2019-09-20 15:53 UTC, merged