Update teleport.yaml, copied from docs
gravitational/teleport pull request #3034
Opened 2019-09-30 22:58 UTC by eldios

Update teleport.yaml, copied from docs version which includes newer settings

2019-10-01 21:58 UTC, benarent requested changes
Thanks for the PR @eldios ,  Should we also bump https://github.com/gravitational/teleport/blob/master/build.assets/pkg/init-scripts/systemd/system/teleport.service to match our current SystemD setup.

2019-10-04 19:56 UTC, webvictim commented
ok to test

2019-10-15 18:53 UTC, benarent commented
@eldios Could you please add in the updated SystemD module with this PR please.

2019-10-18 01:33 UTC, benarent approved these changes

2019-10-18 01:44 UTC, merged