docs: add prompt field definition for OIDC auth connector
gravitational/teleport pull request #30414
Opened 2023-08-14 00:13 UTC by stevenGravy

The `prompt` field was not defined as a option.

2023-08-14 16:03 UTC, ptgott requested changes

2023-08-25 17:07 UTC, stevenGravy commented on docs/pages/access-controls/sso/oidc.mdx
> +default.
@ptgott please see update that includes value definitions.

2023-08-30 22:20 UTC, ptgott approved these changes

2023-08-31 15:44 UTC, zmb3 approved these changes

2023-08-31 16:03 UTC, merged