Define and add `IneligibleStatus` fields for access list members and owners
gravitational/teleport pull request #31857
Opened 2023-09-14 02:18 UTC by kimlisa

part of https://github.com/gravitational/teleport.e/issues/1899

For members ineligibility status is nonzero when:
- membership expired
- user does not exist
- user does not meet the `membership_requires` fields

For owners ineligibility status is nonzero when:
- user does not exist
- user does not meet the `ownership_requires` fields

2023-09-14 13:05 UTC, mdwn reviewed
I have no issue with the code per se.

I'm not sure how I feel about having this transient field as part of the underlying object -- I feel like this should be handled in the UI endpoint layer. As is this field could get stored in the backend, and it strikes me as a derivable field at run time.

What do you think?

Edit: I'm vacillating on this because, thinking more on it, there is prior art here, isn't there? @jakule, what do you think?

2023-09-18 20:55 UTC, kimlisa commented
friendly ping @mdwn @jakule

2023-09-18 22:23 UTC, jakule requested changes
As I mentioned in the comment, `INELIGIBLE_STATUS_UNKNOWN` should not be used as `eligible` status. Apart from that the PR looks good. I missed this the last time.

2023-09-19 14:17 UTC, mdwn approved these changes

2023-09-19 18:09 UTC, jakule approved these changes

2023-09-21 02:57 UTC, merged