Include node count in cluster info for UI (#2924)
gravitational/teleport pull request #3246
Opened 2020-01-07 00:17 UTC by fspmarshall

Addresses #2924 by adding a new `node_count` field as part of the cluster descriptions returned by `/v1/webapi/sites`.

Ex:

```json
{
  "current": {
    "name": "one",
    "last_connected": "2020-01-07T00:14:13.936035784Z",
    "status": "online",
    "node_count": 2
  },
  "trusted": [
    {
      "name": "two",
      "last_connected": "2020-01-07T00:13:42.35797554Z",
      "status": "online",
      "node_count": 3
    }
  ]
}
```

#### Potential Performance Issue:

As implemented, every leaf cluster must have `GetNodes` called against it every time the endpoint is hit.  Assuming a large number of nodes and a large number of concurrent web sessions, this could lead to a pretty sizable overhead for such a simple task.

Possible fixes:
**A**: Cache node counts at the API server for a few seconds.
**B**: Expose an API for getting node count directly on from each cluster rather than getting all node resources and then counting them.
**C**: All of the above.

I'm leaning towards **A** since it introduces only local complexity.  **B** and **C** are better in theory, but they add more complexity to the API surface and also have implications for cross-cluster version compatibility.

2020-01-08 00:28 UTC, benarent commented
I would suggest that we start to move new features for trusting/trusted to root/leaf terminology.

2020-01-08 02:46 UTC, fspmarshall commented
> I would suggest that we start to move new features for `trusting/trusted` to `root/leaf` terminology.

Agreed.  Unfortunately, in this case, the `trusted` field is an existing part of the API; this PR only adds the `node_count` subfield.

2020-01-08 18:26 UTC, benarent commented
Thanks for the clarification fspmarshall

2020-01-22 18:45 UTC, benarent commented
While sorting out other tickets, would it be possible to add Teleport Version number to this PR?  https://github.com/gravitational/teleport/issues/2925

2020-03-18 02:12 UTC, alex-kovoy requested changes
This will be taken care by https://github.com/gravitational/teleport/issues/2924. Thus I suggest to close this PR.

2020-03-18 16:39 UTC, benarent commented
Per @alex-kovoy comment, I'm going to close this PR as #_2924 will build upon this and add more information .

2020-03-18 16:39 UTC, closed without merging