Enable FIPS mode at the OS level for AWS AMIs
gravitational/teleport pull request #32625
Opened 2023-09-27 05:20 UTC by reedloden

While Teleport uses Go in FIPS mode (via boringcrypto), the underlying OS was not configured to use its own FIPS mode.

AL2: https://aws.amazon.com/blogs/publicsector/enabling-fips-mode-amazon-linux-2/
AL2023: https://docs.aws.amazon.com/linux/al2023/ug/fips-mode.html

2023-09-27 14:38 UTC, zmb3 commented
This seems like a risky change to land in a patch release.

2023-09-27 15:40 UTC, reedloden commented
> This seems like a risky change to land in a patch release.

I considered it both ways, but I feel like we are claiming these images are FIPS-compatible when they really aren't even close unless we actually enable FIPS mode at the OS level. At the least, could find some middle-ground with releasing this in a minor release (14.1, for instance) instead of a patch release and then moving forward with 15.x and later. Thoughts?

2023-09-27 15:55 UTC, zmb3 commented
14.1 is better than a patch, but I think we also need to cut a dev release with this change and do a bit of manual verification.

2023-10-03 19:32 UTC, wadells commented
Is there a related issue or users asking for this?  If not, I don't see much reason to take the risk before v15.

I agree that we we should build the AMI and give it a manual test.

2023-10-09 19:08 UTC, wadells requested changes
Needs testing before merge, as well as a decision about whether this is backported to anything before v15.

2023-10-31 21:09 UTC, zmb3 approved these changes
I'm fine landing this in master but we should spin up a cluster using this AMI once it lands and verify that everything works before backporting to a release branch.

2023-10-31 21:09 UTC, reedloden commented
> Needs testing before merge, as well as a decision about whether this is backported to anything before v15.

Green tag build here -- https://drone.platform.teleport.sh/gravitational/teleport/30214

Talked to @zmb3, and we just want to make sure this is fully tested before backporting. So, going to land in `master` but let it sit until enough smoke tests have been completed that we feel it's OK to backport.

2023-10-31 21:20 UTC, wadells approved these changes

2023-10-31 21:32 UTC, merged