Applies RBAC predicates to user resources
gravitational/teleport pull request #34056
Opened 2023-10-31 03:15 UTC by tcsc

This change aims to treat Teleport users like fully-fledged
resources in the RBAC system, specifically by allowing admins
to specifiy `where` clauses in Roles that apply to to the user
being created or modifies, as opposed to just the acive user
that is performing the operation.

| Operation      | `where` exptression `resource` value           |
| ---------------|------------------------------------------------|
| `CreateUser()` | The user to be created                         |
| `UpdateUser()` | The user to be modified                        |
| `DeleteUser()` | The user to be deleted                         |
| `UpsertUser()` | The user to be created (for the `Create` verb) |
|                | The user to be modified (for the `Update` verb |

Updating a user poses a potential security risk, given that our
RBAC predecate language currently has no way to reference an
"indirect object"; that is, in a `where` clause we cannot supply
both the value of a resource as it is and to the value it will
become after the update. To get around this, when updating a user,
the where clause *only* applies to the value in storage and NOT to
the value that the user will take after the update.

This leads to some inconsistencies - for example, it is possible
to create a user that meets the `Create` permissions, but then
immediately update it to a value that violates those `Create`
rules. I couldn't think of a way to prevent this that would also
not be too cumbersome to use in practice.

----
Changelog: Added RBAC role  `where` clause support for rules governing Users.

2023-10-31 03:37 UTC, r0mant requested changes
I'm not sure I fully understand why this is needed. The potentially infinite loops are especially scary.

If it's to address the concern with Okta service creating users, can't we just make sure that Okta service can only CRUD users with a specific "okta" label or something?

2023-10-31 04:10 UTC, tcsc commented
>  The potentially infinite loops are especially scary.

Agreed. I think I could make a case that just letting the race condition happen (i.e. somebody changes the target user underneath us after we have done the permissions check, and we let our user edit/delete a suddenly invalid record) is preferable to the potential DoS via infinite loops.

I am in no way wedded to that approach, and if there is a simpler/less scary option I'm happy to take it. 

> can't we just make sure that Okta service can only CRUD users with a specific "okta" label or something?

That's essentially what this is, only a general-purpose approach rather than specifically hacking special cases into `auth`.  I can definitely achieve the same thing (at least for Okta) by replacing the general `where`-clause evaluation with something like this (assuming that the `okta` policy has RW for users): 

```go
func (a *ServerWithRoles) UpdateUser(ctx context.Context, user types.User) (types.User, error) {
  if err := a.action(apidefaults.Namespace, types.KindUser, types.VerbUpdate); err != nil {
    return nil, trace.Wrap(err)
  }

  if a.hasBuiltinRole(types.RoleOkta) {
    targetUser, err := a.authServer.GetUser(ctx, user.GetName(), false)
    if err { ... }
    if targetUser.GetMetadata().Labels["origin"] != "okta" {
        return nil, trace.AccessDenied("...")
    }
  }

  updated, err := a.authServer.UpdateUser(ctx, user)
  return updated, trace.Wrap(err)
}
```
... in the user admin functions. It is still susceptible to the same race conditions as the original, though.

This PR was about seeing if 

1. having a more general solution, and
2. being able to consolidate all of the Okta service's access rules in one place (i.e. in the `okta` Role itself, rather than scattered about `auth_with_roles.go` 

...was worthwhile.

2023-11-01 13:37 UTC, greedy52 commented
> I think I could make a case that just letting the race condition happen (i.e. somebody changes the target user underneath us after we have done the permissions check, and we let our user edit/delete a suddenly invalid record) is preferable to the potential DoS via infinite loops.

My 2cent on this. Since the race is rare, if we really want `CompareAndSwap`, then just do it once and return the error if compare fails. 

Though we kinda of ignoring this race in other places
https://github.com/gravitational/teleport/blob/f4ad442ba23350166f064e020300c7ae22570ec7/lib/auth/auth_with_roles.go#L6036-L6047

Maybe @jentfoo can evaluate these ⬆️

2023-11-01 16:16 UTC, jentfoo commented
I think overall the goal of making sure a change is still allowed after detecting a concurrent change is a worthy one.

That said I agree with @greedy52 that on conflict the server should return an error without retry.  It's better to let the client decide how the retry should be done.  For example on an update we likely don't want to overwrite whatever change had occurred concurrently, so the client likely will want to retrieve the current state and re-apply the operation before requesting another update.

2023-11-01 16:48 UTC, greedy52 commented
> This will be the normal case for all updates of users once optimistic locking support for users lands in https://github.com/gravitational/teleport/pull/34045.

nice!

2023-11-02 00:56 UTC, tcsc commented
> That said I agree with @greedy52 that on conflict the server should return an error without retry. 

That sounds sensible to me, although I think doing that would require looking carefully at the existing calls to the user management functions and seeing what they will do in the face of a new error condition. 

My reasoning for adding the automatic retries was that the caller has already specified how long they are willing to wait in the supplied `Context`, so they were already somewhat in control of how many retries would be attempted.

Maybe it would be less scary the "until the context expires" condition more explicit? Something like...

```go
for ctx.Err() == nil {
  target, _ := a.authServer.GetUser(ctx, user.GetName(), false)

  sctx := &services.Context{User: a.context.User, Resource: target}
  if err := a.actionWithContext(sctx, apidefaults.Namespace, types.KindUser, types.VerbUpdate); err != nil {
    return nil, trace.Wrap(err)
  }

  err := a.authServer.CompareAndSwapUser(ctx, user, target)
  if trace.IsCompareFailed(err) {
    continue
  }
  return user, trace.Wrap(err)
}
return nil, ctx.Err()
```

2023-11-02 03:08 UTC, tcsc commented
For comparison I have updated the User CRUD actions in #33630 with special cases to deny the Okta role access for non-Okta users.

While I don't really like having special-cased behaviour for a single role, it has an unarguable smaller scope - which may be what we're after.

2023-11-02 14:55 UTC, r0mant commented
> For comparison I have updated the User CRUD actions in https://github.com/gravitational/teleport/pull/33630 with special cases to deny the Okta role access for non-Okta users.

@tcsc Yes, that is exactly what I meant. I would close this PR and go with that approach.

2023-11-02 16:02 UTC, greedy52 commented
BTW, with Ross' https://github.com/gravitational/teleport/pull/34045, you might need to update both auth_with_roles  and the new user service.

2023-11-21 23:06 UTC, tcsc commented
Closed in favour of #33630

2023-11-21 23:06 UTC, closed without merging