Add localStorage value for enabling TAG
gravitational/teleport pull request #34111
Opened 2023-11-01 10:38 UTC by ryanclark

This adds a new key into the local storage enum for enabling/disabling TAG from showing up in the navigation.

2023-11-01 16:12 UTC, jakule approved these changes

2023-11-09 23:22 UTC, jakule commented
@ryanclark Are we fine merging this PR?

2023-11-16 15:53 UTC, justinas requested changes
See review for usage of the main flag here https://github.com/gravitational/teleport.e/pull/2541#pullrequestreview-1734777827

Access to TAG UI is now controlled by RBAC / Features like all other items, so we need to remove the main flag, and only leave SQL behind the manually-set dev flag.

2023-11-16 17:37 UTC, justinas commented
> See review for usage of the main flag here [gravitational/teleport.e#2541 (review)](https://github.com/gravitational/teleport.e/pull/2541#pullrequestreview-1734777827)
> 
> Access to TAG UI is now controlled by RBAC / Features like all other items, so we need to remove the main flag, and only leave SQL behind the manually-set dev flag.

Disregard, we intentionally added the flag to **ship without the UI enabled at first** (just the backend pieces).

2023-11-17 11:52 UTC, justinas approved these changes

2023-11-17 15:00 UTC, merged