Remove cloud only warning for jira plugin
gravitational/teleport pull request #34153
Opened 2023-11-02 16:07 UTC by EdwardDowling

Must be merged after [2555](https://github.com/gravitational/teleport.e/pull/2555)

2023-11-02 16:28 UTC, r0mant approved these changes

2023-11-02 17:05 UTC, ptgott commented
Have you looked at the rendered docs site (on the preview site/dev server) to make sure this is what you want?

2023-11-03 14:49 UTC, zmb3 requested changes

2023-11-03 14:49 UTC, zmb3 commented on docs/pages/access-controls/access-request-plugins/ssh-approval-jira.mdx
>  </Details>
This is almost certainly incorrect. You know have a closing `</Details>` tag without an opening one.

2023-11-03 16:15 UTC, zmb3 approved these changes

2023-11-07 16:44 UTC, merged