[v14]  Log error when entity descriptor cant be fetched in saml
gravitational/teleport pull request #34994
Opened 2023-11-27 14:59 UTC by lxea

Backport #34896 to branch/v14

2023-11-27 15:00 UTC, mdwn approved these changes

2023-11-27 16:34 UTC, avatus approved these changes

2023-11-28 16:46 UTC, jentfoo requested changes
Discussing with @lxea in DM, but I think we want some additional changes before this is backported

2023-12-08 20:09 UTC, jentfoo commented
Replaced by PR #35576

2023-12-08 20:09 UTC, closed without merging