Update admin manual config file
gravitational/teleport pull request #3522
Opened 2020-04-06 19:00 UTC by aelkugia

In the configuration file under `authentication` we currently list `false` as a valid auth type which is not the case.

2020-04-06 19:14 UTC, benarent requested changes
To clarify, I think this was due to setting `local_auth` to false for FIPS mode.  Could you double check this file and it here for clarity. 

```
  # To Support FIPS local_auth needs to be turned off and a SSO connector is 
  # required to log into Teleport. 
  authentication:
    # local_auth needs to be set to false in FIPS mode. 
    local_auth: false
    type: saml
```

2020-04-07 12:45 UTC, webvictim commented
Yeah, this looks like a line has been truncated or deleted at some point.

2020-04-11 00:20 UTC, aelkugia commented
@benarent I've extended the comment to discuss setting `local_auth` to `false` for FIPS mode

2020-04-13 19:01 UTC, benarent approved these changes

2020-04-14 00:31 UTC, merged