Clarify teleport-event-handler config
gravitational/teleport pull request #35448
Opened 2023-12-06 22:04 UTC by WilliamLoy

Some users are using the example config before reading through the changes that need to be made to it. This PR moves the example config to come after the change instructions as well as adds examples for Splunk Enterprise vs. Splunk Cloud.

2023-12-06 22:50 UTC, ptgott requested changes

2024-01-02 22:14 UTC, WilliamLoy commented on docs/pages/includes/plugins/finish-event-handler-config.mdx
> +<TabItem label="Linux server - Splunk Enterprise">
@ptgott No I haven't. Do you have a guide for using it?

2024-01-02 22:17 UTC, ptgott commented on docs/pages/includes/plugins/finish-event-handler-config.mdx
> +<TabItem label="Linux server - Splunk Enterprise">
You can either:
- Use the preview link that our GHA workflows post to docs PRs (this isn't being posted to the current PR discussion, so I'm guessing you'll need to rebase this branch against `master` first)
- Follow the instructions here to review your changes on a local dev server: https://goteleport.com/docs/contributing/documentation/reviewing-docs/

2024-01-16 14:00 UTC, zmb3 commented
@WilliamLoy do you plan to clean this up or should we close it?

2024-01-24 02:08 UTC, closed without merging

2024-02-06 17:12 UTC, WilliamLoy commented
@ptgott were you able to get this converted to an issue?

2024-02-13 22:57 UTC, ptgott commented
@WilliamLoy I've opened an issue at #38184