Improved error message when node is offline.
gravitational/teleport pull request #3688
Opened 2020-05-08 23:59 UTC by russjones

**Description**

When connecting to a remote cluster, if the connection failed return node is offline or cluster is offline (instead of always cluster is offline) to return a better error to the caller.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/3458

2020-05-09 00:02 UTC, benarent approved these changes
👍

2020-05-11 12:59 UTC, webvictim requested changes
`IntSuite.TestTwoClustersTunnel` looks to be broken as a result of this.

2020-05-11 17:21 UTC, awly approved these changes
LGTM, except for @webvictim's comment

2020-05-15 14:28 UTC, webvictim approved these changes

2020-05-15 20:14 UTC, merged