Docs OpenSSH tsh instructions
gravitational/teleport pull request #3795
Opened 2020-06-02 20:53 UTC by stevenGravy

Provide guidance on connecting to a OpenSSh with TSH

2020-06-03 12:15 UTC, webvictim commented on docs/4.2/admin-guide.md
> + To connect to the OpenSSH server via `tsh` add the `--port=<ssh port>` with the `tsh ssh` command:
...via `tsh`, add `--port=<ssh port>` to the `tsh ssh` command:

(add comma, fix formatting)

2020-06-03 12:15 UTC, webvictim commented on docs/4.2/admin-guide.md
> +  + Example ssh to `database.work.example.com` as `root` with a OpenSSH server on port 22 via `tsh`
...via `tsh`:

(add colon)

2020-06-03 12:15 UTC, webvictim commented on docs/4.2/admin-guide.md
> +    The user being connected as must be available in the Teleport user configuration or role.
The principal (username) being used to connect must be listed in the Teleport user/role configuration.

(bit more readable, plus uses the term 'principal' which people could potentially Ctrl+F for if they're getting the "name is not a listed principal" error)

2020-06-18 15:35 UTC, benarent requested changes
Can you also add this into 4.3, if you update from master those documents are available now.

2020-06-25 18:12 UTC, closed without merging