[v14] Always verify the old password when changing it
gravitational/teleport pull request #39126
Opened 2024-03-08 15:56 UTC by bl-nero

Backport #38203 to branch/v14

changelog: Fixed an issue where it was possible to skip providing old password when setting a new one.

2024-03-08 16:20 UTC, jentfoo approved these changes

2024-03-08 16:36 UTC, codingllama approved these changes

2024-03-08 16:39 UTC, codingllama requested changes

2024-03-08 16:39 UTC, codingllama commented on lib/auth/password_test.go
> +		ChallengeExtensions: &mfav1.ChallengeExtensions{
There's no mfav1 in this branch, so we'll have to change this.

2024-03-12 14:27 UTC, codingllama approved these changes

2024-03-12 15:54 UTC, zmb3 approved these changes

2024-03-12 16:58 UTC, merged