Wolfe/ui fixes
gravitational/teleport pull request #3959
Opened 2020-07-01 18:09 UTC by alexwolfe

2020-07-01 22:58 UTC, benarent commented
![image](https://user-images.githubusercontent.com/559288/86298844-a3ceca80-bbb3-11ea-952c-e0f3e9b44f94.png)

Docs looks great.

I would be good to provide a nested nav, in the sidebar and breadcrumbs, but we can come back to that in the future

2020-07-01 22:59 UTC, benarent commented on docs/4.3.yaml
> +        #    - Teleport Slack Plugin Setup: enterprise/workflow/ssh_approval_slack.md
Commented these out, we can add nestested nav back in the future.

2020-07-01 23:00 UTC, benarent approved these changes

2020-07-02 16:59 UTC, webvictim commented
`milv` is complaining: https://drone.gravitational.io/gravitational/teleport/320/2/2

2020-07-02 17:00 UTC, webvictim requested changes
Please fix `milv` complaints before we merge: https://drone.gravitational.io/gravitational/teleport/320/2/2

2020-07-02 20:38 UTC, merged