Workflow Documentation Fixes
gravitational/teleport pull request #4111
Opened 2020-07-23 22:11 UTC by travelton

Various documentation and example fixes for workflow approval.

1. Fixes typo in generating example Slack toml.
2. Adds hint in example Slack toml for Slack oAuth token.
3. Removes `--pid-file` from example systemd units, as this flag is not valid.

2020-07-23 22:44 UTC, webvictim approved these changes
@travelton In future, could you please create your own branches against `gravitational/teleport` rather than using a fork? Drone doesn't (currently) run on PRs from forks, but it runs the `docs` tests which would be relevant here.

2020-07-23 23:27 UTC, benarent requested changes

2020-07-23 23:27 UTC, benarent commented on docs/4.3/enterprise/workflow/ssh_approval_slack.md
> +$ teleport-slack configure > teleport-slackbot.toml
Make this `teleport-slack.toml`

We dropped bot from the plugins. 
```
[ec2-user@ip-172-31-14-137 teleport-access-slack]$ sudo ./install
Teleport Slack binaries have been copied to /usr/local/bin
You can run teleport-slack configure > /etc/teleport-slack.toml to bootstrap your config file
```

2020-07-24 15:12 UTC, benarent approved these changes

2020-07-24 15:12 UTC, benarent approved these changes

2020-07-24 15:18 UTC, merged