Fix milv failing test
gravitational/teleport pull request #4251
Opened 2020-08-21 23:51 UTC by benarent

Fixed the one nagging milv issue and stopped external checks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190029021439585/1190182393542976) by [Unito](https://www.unito.io/learn-more)

2020-08-22 20:22 UTC, webvictim requested changes
We should still be checking external links. Are we just turning it off because it’s a bit flaky? This seems like a bad solution. The external link checker caught that problem with the BCC instructions for Ubuntu just a few weeks ago - we’d never have known otherwise.

Maybe a better alternative would be to split the test-docs step into two separate checks - one internal-only and one external-only. This wouldn’t be tough to do and we could still run the checks in parallel, so we’d hopefully know whether it was something we did or not.

2020-08-24 18:32 UTC, kontsevoy commented
My suggestion was to keep the external link-checking as a build process UNTIL we migrate to external site crawler/monitor which will continuously check those not just for docs, but for ALL our web properties.

2020-08-25 00:12 UTC, benarent commented
retest this please

2020-08-26 11:39 UTC, webvictim approved these changes

2020-08-26 11:39 UTC, merged