ssh as tsh ssh alias
gravitational/teleport pull request #4288
Opened 2020-09-02 18:11 UTC by quinqu

Fixed #3728

2020-09-02 21:08 UTC, webvictim commented
I think that `tsh` is supposed to detect if it's called using the name `ssh` and modify its behaviour to automatically run `tsh ssh` in these instances. Does it work that way for you?

How about if you rename the binary (so `mv tsh ssh` or similar) - does it do that then?

2020-09-03 18:04 UTC, quinqu commented
I think folks are confused by this line in the user manual, because they don't know that `ssh` is being appended to the command, I updated the description so it's less confusing. 

> alias ssh="tsh ssh" then you can continue using familiar SSH syntax

2020-09-03 19:21 UTC, webvictim commented
Leaving this one for @benarent

2020-09-09 21:45 UTC, benarent commented on docs/4.3/user-manual.md
> +the following alias defined in your ~/.bashrc: `alias ssh="tsh"` then you
```suggestion
the following alias defined in your ~/.bashrc: `alias ssh="tsh ssh"` then you
```

2020-09-09 21:45 UTC, benarent commented on docs/4.3/user-manual.md
> +$ alias ssh="/usr/local/bin/tsh"
```suggestion
$ alias ssh="/usr/local/bin/tsh ssh"
```

2020-09-09 21:46 UTC, benarent requested changes
Based on the example and the initial issue, let's keep it to alias ssh to `tsh ssh` as the rest of the example shows this flow. 

Feel free to just commit my suggestions.

2020-09-18 14:12 UTC, webvictim approved these changes

2020-09-18 14:13 UTC, webvictim commented
@benarent Let's get this closed/merged as appropriate.

2020-09-21 21:27 UTC, benarent approved these changes

2020-09-21 21:28 UTC, benarent commented
ok to test

2020-09-22 16:33 UTC, merged