Send cluster name as SNI when connecting to TAG
gravitational/teleport pull request #43780
Opened 2024-07-03 00:36 UTC by jakule

Include Teleport cluster name in the connection information when connecting to TAG event stream endpoint. TAG will use that information to manage open connections. Only EventStream endpoint need that information, so Proxy connection can still send empty server name as it does right now.

2024-07-08 14:41 UTC, marcoandredinis approved these changes

2024-07-08 18:56 UTC, tigrato requested changes

2024-07-08 18:56 UTC, tigrato commented on lib/service/discovery.go
> +const accessGraphClusterSNI = "access-graph.cluster."
Please don't use sni otherwise all certificates must be updated in cloud and customers. Use the next protos to send it

2024-08-22 14:23 UTC, closed without merging

2024-08-22 14:24 UTC, jakule commented
We decided to use a different approach so, we don't need this anymore.