[v16] Add context around AWS join methods
gravitational/teleport pull request #43820
Opened 2024-07-03 19:25 UTC by ptgott

Backport #43380 to branch/v16

2024-07-05 08:39 UTC, marcoandredinis approved these changes

2024-07-05 09:23 UTC, strideynet approved these changes

2024-07-09 17:43 UTC, nklaassen requested changes
My [comment](https://github.com/gravitational/teleport/pull/43380#discussion_r1649402083)s on the missing parens were not resolved 
<img width="269" alt="Screenshot 2024-07-09 at 10 42 17 AM" src="https://github.com/gravitational/teleport/assets/16807901/e8dda691-120a-4bfc-9182-87b76202d859">

2024-08-15 16:42 UTC, nklaassen approved these changes

2024-08-30 12:56 UTC, ptgott commented
@mmcallister Would you have time to give this one a look?

2024-08-30 21:09 UTC, mmcallister approved these changes

2024-08-30 21:33 UTC, merged