[branch/v16] Invoke signing function for Windows Connect binary
gravitational/teleport pull request #44419
Opened 2024-07-18 20:10 UTC by fheinecke

Backport #41963

2024-07-19 02:30 UTC, zmb3 commented on build.assets/windows/build.ps1
> +        --copyright "Copyright (C) $Year Gravitational, Inc." `
Best to run a tag build and then right click and go to properties on `tsh.exe` in a Windows environment. This version metadata is very picky and I seem to recall something about the comma breaking things.

2024-07-19 02:31 UTC, zmb3 commented on build.assets/windows/build.ps1
> -    & $GoWinres simply --no-suffix --arch amd64 --admin `
Why was this removed?! This is necessary in order for the installer to properly request admin permissions.

2024-07-19 02:32 UTC, zmb3 requested changes
I'm not convinced this doesn't break things, can we verify the version metadata is correct before merging this?

2024-07-19 17:19 UTC, fheinecke commented
@zmb3 I screwed up my local backport commands and this should now be fixed, with a significantly smaller set of changes.

2024-07-19 17:21 UTC, zmb3 commented
Looks better but I'm now confused how this fixes anything. All I can see is that `SignedBinaryPath` is no longer mandatory. Is that correct?

2024-07-19 17:22 UTC, fheinecke commented
Yep that's pretty much it. Somehow when I did several other backports I managed to include only part of the original PR and it's breaking things due to this attribute.

2024-07-19 17:23 UTC, fheinecke commented
Having `mandatory` set makes the field mandatory (as the name implies), and we're calling this commandlet in some places without this parameter now.

2024-07-19 17:23 UTC, zmb3 approved these changes

2024-07-22 08:11 UTC, gzdunek approved these changes

2024-07-22 08:22 UTC, merged