Add docs for RDP NLA
gravitational/teleport pull request #45282
Opened 2024-08-08 18:50 UTC by zmb3

Replaces #45099

2024-08-08 18:58 UTC, zmb3 commented on docs/pages/includes/config-reference/desktop-config.yaml
> +  kdc_addr: '$KDC_SERVER_ADDRESS'
This should read `kdc_address`, not addr. Will fix.

2024-08-09 13:39 UTC, ptgott approved these changes

2024-08-26 20:54 UTC, probakowski requested changes

2024-08-26 20:54 UTC, probakowski commented on docs/pages/enroll-resources/desktop-access/active-directory.mdx
> +- manually set the `teleport.dev/dns_host_name` label to the proper hostname
```suggestion
- manually set the `teleport.dev/computer_name` label to the proper hostname
```

2024-08-26 21:44 UTC, mmcallister approved these changes

2024-08-26 21:47 UTC, probakowski approved these changes

2024-08-26 21:53 UTC, mmcallister commented on docs/pages/enroll-resources/desktop-access/active-directory.mdx
> +`teleport.dev/computer_name` label which is automaticaly populated. If this
```suggestion
`teleport.dev/computer_name` label which is automatically populated. If this
```

2024-08-26 21:53 UTC, mmcallister commented on docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
> +- the server's computer name is specified in the `telepot.dev/computer_name` label
```suggestion
- the server's computer name is specified in the `teleport.dev/computer_name` label
```

2024-08-27 01:36 UTC, webvictim approved these changes

2024-08-27 12:31 UTC, webvictim commented on docs/pages/enroll-resources/desktop-access/troubleshooting.mdx
> +### CredSSP: server not found in Kerberos database
Do you think it's also worth adding `CredSSP enhanced RDP security required by server` as a header here, with instructions about setting the environment variable?

2024-08-27 16:02 UTC, merged