[v16] Adding extra pod labels to post-upgrade and post-delete hook job pods
gravitational/teleport pull request #46232
Opened 2024-09-04 14:52 UTC by mvbrock

Backport #46029 to branch/v16

changelog: Ensure that additional pod labels are carried over to post-upgrade and post-delete hook job pods when using the teleport-kube-agent Helm chart.

2024-09-04 14:53 UTC, tigrato approved these changes

2024-09-04 16:08 UTC, hugoShaka requested changes
Please don't merge those backports PR yet, this will break CI

2024-09-06 16:08 UTC, mvbrock commented
> Please don't merge those backports PR yet, this will break CI

@hugoShaka can you give a little more detail? Should I fix something before merging?

2024-09-06 16:40 UTC, hugoShaka commented
Sorry, I forgot to ping you, the fix passed, You can now rebase on branch/v16. The CI now enforces the chart documentation to be in sync with the chart values, it won't let the PR break the tests anymore.

After rebasing you might face a CI error asking to re-generate the docs, it will contain the command to do so.

2024-09-06 16:41 UTC, hugoShaka approved these changes

2024-09-06 17:33 UTC, merged