[web] update device type for enrolled/not enrolled
gravitational/teleport pull request #48727
Opened 2024-11-09 13:07 UTC by stevenGravy

The device status is lower case.

2024-11-09 14:12 UTC, avatus approved these changes

2024-11-09 14:17 UTC, avatus requested changes
https://github.com/gravitational/teleport/pull/48474/files

Why move back to lower case?

2024-11-09 14:19 UTC, stevenGravy commented
> https://github.com/gravitational/teleport/pull/48474/files
> 
> Why move back to lower case?

The status from device list is `enrolled` and `not enrolled`. If we want it upper case it would have to be changed in the display.

2024-11-09 14:23 UTC, avatus approved these changes

2024-11-09 14:23 UTC, avatus commented
Thanks for catching!

2024-11-11 11:25 UTC, marcoandredinis approved these changes

2024-11-11 11:37 UTC, merged