Add initial msteams hosted enroll docs
gravitational/teleport pull request #48756
Opened 2024-11-11 17:25 UTC by EdwardDowling

Part of #24495

Updates image showing hosted enrollment of plugins  and adds some more info about msteams  enrollment

2024-11-11 17:54 UTC, zmb3 commented on docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
> +(!docs/pages/includes/plugins/enroll.mdx name="the Mattermost integration"!)
Mattermost??

2024-11-11 19:34 UTC, r0mant requested changes
The snippet you inserted is referring to Mattermost, not MS Teams. Screenshot from your [rendered branch](https://docs-181v9f3cy-goteleport.vercel.app/docs/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams/):

<img width="1196" alt="Screenshot 2024-11-11 at 11 31 37 AM" src="https://github.com/user-attachments/assets/e62ed695-1607-4019-b145-4149d23451be">

Also, should we mark some steps in the guide as optional when using a hosted version of the integration?

2024-11-11 19:34 UTC, r0mant commented on docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
> +Once enrolled you can download the require 'app.zip' file from the integrations status page.
Download how? Should we insert a screenshot demonstrating it?
```suggestion
Once enrolled you can download the required `app.zip` file from the integrations status page.
```

2024-11-13 15:30 UTC, EdwardDowling commented on docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
> +Once enrolled you can download the required `app.zip` file from the integrations status page.
Sorry only noticed the suggested edit part of that comment. Have added in an example image of the download page

2024-11-14 16:47 UTC, EdwardDowling commented on docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
> +![Download app.zip](../../../../img/enterprise/plugins/msteams/app-zip.png)
Fixed the commit to include it.

2024-11-14 17:58 UTC, r0mant reviewed
@EdwardDowling Two more comments regarding screenshots, then should be lgtm.

2024-11-14 17:58 UTC, r0mant commented on docs/img/enterprise/plugins/enroll.png
I think it would actually make more sense to show the "Select Integration Type" page as it was before, and say pick MS Teams tile - enroll new integration doesn't make much sense to show here, and it also can look different depending on whether you already have another integration setup or not.

2024-11-14 17:58 UTC, r0mant commented on docs/img/enterprise/plugins/msteams/enroll-bot.png
Why does the same guide have 2 screenshots with dark theme and 1 with light theme? Can we be consistent?

2024-11-14 22:09 UTC, zmb3 commented on docs/img/enterprise/plugins/msteams/app-zip.png
Not a big deal, but this is 250KB of mostly plain purple background pixels.

Can we shrink the window a bit so we're not capturing so much empty space? It will improve readability too - the text on this is really small when rendered.

2024-11-14 22:10 UTC, zmb3 commented on docs/pages/admin-guides/access-controls/access-request-plugins/ssh-approval-msteams.mdx
> +(!docs/pages/includes/plugins/enroll.mdx name="the MsTeams integration"!)
Is `MsTeams` actually the publicly recognized name of the product, or should we say `Microsoft Teams` here?

2024-11-15 18:14 UTC, r0mant approved these changes

2024-11-15 18:59 UTC, zmb3 approved these changes

2024-11-15 22:02 UTC, merged