Remove Homebrew from Mac from docs
gravitational/teleport pull request #4923
Opened 2020-11-19 15:43 UTC by webvictim

We don't control the Teleport package in [Homebrew](https://brew.sh/) and there is [an outstanding issue](https://github.com/Homebrew/homebrew-core/issues/65004) which means that the Teleport 4.4.5 package is broken in Homebrew.

2020-11-19 16:05 UTC, markherring commented
Isn't home brew super popular? Can't we fix why they are using the wrong version?

2020-11-19 16:06 UTC, klizhentas requested changes
I just installed 4.4.5 on mac via brew and it worked OK. Also I agree with Mark it's super popular. Let's please fix the brew package instead 🙏

2020-11-19 16:23 UTC, benarent commented
This is both a benefit of being open source and a (good)curse. The reality is the community can do anything they desire with Teleport but even if didn't start the initiative we are still responsible for providing official support at a certain scale. 

Two example are supporting brew 
- https://github.com/gravitational/teleport/issues/3002
- https://github.com/gravitational/teleport/issues/4870 

and Docker Hub support
- https://github.com/gravitational/teleport/issues/4159

If we don't meet customers where they are, someone will half fill in part of the gap.

2020-11-19 18:28 UTC, webvictim commented
:man_shrugging:

2020-11-19 18:28 UTC, closed without merging

2020-11-20 13:39 UTC, fxcoudert commented
The brew package will be fixed, we are working on it. It's triggering a system bug, so in that sense it's not specific to brew (although it triggers relatively rarely: we have seen it about a dozen times out of 4000 tar files).

2020-11-20 15:07 UTC, webvictim commented
@fxcoudert Thank you very much for the information. I get frustrated because users complain about their systems breaking when there's absolutely nothing that we as the authors of the Teleport code can do to fix it. Hopefully either Apple will resolve it soon or Homebrew can implement a workaround.