Use strict teleport.yaml validation in warning mode
gravitational/teleport pull request #5057
Opened 2020-12-04 18:22 UTC by awly

Strict YAML validation catches the cases where a valid config key is
placed in the wrong location in the config. These errors were not
caught by the old validation.
The failure is always reported, but only fails startup when both old and
new validations fail. This will let the users fix their configs during
6.0 release and we will start enforcing it in 7.0.

Example:
```yaml
auth_service:
  data_dir: "/foo" # this field must live under "teleport:", not "auth_service:"
```

Output:
```
$ teleport start -c teleport-invalid.yaml
ERRO             "Teleport configuration is invalid: yaml: unmarshal errors:\n  line 6: field data_dir not found in type config.Auth." config/fileconf.go:303
ERRO             This error will be enforced in the next Teleport release. config/fileconf.go:304
[AUTH]         Auth service 5.0.0-dev:v4.4.0-alpha.1-262-g307040886-dirty is starting on 0.0.0.0:3025.
... continues startup ...
```

Updates https://github.com/gravitational/teleport/issues/5056

2020-12-04 20:36 UTC, a-palchikov approved these changes
lgtm except for the `time.Sleep` - is logging always configured to output to stderr so the user can actually see it?

2020-12-04 21:12 UTC, awly commented
@a-palchikov my reason for the sleep is that most users don't configure/run teleport manually, but provision it via some tooling (ansible, k8s, etc). So they don't see the logs most of the time, unless something goes wrong.
A startup delay might nudge them to investigate and actually look at logs.

This is kind of speculative, so if others also thing the sleep is a bad idea, I'll remove it.

2020-12-04 21:44 UTC, klizhentas requested changes
@awly can you fix the output to remove newlines? see in the output how the line is quoted

2020-12-04 22:15 UTC, awly commented
@klizhentas that output is coming from `yaml.UnmarshalStrict`, not from our code.
Should I `strings.Replace` all the newlines in the returned error?

2020-12-05 02:41 UTC, klizhentas commented
@awly yes, I would remove newlines from the output

2020-12-07 18:12 UTC, awly commented
Removed newlines, output looks like:
```
$ teleport start -c teleport-invalid.yaml
ERRO             Teleport configuration is invalid: yaml: unmarshal errors:  line 8: field data_dir not found in type config.Auth. config/fileconf.go:306
ERRO             This error will be enforced in the next Teleport release. config/fileconf.go:307
```

2020-12-14 18:46 UTC, awly commented
@klizhentas PTAL

2020-12-18 21:49 UTC, fspmarshall approved these changes

2020-12-18 21:50 UTC, klizhentas approved these changes

2020-12-18 22:11 UTC, merged