(6.0) Update release table to 6.0.0
gravitational/teleport pull request #5838
Opened 2021-03-04 02:08 UTC by r0mant

The release download table embedded in some pages was still using rc.1 release, update it to 6.0.0.

2021-03-04 17:48 UTC, klizhentas requested changes

2021-03-04 17:48 UTC, klizhentas commented on docs/pages/preview/releases-table.mdx
> +| Linux 64-bit DEB | [SHA256](https://get.gravitational.com/teleport_6.0.0_amd64.deb.sha256) | [teleport_v6.0.0_amd64.deb](https://get.gravitational.com/teleport_6.0.0_amd64.deb) |
can you use `{{version}}` var?

2021-03-04 18:08 UTC, r0mant commented on docs/pages/preview/releases-table.mdx
> +| Linux 64-bit DEB | [SHA256](https://get.gravitational.com/teleport_6.0.0_amd64.deb.sha256) | [teleport_v6.0.0_amd64.deb](https://get.gravitational.com/teleport_6.0.0_amd64.deb) |
Nice, I didn't know we had it. Updated.

2021-03-04 18:11 UTC, klizhentas commented
@r0mant please also forward-port the PR

2021-03-04 18:26 UTC, r0mant commented
@klizhentas https://github.com/gravitational/teleport/pull/5851

2021-03-04 18:45 UTC, webvictim commented
I'm curious why we're embedding a second set of links here, shouldn't we just be directing people off to https://goteleport.com/teleport/download? I could understand it during preview to make sure people got the correct version but now it's GA, the second set of links should probably go.

2021-03-04 21:03 UTC, r0mant commented
@webvictim Since these are "guides", I think the idea is to let people do as much as possible without leaving the page and not disrupt the flow. I'm not a fan of duplicating the links myself to be honest but I'm not aware of a decent (or any really) way to just embed our downloads table in the docs, which would probably be ideal. Maybe that's something that's on the grv/next roadmap? As a next best thing I think we could add a note here something along the lines of "or go to our Downloads page to pick an appropriate version" or something, in addition to the table?

@klizhentas Curious what you think as well ^

2021-03-06 23:50 UTC, klizhentas commented
I agree with @webvictim please point to downloads page

2021-03-08 21:07 UTC, r0mant commented
@klizhentas Done.

2021-03-09 03:49 UTC, webvictim approved these changes

2021-03-10 19:49 UTC, klizhentas approved these changes

2021-03-10 20:04 UTC, merged