Lint markdown files syntax for v4.3 with the new linter
gravitational/teleport pull request #5874
Opened 2021-03-05 17:51 UTC by iAdramelk

Broken links:

```
content/4.3/docs/pages/enterprise/sso/ssh-adfs.mdx
    134:5-134:159  warning  Link to http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname" is dead     no-dead-urls  remark-lint
content/4.3/docs/pages/features/enhanced-session-recording.mdx
   145:12-145:103  warning  Link to https://github.com/iovisor/bcc/blob/master/INSTALL.mdx#debian---source is dead          no-dead-urls  remark-lint
  214:106-214:198  warning  Link to https://github.com/iovisor/bcc/blob/master/INSTALL.mdx#amazon-linux-2---binary is dead  no-dead-urls  remark-lint
```

2021-03-06 22:04 UTC, klizhentas requested changes
Please escape the microsoft link and fix `.mdx` extension on two other links for the linter to pass

2021-03-08 13:18 UTC, iAdramelk commented
Added Microsoft link to whitelist and fixed broken md links

2021-03-08 16:24 UTC, klizhentas approved these changes

2021-03-08 16:35 UTC, klizhentas approved these changes

2021-03-08 16:37 UTC, klizhentas commented
@benarent @webvictim please approve folks

2021-03-08 16:39 UTC, benarent approved these changes

2021-03-08 16:40 UTC, merged