Lint markdown files syntax for v4.4 with the new linter
gravitational/teleport pull request #5875
Opened 2021-03-05 18:11 UTC by iAdramelk

Broken links:

```
content/4.4/docs/pages/enterprise/sso/ssh-adfs.mdx
   134:5-134:159  warning  Link to http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname" is dead               no-dead-urls  remark-lint
content/4.4/docs/pages/features/enhanced-session-recording.mdx
  143:12-143:103  warning  Link to https://github.com/iovisor/bcc/blob/master/INSTALL.mdx#debian---source is dead                    no-dead-urls  remark-lint
content/4.4/docs/pages/preview/teleport-application-access.mdx
    35:22-35:113  warning  Link to https://get.gravitational.com/teleport-v5.0.0-beta.10-linux-386-bin.tar.gz.sha265 is dead         no-dead-urls  remark-lint
    48:22-48:117  warning  Link to https://get.gravitational.com/teleport-ent-v5.0.0-beta.10-linux-386-bin.tar.gz.sha265 is dead     no-dead-urls  remark-lint
   51:119-51:249  warning  Link to https://get.gravitational.com/teleport-ent-v5.0.0-beta.10-linux-arm-bin.tar.gz is dead            no-dead-urls  remark-lint
content/4.4/docs/pages/preview/teleport-database-access.mdx
  229:21-229:125  warning  Link to https://github.com/gravitational/teleport/blob/roman/rfd/dba/rfd/0011-database-access.md is dead  no-dead-urls  remark-lint

```

2021-03-06 20:43 UTC, klizhentas requested changes
The link is broken because the processor added mdx extension by mistake:

https://github.com/iovisor/bcc/blob/master/INSTALL.mdx#debian

2021-03-08 13:20 UTC, iAdramelk commented
Upd: Added Microsoft link to whitelist and fixed broken md link. Other issues are still persist.

2021-03-08 16:24 UTC, klizhentas approved these changes

2021-03-08 16:34 UTC, benarent approved these changes

2021-03-08 16:34 UTC, merged