Support for multiple oidc providers
gravitational/teleport pull request #617
Opened 2016-11-25 20:36 UTC by tehsis

## Overview

We want to use a different OIDC provider for teleport (for instance auth0.com) which currently works as is with Teleport.
This PR adds support for a `Display` field on the OIDC provider configuration to use in the login button on the web ui. So you can use a friendly name to identify the provider (which may be google, auth0 or even your specific company name).

The PR also allows you to use different providers on the same auth cluster (you can use google and auth0 or two or more different google/auth0 accounts)

## Example configuration

```yaml
auth_service:
  enabled: yes
  cluster_name: cluster-b
  trusted_clusters:
      - key_file: /var/lib/teleport/cluster-a
  oidc_connectors:    
      - id: auth0
        display: Auth0
        redirect_url: https://10.0.10.20:3080/web/login:3080/v1/webapi/oidc/callback
        client_id: <auth0-client-id>
        client_secret: <auth0-client-secret>
        issuer_url: https://tehsis-teleport.auth0.com/ 
      - id: auth0-eu
        redirect_url: https://10.0.10.20:3080/web/login:3080/v1/webapi/oidc/callback
        client_id: <auth0-client-id>
        client_secret: <auth0-client-secret>
        issuer_url: https://tehsis-eu.eu.auth0.com/
```

This result in the following ui:

![screen shot 2016-11-25 at 5 34 34 pm](https://cloud.githubusercontent.com/assets/354324/20634972/92995030-b335-11e6-8385-1dac86160d5c.png)

Note that since display is not specified on the second connection, the id is used as a default value.

2016-11-25 20:54 UTC, klizhentas approved these changes
Looks good to me, @alex-kovoy can you review UI part as well?

2016-11-25 20:54 UTC, klizhentas commented
ok to test

2016-11-25 20:54 UTC, klizhentas commented
ok to test

2016-11-29 15:02 UTC, tehsis commented
Any news on this one?

2016-11-29 23:52 UTC, klizhentas requested changes

2016-11-29 23:52 UTC, klizhentas commented on lib/auth/auth.go
> +	user, err = a.Identity.GetUserByOIDCIdentity(services.OIDCIdentity{
I think this change is out of scope of this PR and should be submitted separately. So please revert this commit from this PR.

 Can you also write down a small issue/proposal explaining the desired change so we can discuss it separately.

2016-11-30 00:53 UTC, tehsis commented
@klizhentas fixed! I've created the issue to discuss this change.

2016-11-30 15:19 UTC, alex-kovoy commented
Looks good to me too

2016-11-30 16:37 UTC, alex-kovoy approved these changes
Looks good

2016-11-30 16:43 UTC, klizhentas commented
@tehsis please update with master and you are good to merge

2016-11-30 16:44 UTC, klizhentas approved these changes

2016-11-30 17:04 UTC, tehsis commented
done!

2016-11-30 17:14 UTC, klizhentas commented
ok, thanks for your contribution!

2016-11-30 17:14 UTC, merged