docs: document per-session MFA feature
gravitational/teleport pull request #6285
Opened 2021-04-01 19:29 UTC by awly

Also, update general U2F configuration docs to explain server-side
configs better.

Fixes https://github.com/gravitational/teleport/issues/3878

2021-04-02 01:24 UTC, klizhentas requested changes
@awly thanks for writing the docs. Can you please move most of the content to become `/access-controls/guides/per-session-mfa`

In the new structure I'm slowly splitting away the content from admin guide into separate parts. Ping me if you have questions

2021-04-02 03:14 UTC, klizhentas commented
@awly take a look for this guide with a new structure. A couple of notes:

https://raw.githubusercontent.com/gravitational/teleport/master/docs/pages/access-controls/guides/role-templates.mdx

* Add prerequisites, even if they are as simple as having a cluster installed and `tctl` connected
* After reading many guides, I've noticed if you create a simple narrative, with users `Alice` and `Bob` it's much easier for users to follow along
* The guide does not have to be long, could be pretty short 
* The guide should be self contained, ideally users can start from the beginning and follow along to the end without clicking elsewhere

More tips here:

https://goteleport/docs/docs

2021-04-07 23:15 UTC, awly commented
@klizhentas PTAL

Extracted U2F setup and per-session MFA setup into dedicated guides.

2021-04-08 18:14 UTC, klizhentas approved these changes

2021-04-08 18:24 UTC, merged