Update installation docs to use sudo
gravitational/teleport pull request #6307
Opened 2021-04-05 13:25 UTC by stevenGravy

Sudo (or running as root or a user with privileges) is required for these installation steps.  This makes it consistent with other installation examples in docs.

2021-05-06 01:44 UTC, inertial-frame approved these changes

2021-05-06 17:20 UTC, awly commented
I removed `sudo` from `./install` script calls, when installing from a tarball.
It's basically `curl | sudo bash` with extra steps, which is how codecov got popped.
otherwise LGTM

2021-05-06 17:21 UTC, awly approved these changes

2021-05-06 17:24 UTC, awly commented
@klizhentas or @russjones can one of you approve too?

2021-05-07 12:28 UTC, stevenGravy commented
> I removed `sudo` from `./install` script calls, when installing from a tarball.
> It's basically `curl | sudo bash` with extra steps, which is how codecov got popped.
> otherwise LGTM

thanks @awly !

2021-06-08 18:03 UTC, klizhentas requested changes

2021-06-08 18:03 UTC, klizhentas commented on docs/pages/installation.mdx
> +  $ sudo yum-config-manager --add-repo https://rpm.releases.teleport.dev/teleport.repo
let's remove dollar signs here and below

2021-07-08 21:33 UTC, klizhentas commented
@stevenGravy ping, let's remove this PR, and if you would like to push this change, please rebase against master.

2021-09-01 17:12 UTC, russjones commented
@stevenGravy If you still want to make these changes, please re-open or create another PR.

2021-09-01 17:12 UTC, closed without merging