Modify token language for teleport-kube-agent to allow for dynamic tokens
gravitational/teleport pull request #6487
Opened 2021-04-16 19:46 UTC by stevenGravy

To match our Kubernetes multiple cluster instructions, adding that you can use a dynamic token with a set ttl with a long time.

2021-04-16 22:29 UTC, awly approved these changes

2021-04-17 14:11 UTC, webvictim approved these changes

2021-04-17 14:11 UTC, webvictim commented on examples/chart/teleport-kube-agent/README.md
> +  for this Teleport cluster (`$JOIN_TOKEN`) or you can use a [dynamic join token](https://goteleport.com/docs/admin-guide/#short-lived-dynamic-tokens) with a lengthy time to live (ttl) (`tctl tokens
```suggestion
  for this Teleport cluster (`$JOIN_TOKEN`)
    - you can also use a [dynamic join token](https://goteleport.com/docs/admin-guide/#short-lived-dynamic-tokens) with a lengthy time to live (TTL) (`tctl tokens add --type=kube --ttl=10000`). The token setting will need updating if the token is changed or the TTL expires.
```

2021-04-20 20:53 UTC, stevenGravy commented
@russjones bot

2021-04-27 00:01 UTC, klizhentas requested changes
I would like to avoid recommending long-lived tokens and TTLs in our docs

2021-04-27 23:43 UTC, awly commented
@klizhentas is right.
A dynamic token with a long TTL is basically a static token.

2021-04-28 12:21 UTC, webvictim commented
A dynamic token with a fixed TTL is slightly more secure than a static token, because even a dynamic token with a 10,000 hour (416 day) TTL will _eventually_ expire, whereas a static token will not. I agree that we shouldn’t recommend the use of long-lived dynamic tokens though. 

The real way to fix this is to add support for Teleport to store its certs via Kubernetes API (https://github.com/gravitational/teleport/issues/4832)

2021-05-06 17:10 UTC, russjones commented
Once we support dynamic tokens, we'll update the language at the same time. Closing for now.

2021-05-06 17:10 UTC, closed without merging