move roleset and rulesets to separate packages
gravitational/teleport pull request #6770
Opened 2021-05-06 23:23 UTC by alex-kovoy

This PR moves roleset and ruleset into the separate packages. This way the cloud team can vendor below packages without a long dependency list.

```
"github.com/gravitational/teleport/lib/services/roleset"
"github.com/gravitational/teleport/lib/services/ruleset"
```	

This is a temporary fix while we are waiting for #6759

2021-05-07 03:18 UTC, alex-kovoy commented
@r0mant @Joerger could you guys review?

2021-05-07 04:12 UTC, klizhentas requested changes
I would prefer this in the `api` package so users of the api can discover there. Also wondering if we are bringing additional dependencies to the `api` package by importing utils? @Joerger  what do you think?

2021-05-07 17:14 UTC, Joerger commented
> I would prefer this in the `api` package so users of the api can discover there. Also wondering if we are bringing additional dependencies to the `api` package by importing utils? @Joerger what do you think?

Yes that would bring in many dependencies. Instead you'd need to extract the utils functions needed into `api/utils`.

2021-05-07 17:16 UTC, Joerger reviewed
Did you check if this fixes the extraneous import issue for cloud? IIUC Since teleport is a Go module, importing any teleport package imports the entire module, so this wouldn't solve the issue.

2021-05-07 20:05 UTC, alex-kovoy commented
@Joerger yes I did check that. We were able to cut ~200 files down. It also removes a need for us to compile it with `CGO` flag. As I understand, it may take some time for us to expose the `accesschecker` via API package in a clean way but I was wondering if we can go with this PR for now? @klizhentas  ^^

2021-05-07 22:49 UTC, alex-kovoy commented
@Joerger most of the said dependencies come from the `/teleport/lib/services` package which this PR fixes.

2021-05-07 22:54 UTC, klizhentas commented
@alex-kovoy @Joerger I would then ask us to fix it properly - by having the AccessChecker and role cache as described in #6759. Saving 200 files is not worth moving this code, as it would have to be moved again.

2021-05-08 17:43 UTC, alex-kovoy commented
@klizhentas i would not bother with this effort if it was just about these 200 files. It also forces us to change our build scripts because Teleport requires `CGO` and potentially we need to update our docker images along the pipeline to address breaking changes. If we are strongly against _moving_ the files than we will address it on our end.

2021-05-08 18:24 UTC, klizhentas commented
@alex-kovoy thanks for the explainer. I will leave this up to @Joerger and @awly to help you out then. The end state is described #6759, but @Joerger and @awly can decide how to get there and help you along the way.

2021-05-08 18:24 UTC, klizhentas reviewed
moving to comment for @Joerger and @awly

2021-05-11 21:02 UTC, awly reviewed
I like this change even if we don't make a proper [`AccessChecker` API](https://github.com/gravitational/teleport/issues/6759#issuecomment-838849214) on the auth server. It separates authorization logic from our data model.

I would prefer not to put this in the API client library, it does not belong there.

2021-05-19 17:47 UTC, russjones commented
@alex-kovoy Have not seen any movement on this, is this something you're still planning on implementing?

2021-06-09 22:54 UTC, alex-kovoy commented
This PR is no longer P0 for the cloud and I guess we can close it BUT I agree with @awly that this package makes the code more organized. I event suggest to move it 1 level up.

```
lib/
   /accesschecker
   /services
   ...
```   

@Joerger I know that you are working on refactoring and APIs, so you might be interested in taking over this PR because I do not have time to address comments and resolved merge conflicts since code is moving due to API work :)

2021-06-09 22:55 UTC, closed without merging