Updating teleport-quickstart.yml to latest release
gravitational/teleport pull request #6970
Opened 2021-05-20 16:43 UTC by corkrean

This teleport-quickstart.yml is used in our Docker quickstart guide (docker-compose section). https://goteleport.com/docs/quickstart-docker/#quickstart-using-docker-compose

I updated the quay repo from 5.0 to 6.1.5. (latest version at time of writing)

2021-05-20 19:08 UTC, webvictim requested changes

2021-05-20 19:08 UTC, webvictim commented on docker/teleport-quickstart.yml
> +    image: quay.io/gravitational/teleport:6.1.5
The old `5` tag was a 'nightly' tag - i.e it is rebuilt every night and points to the latest `5.x` Teleport version. We should use the equivalent `6` tag here.

[Here's a list of tags](https://quay.io/repository/gravitational/teleport?tag=latest&tab=tags) - see the `4.4`, `5` and `6` at the top.

```suggestion
    image: quay.io/gravitational/teleport:6
```

2021-05-20 19:08 UTC, webvictim commented on docker/teleport-quickstart.yml
> +    image: quay.io/gravitational/teleport:6.1.5
```suggestion
    image: quay.io/gravitational/teleport:6
```

2021-05-20 19:09 UTC, webvictim commented
@corkrean As you raised this PR directly against the Teleport repo, the tests will run and you'll be able to merge it yourself. See the "checks" section above and the link to Drone CI: https://drone.gravitational.io/gravitational/teleport/11891

2021-05-20 20:42 UTC, corkrean reviewed
Changing to incorporate nightly change repo.

2021-05-20 21:12 UTC, webvictim approved these changes

2021-05-21 19:39 UTC, inertial-frame approved these changes

2021-05-26 17:28 UTC, russjones approved these changes
Bot.

2021-05-26 19:07 UTC, merged

2021-05-26 20:14 UTC, webvictim commented
Needs to be backported along with #7055