[backport v7] Describe usage of TELEPORT_CONFIG_FILE in faq and cli page for remote tctl usage #6866
gravitational/teleport pull request #7067
Opened 2021-05-27 02:06 UTC by stevenGravy

backport of #6866

2021-05-27 21:02 UTC, inertial-frame requested changes

2021-05-27 21:02 UTC, inertial-frame commented on docs/pages/cloud/faq.mdx
> +$ export TELEPORT_CONFIG_FILE=""
I think we'll be appending the `$` and other code blocks programmatically in the future. There's an edit pass in place to get the code snippets that're already there. I can edit the last of these in one final pass in the future.

2021-05-27 21:02 UTC, inertial-frame commented on docs/pages/cli-docs.mdx
> +The `TELEPORT_CONFIG_FILE` environment variable indicates where the Teleport configuration file is.
Ran this through Grammarly.

2021-05-28 02:39 UTC, klizhentas approved these changes
approved assuming @inertial-frame's comments are applied

2021-06-02 14:57 UTC, inertial-frame approved these changes

2021-06-02 14:57 UTC, merged