define diag ports in helm
gravitational/teleport pull request #7107
Opened 2021-05-31 11:23 UTC by dinesh

Our monitoring agent (signalfx-agent) discovers pods when we actually define them in the object spec. This PR adds the diag port (3000) for high-availability setup.

To test -
 
```
$ helm template examples/chart/teleport --set config.highAvailability=true | grep -C 2 diag
        - name: diag
          containerPort: 3000
--
        - name: authssh
          containerPort: 3025
        - name: diag
          containerPort: 3000
        resources:
```

2021-05-31 14:40 UTC, webvictim commented
@dinesh This port should be optional i.e. gated behind a feature flag, as the chart doesn't open port 3000 by default.

2021-05-31 14:41 UTC, webvictim requested changes
@dinesh This port should be optional i.e. gated behind a feature flag, as the chart doesn't open port 3000 by default.

2021-05-31 16:52 UTC, dinesh commented
@webvictim tried adding logic to detect if metrics are enabled though it's a bit hacky. Please take a look.

2021-05-31 19:07 UTC, webvictim reviewed
That's actually not a bad way of doing it. Maybe it should check for `--diag-addr=0.0.0.0:3000` instead? If you specify `--diag-addr=127.0.0.1:3000` then the port doesn't need to be exposed because it's only listening for loopback connections. Seems like we could be explicit about only exposing it when the container's actually going to be listening on all interfaces.

2021-05-31 19:07 UTC, webvictim commented on examples/chart/teleport/templates/deployment.yaml
> +        {{- if contains "--diag-addr" .}}
```suggestion
        {{- if contains "--diag-addr" . }}
```

2021-06-01 13:07 UTC, dinesh commented on examples/chart/teleport/templates/deployment.yaml
> +        {{- if contains "--diag-addr" .}}
cool makes sense. updated it.

2021-06-07 18:47 UTC, webvictim approved these changes

2021-06-07 18:47 UTC, webvictim commented
Our CI doesn't run tests on external PRs at the moment so I'm going to make a branch and PR it myself.

2021-06-07 20:11 UTC, webvictim commented
My PR: https://github.com/gravitational/teleport/pull/7212

2021-06-11 20:51 UTC, webvictim commented
Hey @dinesh, thanks for the PR. It's been merged to `master` now, see https://github.com/gravitational/teleport/pull/7212

Closing this mirror.

2021-06-11 20:51 UTC, closed without merging