Add abilty to configure postStart handler for teleport-cluster chart
gravitational/teleport pull request #7168
Opened 2021-06-03 18:29 UTC by stefansedich

This PR introduces the ability to configure a `postStart` handler. We are using this to configure a script that will run `tctl create` of our roles and provider config when the server starts.

2021-06-23 16:43 UTC, russjones commented
@webvictim Can you review?

2021-06-24 12:15 UTC, webvictim requested changes
@stefansedich Changes look good to me.

Please also add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so that it's kept up to date.

Thanks for the PR!

2021-06-25 18:01 UTC, stefansedich commented
> @stefansedich Changes look good to me.
> 
> Please also add this value to the Helm chart reference at https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/reference.mdx so that it's kept up to date.
> 
> Thanks for the PR!

@webvictim that should be done.

2021-06-28 13:25 UTC, webvictim approved these changes

2021-06-28 13:25 UTC, webvictim commented
@stefansedich Thanks - this will be merged once it has another approving review.

2021-06-29 16:01 UTC, inertial-frame approved these changes

2021-06-29 16:04 UTC, inertial-frame commented on docs/pages/kubernetes-access/helm/reference.mdx
> +## `postStart`
Do you mind adding the same kind of table you added in https://github.com/gravitational/teleport/pull/7167/files:

```
## `extraEnv`

| Type | Default value | Can be used in `custom` mode? |
| - | - | - |
| `list` | `[]` | ✅  |
```

2021-06-29 16:29 UTC, klizhentas approved these changes

2021-08-19 17:15 UTC, stefansedich commented
@klizhentas anything I need to do to get CI running?

2021-08-19 21:30 UTC, webvictim commented
@stefansedich External PRs require approval to run, I just hit the start button.

2021-08-20 14:31 UTC, merged