Terraform reference docs
gravitational/teleport pull request #7233
Opened 2021-06-09 15:38 UTC by gzigzigzeo

Closes teleport-plugins/#253

2021-06-09 18:28 UTC, inertial-frame requested changes
Thank you very much! Super helpful! 

Just a few editorial items here - I will validate further once changes are made.

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +# <a name="teleport_user"></a>`teleport_user`
Great job splitting up each of these sections! Super easy to read through and find what you need.

Nitpicks:

1. Can you remove the anchor tags? Links to the H1, H2, ... headings will be automatically generated.
2. Can you remove tic marks from the headings?

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +User resource allows to manage Teleport users: create, update, delete, assign and revoke roles and permissions.
Nit: `create`, `update`, `delete`, `assign`, and `revoke` - reduces ambiguity so it's clear that `assign and revoke` is not a role. Thanks!

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +`metadata` is a user metadata
Nit: colon or period here please

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +# <a name="teleport_role"></a>`teleport_role`
Same as above thanks

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +Metadata is a role metadata
Colon or period here and in similar places below please

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +`review_requests` is a matcher for allow/deny restrictions on  access reviews.
Extra space. Also, `allow/deny` implies that these are interchangeable or the same. Can we say `allow`, `deny` instead?

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +```
Do you mind adding the language: `YAML` - I'm not sure this presently has any functional differences but we've planned some cool things in the future that might use these more

2021-06-09 18:28 UTC, inertial-frame commented on docs/pages/setup/guides/terraform-provider/reference.mdx
> +`spec` is a provision token spec. It has a single field: `roles` (string list) which is a list of roles associated with the token,  that will be converted to metadata in the SSH and X509 certificates
Probably break this up into two sentences. `. It will be ...`

2021-06-11 01:52 UTC, klizhentas commented
I will send a different PR with this as a base.

2021-06-11 01:52 UTC, closed without merging