Multiple Principals
gravitational/teleport pull request #730
Opened 2017-01-28 05:34 UTC by russjones

**Purpose**

As covered in https://github.com/gravitational/teleport/issues/579, connecting to a Teleport node from an OpenSSH client presents a UX problem: you need to connect via the host UUID + cluster name for certificate verification to pass.

To improve the UX for users with Teleport nodes and OpenSSH clients, this PR adds the node name into the list of Principals on the certificate. This means as long the DNS name for the host matches the node name, OpenSSH clients should be able to connect to Teleport nodes without problems.

**Implementation** 

_Code Updates_

* The signature for `GenerateHostCert` method on the `Authority` interface (as well as the implementation in `lib/auth/native`) has been updated with `nodeName`.
* All functions up to `GenerateHostCert` have been updated to pass along the node name along with the host ID.
* `authDomain` has been renamed `clusterName`.

_Documentation Updates_

The Teleport Admin Manual has been updated to reflect two things:

1. For Teleport and OpenSSH interoperability it is recommended node names and DNS names should match.
1. You can not connect to Teleport nodes by IP address in older versions of OpenSSH.

2017-01-28 17:36 UTC, klizhentas commented
ok to test

2017-01-29 02:12 UTC, kontsevoy commented
@russjones you need to make integration tests pass. To debug them, type:

```
$ make integration
```

They do not run as part of `make test` to make testing faster, so it's advised to run `make integration` manually before creating pull requests.

2017-01-29 20:19 UTC, klizhentas commented on lib/auth/apiserver.go
> +	ClusterName string         `json:"cluster_name"`
I would change the data structure name, but keep the json version of it to `auth_domain` or write the migration procedure.

2017-01-29 20:19 UTC, klizhentas commented on lib/auth/auth.go
> +	GenerateHostCert(privateCASigningKey, publicHostKey []byte, hostID, nodeName, clusterName string, roles teleport.Roles, ttl time.Duration) ([]byte, error)
there is a lot of parameters in this function, at this point it makes sense to introduce the CertParams struct and put fields there

2017-02-06 22:53 UTC, russjones commented
@klizhentas Made the changed you suggested, can you review again?

2017-02-07 16:57 UTC, klizhentas commented on docs/admin-guide.md
> +    You can not connect to Teleport node by IP addresses using most version of OpenSSH, you can only connect via DNS name. When validating a certificate the OpenSSH client validates the DNS hostname
* formatting is a bit off compared to the rest of the text
* most version -> most recent?

2017-02-07 16:58 UTC, klizhentas commented on integration/helpers.go
> +	cert, err := keygen.GenerateHostCert(services.CertParams{
looking at the usage, I think `CertParams` could be renamed to `CSR` or `CertSignRequest`

2017-02-07 16:59 UTC, klizhentas commented on lib/auth/apiserver.go
> +	NodeName    string         `json:"node_name"`
this makes API backwards - incompatible, so you have to address this before merging.

2017-02-07 17:00 UTC, klizhentas commented on lib/auth/apiserver.go
> +	HostID   string        `json:"hostID"`
we are using `_` vs camel case in Teleport, `hostID` is unfortunate, so we have to keep it, but the rest of the args let's keep them underscore for now

2017-02-07 17:02 UTC, klizhentas commented on lib/auth/init.go
> +	if len(cert.ValidPrincipals) != 2 {
you can have more than two, also this makes existing nodes backwards incompatible, so you  have to regenerate host cert if you detect this situation here

2017-02-07 17:03 UTC, klizhentas commented on lib/auth/native/native.go
> +		fmt.Sprintf("%s.%s", c.HostID, c.ClusterName),
what if `HostID` or `NodeName` are passed empty? you have to check parameters for sanity I think

2017-02-07 17:04 UTC, klizhentas commented on lib/services/authority.go
> +	PrivateCASigningKey []byte
public members should have comments, also we are following these guidelines:

https://github.com/golang/go/wiki/CodeReviewComments

2017-02-07 17:04 UTC, klizhentas commented on lib/services/authority.go
> +func (c CertParams) Check() error {
why not pointer receiver here?

2017-02-07 17:06 UTC, klizhentas requested changes
Two main issues to address before merging is API backwards-compatibility.

* You can have new method to be available under v2 and old methods with old data structures under v1 if needed. 

* Node certificate upgrade path - we should not crash if teleport starts with old cert without two principals.

2017-02-07 22:12 UTC, russjones commented on lib/services/authority.go
> +func (c CertParams) Check() error {
I'm not making changes to `CertParams`? If it's a convention to use a pointer receiver for all `Check` methods I can change it.

2017-02-07 23:16 UTC, russjones commented
retest this please

2017-02-08 02:09 UTC, kontsevoy commented
retest this please

2017-02-09 02:40 UTC, klizhentas approved these changes

2017-02-09 02:40 UTC, russjones commented
retest this please

2017-02-10 02:23 UTC, merged