Update trustedclusters.mdx
gravitational/teleport pull request #7462
Opened 2021-07-02 17:40 UTC by Aharic

Changed "leaf:admin" to "leaf:access" in RBAC mapping example to avoid confusion and maintain consistency with rest of example.

2021-07-02 18:19 UTC, inertial-frame requested changes

2021-07-02 18:19 UTC, inertial-frame commented on docs/pages/trustedclusters.mdx
> +Now, we need to establish trust between roles "root:admin" and "leaf:access". This is
Great catch!

I'm wondering if we want to elevate someone's access here (even if this is just an example). I'd think we'd want the level of access to be the same. Especially from a leaf cluster to a root cluster.

I'd think we'd want to update the YAML to have the same mapping instead (which seems to be the intent of the comment too):

```yaml
role_map:
    - remote: admin
      # admin <-> admin works for the Open Source Edition. Enterprise users
      # have great control over RBAC.
      local: [admin]
```

My guess is that this snippet was copy-pasted in from somewhere.

2021-07-08 21:41 UTC, klizhentas requested changes

2021-07-08 21:41 UTC, klizhentas commented on docs/pages/trustedclusters.mdx
> +Now, we need to establish trust between roles "root:admin" and "leaf:local-admin". This is
We should be moving away from the admin role and use access role as much as possible.

2021-07-28 17:00 UTC, klizhentas commented
@Aharic ping

2021-07-31 18:51 UTC, klizhentas commented
@Aharic ping.

2021-09-23 16:47 UTC, closed without merging