Update teleport container image version to 6.2.7(latest) in teleport-quickstart.yml
gravitational/teleport pull request #7539
Opened 2021-07-13 13:53 UTC by sshahcodes

Trying out teleport quickstart via [docker compose method](https://goteleport.com/docs/setup/guides/docker-compose/#creating-a-teleport-user-when-using-docker-quickstart) fails with error `error: unknown long flag '--roles'` while executing command `docker exec teleport tctl users add testuser --roles=editor,access --logins=root,ubuntu,ec2-user` because the teleport container image version in `teleport-quickstart.yml` still points to v5.

This PR updates the quickstart file with an image version pointing to v6.2.7 (latest)

2021-07-13 13:58 UTC, webvictim requested changes
If you use `6` as the tag it'll automatically pick the latest 6.x version of Teleport. This saves updating the docs every single time we release.

https://quay.io/repository/gravitational/teleport?tab=tags

These images are rebuilt with the latest version every night.

2021-07-13 13:58 UTC, webvictim commented on docker/teleport-quickstart.yml
> +    image: quay.io/gravitational/teleport:6.2.7
```suggestion
    image: quay.io/gravitational/teleport:6
```

2021-07-13 13:58 UTC, webvictim commented on docker/teleport-quickstart.yml
> +    image: quay.io/gravitational/teleport:6.2.7
```suggestion
    image: quay.io/gravitational/teleport:6
```

2021-07-15 21:09 UTC, webvictim approved these changes

2021-07-15 21:54 UTC, klizhentas approved these changes

2021-07-28 16:36 UTC, russjones approved these changes
Bot.

2021-09-18 01:01 UTC, closed without merging