Add kube-cluster env for tsh
gravitational/teleport pull request #7867
Opened 2021-08-10 23:46 UTC by Joerger

Closes https://github.com/gravitational/teleport/issues/7641

2021-08-11 17:05 UTC, russjones commented on tool/tsh/tsh.go
>  		fmt.Printf("export %v=%v\n", proxyEnvVar, profile.ProxyURL.Host)
@timothyb89 Does Windows have the equivalent of environment variables and commands like `unset`?

2021-08-11 17:19 UTC, timothyb89 commented on tool/tsh/tsh.go
>  		fmt.Printf("export %v=%v\n", proxyEnvVar, profile.ProxyURL.Host)
I believe the syntax for Windows varies for cmd.exe vs PowerShell:

cmd.exe:
```
set FOO=bar
set FOO=
```


PowerShell:
```
$Env:FOO = "bar"
Remove-Item Env:\FOO
```

2021-08-11 17:36 UTC, zmb3 commented on tool/tsh/tsh.go
>  		fmt.Printf("export %v=%v\n", proxyEnvVar, profile.ProxyURL.Host)
@timothyb89 you should be able to check for the `PSModulePath` environment variable to see if you're in PowerShell.

2021-08-13 15:37 UTC, andrejtokarcik reviewed
Do I understand correctly this PR overrides https://github.com/gravitational/teleport/pull/7840 in the sense that Teleport should _not_ take the `$KUBECONFIG` env var into account and use `$TELEPORT_KUBE_CLUSTER` instead? If so, shouldn't `kubeconfig.PathFromEnv` be removed?

2021-08-13 16:29 UTC, Joerger commented
> Do I understand correctly this PR overrides #7840 in the sense that Teleport should _not_ take the `$KUBECONFIG` env var into account and use `$TELEPORT_KUBE_CLUSTER` instead? If so, shouldn't `kubeconfig.PathFromEnv` be removed?

This PR doesn't override the other one. `$TELEPORT_KUBE_CLUSTER` is just used to set `CLIConf.KubernetesCluster` rather than providing it through `tsh login --kube-cluster=...`. So actually the two PRs can be used together by setting `$TELEPORT_KUBE_CLUSTER=kube1` and `$KUBECONFIG=~/.tsh/.../kubeconfig-kube1`.

2021-08-16 06:19 UTC, tcsc approved these changes

2021-08-17 14:14 UTC, andrejtokarcik approved these changes

2021-08-20 22:56 UTC, zmb3 commented on tool/tsh/tsh.go
>  		fmt.Printf("export %v=%v\n", proxyEnvVar, profile.ProxyURL.Host)
@Joerger let's just make a separate issue to track this.

2021-08-23 14:58 UTC, zmb3 commented on tool/tsh/tsh.go
> +func readKubernetesClusterFlag(cf *CLIConf, fn envGetter) {
Might want to rename this since it does more than than read a flag.

2021-08-23 14:59 UTC, zmb3 commented on tool/tsh/tsh_test.go
> +		t.Run("TELEPORT_KUBE_CLUSTER and CLI flag is set, prefer CLI", testEnvFlag(testCase{
Add a test for only the CLI flag set.

2021-08-23 14:59 UTC, zmb3 requested changes
Would be good to see one more test to cover all 4 cases (nothing set, flag set, env var set, both flag and env var set).

2021-08-24 19:59 UTC, Joerger commented on tool/tsh/tsh.go
>  		fmt.Printf("export %v=%v\n", proxyEnvVar, profile.ProxyURL.Host)
@zmb3  https://github.com/gravitational/teleport/issues/8047

2021-08-27 14:21 UTC, zmb3 approved these changes

2021-08-30 17:55 UTC, klizhentas approved these changes

2021-08-30 21:28 UTC, merged