Move newly-added Webauthn tests out of gocheck
gravitational/teleport pull request #8074
Opened 2021-08-26 19:48 UTC by codingllama

Move newly-added tests from gocheck to testing/require.

2021-08-26 20:43 UTC, zmb3 requested changes

2021-08-26 21:48 UTC, zmb3 approved these changes

2021-08-30 14:36 UTC, codingllama commented
FYI, rebased and made newly-merged code use newIdentityService.

2021-08-30 16:14 UTC, quinqu approved these changes

2021-08-30 17:18 UTC, klizhentas approved these changes

2021-08-30 17:59 UTC, merged