Desktop Access Beta documentation
gravitational/teleport pull request #8504
Opened 2021-10-07 00:13 UTC by awly

First draft of the Desktop Access docs. This is for Beta and has the
warnings on every page to make that clear.

2021-10-07 18:21 UTC, zmb3 approved these changes

2021-10-07 21:39 UTC, ibeckermayer approved these changes
Left a bunch of nitpicky inline grammar suggestions, otherwise LGTM

2021-10-09 18:11 UTC, klizhentas requested changes
@zmb3 I've left some comments on the naming and style. I'm assuming you are taking over this doc section. 

@benarent please add the video walk-through for the introduction before beta release at the end of October

2021-10-11 17:33 UTC, klizhentas approved these changes

2021-10-11 22:42 UTC, merged