Desktop Access notes and comments
gravitational/teleport pull request #8530
Opened 2021-10-08 18:06 UTC by awly

Also, Fixes #8521

2021-10-08 20:38 UTC, zmb3 requested changes

2021-10-08 22:18 UTC, zmb3 approved these changes
Looks good.

2021-10-10 21:35 UTC, zmb3 commented
@codingllama I'm going to take this one over for Andrew, so added you as a reviewer. Mostly just extra godoc. PTAL.

2021-10-11 15:23 UTC, codingllama approved these changes
A few comments/questions, but nothing blocking.

Btw, my Rust is pretty much non-existent, so for actual .rs changes you'd be better off with another reviewer. Feel free to cc: me, though.

2021-10-11 16:49 UTC, codingllama approved these changes

2021-10-11 16:53 UTC, klizhentas approved these changes

2021-10-11 17:24 UTC, merged