Cleanup lint targets
gravitational/teleport pull request #8599
Opened 2021-10-13 22:04 UTC by zmb3

- Don't assume an explicit $GOPATH is set
- Remove golint from linters - it's been deprecated for over a year
  and golangci-lint prints a warning instead of running it.

2021-10-14 14:06 UTC, rosstimothy approved these changes
Funny enough I was working on replacing golint with revive because I was sick of seeing that warning

2021-10-14 17:10 UTC, codingllama requested changes

2021-10-18 20:10 UTC, codingllama commented
> What's the verdict here? Should we abandon this in favor of @rosstimothy's other changes, which includes adding revive?

My 2c:

1. Push the golint removal and GOPATH fix
2. Leave the actual revive inclusion to @rosstimothy's PR

Removing goimports is trickier, I think. I would rather not be without any format linters, and gofmt is slightly different. Does gofmt sorts out your issues?

Btw, did you see my comment about using a make variable for GOPATH?

2021-10-19 14:58 UTC, codingllama approved these changes

2021-10-19 15:06 UTC, klizhentas approved these changes

2021-10-19 15:21 UTC, r0mant approved these changes

2021-10-19 15:21 UTC, merged