kubectl exec and port-forward requests use the right dialer
gravitational/teleport pull request #8601
Opened 2021-10-13 22:38 UTC by Joerger

In https://github.com/gravitational/teleport/pull/8362, I introduced `dialWithEndpoints` to properly forward kubectl requests for kube clusters with multiple `kube_service` registrations. However, this dial logic was not properly propogated to `kubectl exec` and `kubectl port-forward` requests. 

This PR fixes that by changing `clusterSession.Dial` to switch between a direct dial and `dialWithEndpoints` depending on the targets available in the `clusterSession`. Now all consumers of `Dial` or `DialWithContext` will get the new functionality safely.

Bug report - https://gravitational.slack.com/archives/C01TYKHFVTQ/p1634136552298200

2021-10-15 14:50 UTC, zmb3 requested changes
Looking much better, but see comments about subtests - I think we may be overusing that feature here.

2021-10-15 17:57 UTC, zmb3 approved these changes

2021-10-15 18:56 UTC, atburke approved these changes

2021-10-15 19:29 UTC, r0mant reviewed
Just a small question, otherwise lgtm.

2021-10-19 16:12 UTC, r0mant approved these changes

2021-10-19 20:22 UTC, merged