Update workflow files to run workflows in the context of master
gravitational/teleport pull request #8728
Opened 2021-10-26 00:15 UTC by quinqu

I noticed when I opened my last PR to fix the workflow `yaml` files in master, the workflows ran properly which was not what we expected or wanted. The line in the workflow files `uses: actions/checkout@master` does not actually check out `master`, `master` is the version. This fix actually checks out the `master` branch. 

Here are the docs specifying [how to checkout the master branch](https://github.com/actions/checkout#usage) (look at the `ref` key). 

An important thing to note about this is that when a user opens a PR it will indeed run in the context of master even if the author changes the workflow files ([tested here](https://github.com/gravitational/gh-actions-poc/runs/4003547309?check_suite_focus=true)). This run follows what is [written in master](https://github.com/gravitational/gh-actions-poc/blob/master/.github/workflows/assign.yml), it echos a bunch of stuff, however if you go to the run and click on the 3 dots in the right hand corner, it will display the [changes made from the open PR](https://github.com/gravitational/gh-actions-poc/actions/runs/1383373321/workflow) (removal of all the echos). This is confusing and I'm unsure why Github actions does this, however this change is safe and will indeed run in the context of master as seen by the steps in the [run here](https://github.com/gravitational/gh-actions-poc/runs/4003547309?check_suite_focus=true)(runs the `echo` commands).

2021-10-26 00:32 UTC, russjones approved these changes

2021-10-26 04:28 UTC, tcsc requested changes

2021-10-26 04:29 UTC, tcsc reviewed
I'm leaving this as a comment rather than "change requested" so I don't hold up things overnight, but these changes should be made prior to merging.

2021-10-26 04:32 UTC, tcsc approved these changes

2021-10-26 16:51 UTC, r0mant approved these changes

2021-10-26 19:55 UTC, zmb3 approved these changes

2021-11-03 17:03 UTC, russjones commented
@quinqu I think we can merge this, it's a good fix to get in even if we have the workflows disabled until we're confident they can run securely.

2021-11-03 18:31 UTC, merged