Skip reviewers check on draft synchronize events
gravitational/teleport pull request #8967
Opened 2021-11-12 19:00 UTC by xacrimon

2021-11-12 19:23 UTC, zmb3 commented
Will reviewers be added when the mm pull request is promoted out of draft status?

2021-11-12 19:57 UTC, quinqu requested changes

2021-11-12 19:57 UTC, quinqu commented on .github/workflows/assign.yaml
> +    if: !github.event.pull_request.draft
```suggestion
    if: ${{ !github.event.pull_request.draft }}
```

2021-11-12 19:57 UTC, quinqu commented on .github/workflows/check.yaml
> +    if: !github.event.pull_request.draft
```suggestion
   if: ${{ !github.event.pull_request.draft }}
```

2021-11-12 19:57 UTC, quinqu commented
@zmb3 Yes

2021-11-17 18:06 UTC, russjones commented
@quinqu Is there a way we can push this logic into the bot code itself? Or does it have to be in the workflow.

It probably has to be in the workflow, but maybe you know some trick?

2021-11-17 18:14 UTC, xacrimon commented
@russjones as far as I know, this has the effect of just marking the run as done, something similar could be achieved by just skipping the check on draft PR's but we'd still need to get that info to the bot.

2021-11-17 18:54 UTC, quinqu commented
@russjones There isn't a way to push the logic to the bot code, unfortunately.

2021-11-17 18:56 UTC, quinqu commented
@xacrimon This change doesn't mark the run as done, it just skips it altogether.

2021-12-07 17:47 UTC, russjones commented
Let's close this for now, we can come back to this item later when we have a better idea on how to address it.

2021-12-07 17:47 UTC, closed without merging

2021-12-07 17:55 UTC, quinqu commented
@russjones This change works, it has been addressed.

2021-12-07 18:07 UTC, quinqu commented
@russjones @xacrimon I am just going to make this change since this PR had been open for a while.