Updated build-darwin-* pipeline.
gravitational/teleport pull request #8982
Opened 2021-11-13 02:28 UTC by russjones

**Description**

Updated `build-darwin-*` pipeline to use per-build Rust and Go toolchain.

2021-11-13 04:03 UTC, r0mant approved these changes

2021-11-13 13:54 UTC, zmb3 requested changes

2021-11-13 13:54 UTC, zmb3 commented on .drone.yml
>  - name: Build Mac release artifacts
I think you'll have to update PATH for the build artifacts step so that the per-build tool chains are detected first.

2021-11-15 18:54 UTC, zmb3 approved these changes

2021-11-15 19:29 UTC, merged