simplify connection establishment
gravitational/teleport pull request #9088
Opened 2021-11-20 13:35 UTC by ibeckermayer

It turns out that passing the initial username/screen-size parameters in the connection string was non-trivial, because we are limited in what we can pass from the handler in the proxy to the desktop service.

I've "solved" this by adding to Andrew's wizardry of [passing information via the SNI](https://github.com/gravitational/teleport/blob/c37d5792cfb57cb2469dd7c135e5466042ef3cbc/lib/web/desktop.go#L119-L126) and then [decoding it](https://github.com/gravitational/teleport/blob/c37d5792cfb57cb2469dd7c135e5466042ef3cbc/lib/srv/desktop/windows_server.go#L591-L601) on the other side of the connection.

Also takes the opportunity to remove the `InputMessage` and `OutputMessage` callbacks and replace them with a `tdp.Conn`.

TODO: remove send username from tdp

2021-11-20 14:52 UTC, zmb3 requested changes

2021-11-20 14:52 UTC, zmb3 commented on lib/web/desktop.go
> +	tlsConfig.ServerName = strings.Join([]string{
I don't love adding to the server name here. The server name should really just be used to identify the server we're connecting to.

Could we do away with this, and just send the TDP messages with login and screen size ourselves before we start proxying TDP messages from the browser?

2021-11-20 14:52 UTC, zmb3 commented on lib/web/desktop.go
> +// GET /webapi/sites/:site/desktops/:desktopName/connect?access_token=bearer_token&params=<urlencoded json-structure>
Why JSON-encoded? What's wrong with something like

```
?access_token=foo&login=Administrator&w=600&h=400
```

2021-11-20 14:52 UTC, zmb3 commented on lib/web/desktop.go
> +// Due to the nature of websocket we can't POST parameters as is, so we have
This isn't even a `POST` endpoint, so I don't think we should be talking about POSTing paramaters.
```suggestion
// Due to the nature of websocket we can't provide a request body, so we have
// to encode connection information in query parameters.
```

2021-11-20 14:52 UTC, zmb3 commented on lib/srv/desktop/rdp/rdpclient/client_common.go
> +	Width string
I might call these `InitialWidth` and `InitialHeight` given that we will soon support resizing.

Also, should they be strings?

2021-11-20 14:52 UTC, zmb3 commented on lib/srv/desktop/rdp/rdpclient/client_common.go
> +	TDPConn *tdp.Conn
Is `TDPConn` something we can have `connectRDP` create rather than requiring it be provided in the config?

2021-11-22 22:09 UTC, ibeckermayer commented
Closed in favor of https://github.com/gravitational/teleport/pull/9098

2021-11-22 22:09 UTC, closed without merging