helm: Allow setting issuer group for certificate in teleport-cluster
gravitational/teleport pull request #9138
Opened 2021-11-25 14:53 UTC by thehunt33r

Hi,

External issuers for cert-manager require setting a different issuer group. This is not currently supported by the Helm chart which doesn't allow for creating certificates with external issuers (such as AWS ACM PCA).

In this PR I've added the `group` argument to the `issuerRef` declaration, and I've added a default value in the `values.yaml` to `cert-manager.io` which is the default group for built-in issuers.

2021-11-29 16:22 UTC, corkrean commented
Hey @webvictim, could you take a look at this?

2021-11-29 17:37 UTC, webvictim requested changes, later dismissed
LGTM on the whole with the one change I suggested.

@thehunt33r Could you also please add a values file using `issuerGroup` under https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster/.lint so that the linter will check it?

2021-11-29 17:37 UTC, webvictim commented on docs/pages/kubernetes-access/helm/reference.mdx
> +  --set highAvailability.certManager.issuerKind=cert-manager.io
```suggestion
  --set highAvailability.certManager.issuerGroup=cert-manager.io
```

2021-12-01 07:49 UTC, thehunt33r commented on docs/pages/kubernetes-access/helm/reference.mdx
> +  --set highAvailability.certManager.issuerKind=cert-manager.io
@webvictim Thanks!

2021-12-01 07:50 UTC, thehunt33r commented
@webvictim Thanks for the feedback. I have updated my branch. Sorry for the delay!

Do you think I should also add the `commonName` field (maybe make it optional so that the current behavior doesn't change)?

2021-12-01 14:46 UTC, webvictim reviewed
@thehunt33r Looks good - one more tiny change. I need to copy and raise this PR myself so that CI will run it, so I'll do that later today.

Regarding `commonName`: if it's needed for AWS ACM PCA then it's probably worth adding, as I'd imagine that will be a common use case. I'd agree that it should be an optional field.

Many thanks for the changes!

2021-12-01 14:46 UTC, webvictim commented on docs/pages/kubernetes-access/helm/reference.mdx
> +Sets the `Group` of `Issuer` to be used when issuing certificates with `cert-manager`. Defaults to `cert-manager.io` to use built-in issuers
```suggestion
Sets the `Group` of `Issuer` to be used when issuing certificates with `cert-manager`. Defaults to `cert-manager.io` to use built-in issuers.
```

2021-12-01 15:06 UTC, thehunt33r commented
Thanks @webvictim 

I've added the optional `commonName` field in the certificate.yaml. Not super happy with the implementation but I'm open for your suggestions for more... elegant... ideas. Unfortunately I think it would be clunky to force users to instruct the `commonName` since it will almost always match the `clusterName`... but the boolean isn't great either.

2021-12-14 16:02 UTC, webvictim commented
/gcbrun

2021-12-20 22:02 UTC, webvictim approved these changes
I think this is good now, the linter passed.

2021-12-20 22:03 UTC, webvictim commented
/gcbrun

2022-01-04 15:28 UTC, zmb3 approved these changes

2022-01-05 14:36 UTC, webvictim commented
Ping @r0mant @russjones @klizhentas, please approve.

2022-01-05 14:36 UTC, webvictim commented
/gcbrun

2022-01-15 01:39 UTC, russjones approved these changes

2022-01-15 02:25 UTC, russjones commented
/gcbrun

2022-01-15 02:46 UTC, merged