Replace deb repo with a curl and dpkg -i
gravitational/teleport pull request #9229
Opened 2021-12-04 02:29 UTC by wadells

v7 backport of #9227 

The debian repo is currently broken, and we shouldn't recommend
customers use it until it is fixed.

Contributes to https://github.com/gravitational/teleport/issues/8166

(cherry picked from commit df3146258a6a4102a0c35d03a776fa62df0ecf1b)

2021-12-06 18:46 UTC, webvictim approved these changes

2021-12-06 18:48 UTC, webvictim requested changes

2021-12-06 18:48 UTC, webvictim commented on docs/pages/getting-started/linux-server.mdx
> +    $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
    $ curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-06 18:48 UTC, webvictim commented on docs/pages/installation.mdx
> +    $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
    $ curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-06 18:48 UTC, webvictim commented on docs/pages/server-access/getting-started.mdx
> +      $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
      $ curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-09 21:28 UTC, russjones commented
Closing this since since we won't be using this approach. @wadells reopen if needed.

2021-12-20 01:43 UTC, wadells commented on docs/pages/getting-started/linux-server.mdx
> +    $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
Fixed in 410b11d.

2021-12-20 01:43 UTC, wadells commented on docs/pages/installation.mdx
> +    $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
Fixed in 410b11d.

2021-12-20 01:43 UTC, wadells commented on docs/pages/server-access/getting-started.mdx
> +      $ curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
Fixed in 410b11d.

2021-12-20 01:48 UTC, wadells commented
Hi @russjones.

I believe we should take this change for branches 7 and below.  I've only re-opened this one, to hash out the discussion though.  If we do merge, I'll reopen the others.

Why should we take this?  Our users are getting confused about how to install Teleport locked to old versions, because the *default* linux instructions on old branches suggest using `deb https://deb.releases.teleport.dev/ stable main` -- which for compatibility reasons will always install the latest teleport.  `curl` + `dpkg` is a short term docs win that is improves the install for every  branch older than the latest.

For an example this impacting users, see https://github.com/gravitational/teleport/issues/9241.

When we have a fix that allows apt to pin to an older major/minor version, I'll make sure to update these docs to use apt again.  Unfortunately we don't have that today, and with upcoming PTO, I won't have that ready until some time in the new year.

2021-12-22 20:28 UTC, webvictim approved these changes
I agree this approach makes sense in the short term. We've had a lot of issues with people being upgraded to versions of RPMs/DEBs from the repos that they weren't expecting and this seems a low-effort, reasonable solution in the short term.

2022-01-14 04:12 UTC, closed without merging