[v6.2] Replace deb repo with a curl and dpkg -i
gravitational/teleport pull request #9230
Opened 2021-12-04 02:44 UTC by wadells

v6.2 backport of #9227 

The debian repo is currently broken, and we shouldn't recommend
customers use it until it is fixed.

Contributes to https://github.com/gravitational/teleport/issues/8166

This did encounter some merge conflicts, but I addressed them all, and doubled checked I caught all references with:

```console
$ rg 'apt ' docs
$ rg 'apt-get' docs
```

2021-12-06 18:46 UTC, webvictim approved these changes

2021-12-06 18:47 UTC, webvictim requested changes

2021-12-06 18:47 UTC, webvictim commented on docs/pages/getting-started.mdx
> +    curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
    curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-06 18:47 UTC, webvictim commented on docs/pages/installation.mdx
> +    curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
    curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-06 18:47 UTC, webvictim commented on docs/pages/server-access/getting-started.mdx
> +      curl -O https://get.gravitational.com/teleport-(=teleport.version=)_amd64.deb
```suggestion
      curl -O https://get.gravitational.com/teleport_(=teleport.version=)_amd64.deb
```

2021-12-08 22:16 UTC, russjones commented
@wadells I don't think we're taking this approach, so I am going to close this. Feel free to re-open if needed.

2021-12-08 22:16 UTC, closed without merging