Open log files with O_APPEND so log rotation can work properly
gravitational/teleport pull request #9468
Opened 2021-12-17 15:36 UTC by vrivanov-rb

If logging to a file is used, and external log rotation is setup e.g. with logrotate, teleport would end up creating a sparse file because `write`s to the log file opened without O_APPEND would resume writing to the last write location even though the log file might have been truncated by logrotate.

Fix this by opening the log file with O_APPEND. This will cause all subsequent `write`s to write to the end of the file, thus starting from the beginning of the empty file after a truncate has been performed by logrotate.

2022-01-05 19:40 UTC, r0mant approved these changes

2022-07-14 19:17 UTC, zmb3 approved these changes

2022-07-14 19:18 UTC, zmb3 commented
/gcbrun

2022-07-26 17:56 UTC, corkrean commented
Hey @vrivanov-rb, thanks for the change, we'd like to merge this. Can you rebase it or do you want us to take it over?

2022-07-27 17:17 UTC, russjones requested changes
https://github.com/gravitational/teleport/pull/6589

2023-11-16 20:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gravitational/teleport?pullRequest=9468) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gravitational/teleport?pullRequest=9468) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gravitational/teleport?pullRequest=9468) it.</sub>

2024-08-06 21:13 UTC, closed without merging